import type { NewsEvent } from "@/content/types/news";
import { UPLOADS } from "./uploads";

export const events2022: NewsEvent[] = [
  {
    id: "trikralova-sbirka-2022",
    title: "Tříkrálová sbírka 2022",
    start: "2022-01-01",
    end: "2022-01-16",
    place: "Kuřim",
    text: "Letos koledníci opět přijdou k vám, budou rozdávat radost a požehnání a prosit o příspěvek na lidi v nouzi.",
    body: "<p>Při posledním ročníku jsme se museli obejít bez koledníků. Letos přijdou (za dodržení epidemických opatření) a budou rozdávat radost a požehnání a prosit o příspěvek na lidi v nouzi. Jak přispět, pokud se s koledníky minete, najdete na webu sbírky.</p>",
    links: [{ label: "Tříkrálová sbírka", href: "https://www.trikralovasbirka.cz/" }],
  },
  {
    id: "vanocni-koncert-magnificat-2022",
    title: "Vánoční koncert",
    start: "2022-01-09",
    time: "18:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Chrámový sbor Magnificat a orchestr z Lelekovic zvou na koncert: V. J. Kopřiva, Missa pastoralis in D.",
    poster: {
      src: `${UPLOADS}/vanocni-koncert-magnificat-2022-plakat.webp`,
      alt: "Plakát: Vánoční koncert chrámového sboru Magnificat 9. 1. 2022",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/vanocni-koncert-magnificat-2022-plakat.pdf`, size: 107878 }],
  },
  {
    id: "den-modliteb-za-mir-na-ukrajine-2022",
    title: "Den modliteb za mír na Ukrajině",
    start: "2022-01-26",
    text: "Papež František vyhlásil středu 26. ledna dnem modliteb za mír na Ukrajině.",
    attachments: [
      { label: "Výzva papeže", file: `${UPLOADS}/den-modliteb-za-mir-na-ukrajine-2022-vyzva.pdf`, size: 193387 },
    ],
  },
  {
    id: "valentinska-pout-2022",
    title: "Valentinská pouť",
    start: "2022-02-13",
    time: "17:00",
    place: "Brno, kostel sv. Michala",
    mapQuery: "kostel sv. Michala, Dominikánské náměstí, Brno",
    text: "Pouť ke svatému Valentinovi v kostele sv. Michala na Dominikánském náměstí v Brně.",
    body: "<p>Po přednášce manželů Kvapilíkových „Zamilovanost je zadarmo, ale láska je dřina“ následuje bohoslužba k patronu lásky svatému Valentinovi, jehož jméno dalo základ „svátku všech zamilovaných“.</p>",
    poster: {
      src: `${UPLOADS}/valentinska-pout-2022-plakat.webp`,
      alt: "Plakát: Valentinská pouť 13. 2. 2022 v kostele sv. Michala v Brně",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/valentinska-pout-2022-plakat.pdf`, size: 507154 }],
  },
  {
    id: "narodni-tyden-manzelstvi-2022",
    title: "Národní týden manželství",
    start: "2022-02-14",
    end: "2022-02-20",
    text: "Nechte se inspirovat, jak ze svého dobrého manželství udělat ještě lepší, nebo obnovit to, co se časem ve vztahu vytratilo.",
    body: "<p>Ve valentýnském týdnu každý rok společně oslavujeme, jak moc pro nás manželství znamená.</p>",
    poster: {
      src: `${UPLOADS}/narodni-tyden-manzelstvi-2022-plakat.webp`,
      alt: "Plakát: Národní týden manželství 2022",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/narodni-tyden-manzelstvi-2022-plakat.pdf`, size: 149155 }],
    links: [{ label: "Národní týden manželství", href: "https://www.tydenmanzelstvi.cz/" }],
  },
  {
    id: "vecery-pro-dva-2022",
    title: "Večery pro dva",
    start: "2022-02-16",
    end: "2022-03-30",
    time: "19:00",
    place: "Brno, restaurace Era cafe",
    text: "Otevřená setkání pro páry zaměřená na podporu a rozvoj vztahu: večeře u stolků po dvou, krátká promluva a rozhovory v páru.",
    program: [
      { time: "16. 2.", title: "Přežít, nebo prožít?" },
      { time: "1. 3.", title: "Jak s růzností?" },
      { time: "16. 3.", title: "Nové začátky" },
      { time: "30. 3.", title: "Radost z lásky" },
    ],
    poster: { src: `${UPLOADS}/vecery-pro-dva-2022-informace.webp`, alt: "Leták: Večery pro dva" },
    attachments: [{ label: "Informace", file: `${UPLOADS}/vecery-pro-dva-2022-informace.pdf`, size: 1015226 }],
    links: [{ label: "Komunita Emmanuel", href: "https://www.emmanuel.cz/" }],
    sessions: ["2022-02-16", "2022-03-01", "2022-03-16", "2022-03-30"],
  },
  {
    id: "koncert-ucednici-2022",
    title: "Charitativní koncert skupiny Učedníci",
    start: "2022-02-20",
    time: "14:30",
    place: "Boskovice, kino Panorama",
    text: "Přijměte pozvání na charitativní koncert skupiny Učedníci v kině Panorama v Boskovicích.",
    poster: {
      src: `${UPLOADS}/koncert-ucednici-2022-plakat.webp`,
      alt: "Plakát: Charitativní koncert skupiny Učedníci 20. 2. 2022",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/koncert-ucednici-2022-plakat.pdf`, size: 1307930 }],
  },
  {
    id: "pomoc-ukrajine-2022",
    title: "Pomoc Ukrajině",
    start: "2022-02-27",
    text: "Přispět můžete převodem na účet Charity, nebo nabídnout ubytování lidem, kteří utíkají před válkou.",
    body:
      "<p>Dar na humanitární pomoc pošlete na účet <strong>55660022/0800</strong>, variabilní symbol <strong>104</strong>.</p>" +
      "<p>Ubytování pro lidi, kteří utíkají před válkou, nabízejte na krizové lince Charity 516 410 668 nebo 737 234 078: počet osob, které můžete ubytovat, na jak dlouho a zda jim zajistíte stravu. Krizová linka přijímá i další nabídky pomoci, například zdravotnický materiál nebo hygienické pomůcky.</p>",
    poster: { src: `${UPLOADS}/pomoc-ukrajine-2022-letak.webp`, alt: "Leták: Charita pro Ukrajinu" },
    attachments: [{ label: "Leták", file: `${UPLOADS}/pomoc-ukrajine-2022-letak.pdf`, size: 1515516 }],
  },
  {
    id: "postni-katecheze-2022",
    title: "Postní katecheze pro děti",
    start: "2022-03-02",
    end: "2022-04-16",
    text: "K prohlédnutí jsou postní katecheze pro děti z minulého roku.",
  },
  {
    id: "krizova-cesta-za-mir-2022",
    title: "Křížová cesta za mír",
    start: "2022-03-02",
    end: "2022-04-16",
    place: "Moravské Knínice, Mezihoří",
    text: "Křížová cesta přírodou z Mezihoří na Strážnou, letos s naléhavou prosbou za mír na celém světě.",
    body: "<p>Trasa je stejná jako loni a vede lesní stezkou z Mezihoří na Strážnou (viz mapka). Text je přizpůsoben především rodinám s dětmi, obrázky pocházejí od dětí z náboženství z let 2001/2002. Děkujeme všem, kteří se k modlitbě za mír připojí.</p>",
    attachments: [{ label: "Mapka trasy", file: `${UPLOADS}/krizova-cesta-za-mir-2022-mapka.pdf`, size: 321003 }],
  },
  {
    id: "sedm-slov-vykupitelovych-2022",
    title: "Sedm slov Vykupitelových",
    start: "2022-03-20",
    time: "15:00",
    place: "Čebín, kostel sv. Jiří",
    text: "Koncert smíšeného pěveckého sboru Rastislav v kostele sv. Jiří v Čebíně.",
    body: "<p>Koncert pořádá obec Čebín za podpory senátorky Jaromíry Vítkové. Dobrovolné vstupné bude věnováno Domácímu hospici Oblastní charity Tišnov.</p>",
    price: "dobrovolné vstupné",
    poster: {
      src: `${UPLOADS}/sedm-slov-vykupitelovych-2022-plakat.webp`,
      alt: "Plakát: Sedm slov Vykupitelových, koncert sboru Rastislav v Čebíně",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/sedm-slov-vykupitelovych-2022-plakat.pdf`, size: 644985 }],
  },
  {
    id: "dopisy-biskupa-vojtecha-2022",
    title: "Dopisy biskupa Vojtěcha",
    start: "2022-03-20",
    text: "Dva dopisy biskupa Vojtěcha: k zasvěcení Ruska a Ukrajiny Neposkvrněnému Srdci Panny Marie a s prosbou o pomoc uprchlíkům.",
    attachments: [
      {
        label: "Zasvěcení Ruska a Ukrajiny",
        file: `${UPLOADS}/dopisy-biskupa-vojtecha-2022-zasveceni.pdf`,
        size: 70354,
      },
      { label: "Pomoc uprchlíkům", file: `${UPLOADS}/dopisy-biskupa-vojtecha-2022-pomoc-uprchlikum.pdf`, size: 322651 },
    ],
  },
  {
    id: "zasveceni-ruska-a-ukrajiny-2022",
    title: "Zasvěcení Ruska a Ukrajiny",
    start: "2022-03-25",
    time: "17:30",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Modlitbou růžence se na dálku připojíme k zasvěcení Ruska a Ukrajiny Neposkvrněnému Srdci Panny Marie.",
    body: "<p>Papež František zasvětí Rusko a Ukrajinu Neposkvrněnému Srdci Panny Marie v pátek 25. března od 17:00 během modliteb za mír v bazilice sv. Petra v Římě. Přijďte se s námi pomodlit.</p>",
    attachments: [{ label: "Pozvánka", file: `${UPLOADS}/zasveceni-ruska-a-ukrajiny-2022-pozvanka.pdf`, size: 205449 }],
  },
  {
    id: "24-hodin-pro-pana-2022",
    title: "24 hodin pro Pána",
    start: "2022-03-25",
    end: "2022-03-26",
    place: "Tišnov, kostel sv. Václava",
    text: "Děkanství Tišnov zve do kostela sv. Václava k celodenní adoraci a ke svátosti smíření.",
    program: [
      { time: "pá 18:30", title: "Růženec" },
      { time: "pá 19:00", title: "Mše svatá" },
      { time: "pá 20:00 – so 21:00", title: "Adorace" },
      { time: "pá 18:00–22:00, so 19:00–21:00", title: "Svátost smíření", note: "nebo rozhovor s knězem" },
    ],
    poster: {
      src: `${UPLOADS}/24-hodin-pro-pana-2022-plakat.webp`,
      alt: "Plakát: 24 hodin pro Pána v kostele sv. Václava v Tišnově",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/24-hodin-pro-pana-2022-plakat.pdf`, size: 1717570 }],
  },
  {
    id: "postni-duchovni-obnova-2022",
    title: "Postní duchovní obnova",
    start: "2022-04-02",
    time: "9:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Postní duchovní obnova s P. Janem Pacnerem, dlouholetým vojenským kaplanem.",
    body: "<p>Drobné občerstvení bude zajištěno.</p>",
    program: [
      { time: "9:00", title: "Mše svatá", note: "kostel sv. Maří Magdalény" },
      { time: "10:00", title: "Promluva a prostor pro diskusi", note: "sál fary" },
      { time: "11:30", title: "Adorace a závěrečné požehnání" },
    ],
    poster: {
      src: `${UPLOADS}/postni-duchovni-obnova-2022-plakat.webp`,
      alt: "Plakát: Postní duchovní obnova s P. Janem Pacnerem 2. 4. 2022",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/postni-duchovni-obnova-2022-plakat.pdf`, size: 18273 }],
  },
  {
    id: "petrklic-2022-1",
    title: "Petrklíč 1/2022",
    start: "2022-04-08",
    text: "Vyšlo nové vydání farního časopisu Petrklíč. Tištěné výtisky jsou k dispozici pod kůrem v kuřimském kostele.",
    attachments: [{ label: "Petrklíč 1/2022", file: "/uploads/petrklic/2022-1/petrklic-2022-1.pdf", size: 4374333 }],
  },
  {
    id: "diecezni-setkani-mladeze-2022",
    title: "Diecézní setkání mládeže",
    start: "2022-04-09",
    place: "Brno, katedrála sv. Petra a Pavla",
    text: "Setkání mladých s biskupem Vojtěchem v brněnské katedrále.",
    poster: {
      src: `${UPLOADS}/diecezni-setkani-mladeze-2022-plakat.webp`,
      alt: "Plakát: Diecézní setkání mládeže 9. 4. 2022 v Brně",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/diecezni-setkani-mladeze-2022-plakat.pdf`, size: 838571 }],
  },
  {
    id: "krizova-cesta-prirodou-s-detmi-2022",
    title: "Křížová cesta přírodou s dětmi",
    start: "2022-04-09",
    time: "10:00",
    place: "Kuřim, kaple sv. Jana Nepomuckého",
    text: "Křížová cesta pro rodiny s dětmi, vhodná i pro kočárky, zakončená opékáním špekáčků na faře.",
    body:
      "<p>Sejdeme se u vodní kaple sv. Jana Nepomuckého. Po skončení cesty si na faře můžeme opéct špekáčky a ještě společně strávit pěkné chvíle. Špekáčky a pečivo si prosím vezměte vlastní, nezapomeňte na pití a na něco na psaní.</p>" +
      "<p>Budeme moc rádi, když se k rodinám připojíte i vy ostatní.</p>",
  },
  {
    id: "katecheze-ke-svatemu-tydnu-2022",
    title: "Katecheze ke Svatému týdnu",
    start: "2022-04-10",
    end: "2022-04-17",
    text: "K prohlédnutí jsou loňské katecheze pro děti k Velikonocům.",
  },
  {
    id: "den-pro-rodinu-2022",
    title: "Den pro rodinu",
    start: "2022-05-15",
    time: "14:00",
    place: "Kuřim, areál zámku",
    text: "Oslava Dne rodin se soutěžemi, skákacím hradem a hudebními vystoupeními.",
    body: "<p>Občerstvení je zajištěno, vstupné dobrovolné. Za nepříznivého počasí proběhne jen hudební vystoupení v kostele sv. Maří Magdalény.</p>",
    program: [
      { time: "14:00", title: "Začátek akce", note: "soutěže a hry, skákací hrad, malování na obličej" },
      { time: "14:30", title: "Vystoupení žáků ZUŠ Kuřim" },
      { time: "15:15", title: "Kuřimská schola" },
      { time: "16:00", title: "Pavel Helan" },
    ],
    price: "dobrovolné vstupné",
    poster: {
      src: `${UPLOADS}/den-pro-rodinu-2022-plakat.webp`,
      alt: "Plakát: Den pro rodinu 15. 5. 2022 v areálu zámku Kuřim",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/den-pro-rodinu-2022-plakat.pdf`, size: 1092639 }],
  },
  {
    id: "farni-den-2022",
    title: "Farní den",
    start: "2022-06-04",
    time: "14:00",
    place: "Kuřim, areál za farou",
    text: "Farní den s představením komunity Emmanuel, ukulele bandem, posezením u ohně a hrami pro děti.",
    body: "<p>Čeká vás soutěž o nej… jednohubku (doneste alespoň 20 kusů), posezení u ohně s živou hudbou a zábavné hry pro děti. Drobné občerstvení, které přinesete, je vítáno.</p>",
    program: [
      { time: "14:00", title: "Zahájení" },
      { time: "15:00", title: "Představení komunity Emmanuel" },
      { time: "16:00", title: "Představení projektu Mariánská triáda", note: "senátorka Ing. Jaromíra Vítková" },
    ],
    poster: { src: `${UPLOADS}/farni-den-2022-program.webp`, alt: "Plakát: Farní den 4. 6. 2022" },
    attachments: [{ label: "Program", file: `${UPLOADS}/farni-den-2022-program.pdf`, size: 31679 }],
  },
  {
    id: "jarni-koncert-2022",
    title: "Jarní koncert violoncellistů",
    start: "2022-06-05",
    time: "17:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Tradiční jarní koncert: Solitutticelli Brno Cello Sextet zahraje chrámovou a romantickou hudbu pro šest violoncell.",
    body: "<p>Na programu jsou skladby J. S. Bacha, D. Poppera, J. Haydna, F. Schuberta a C. Saint-Saënse. Vstupné dobrovolné.</p>",
    price: "dobrovolné vstupné",
    poster: {
      src: `${UPLOADS}/jarni-koncert-2022-plakat.webp`,
      alt: "Plakát: Chrámová a romantická hudba pro 6 violoncell, Solitutticelli Brno Cello Sextet",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/jarni-koncert-2022-plakat.pdf`, size: 239772 }],
  },
  {
    id: "noc-kostelu-2022",
    title: "Noc kostelů",
    start: "2022-06-10",
    time: "18:45–21:05",
    place: "Kuřim a Moravské Knínice",
    text: "Prohlídky kostelů, zpěvy chrámového sboru a modlitba za naše město.",
    program: [
      {
        time: "18:45–20:00",
        title: "Komentované prohlídky kostela sv. Markéty",
        note: "interiér, varhany, zvonice; zpívá místní schola",
      },
      { time: "19:00–20:00", title: "Prohlídka kostela sv. Maří Magdalény", note: "výklad na požádání" },
      { time: "19:00–19:30", title: "Zpěvy chrámového sboru", note: "Kuřim" },
      { time: "20:00–21:00", title: "Kdo zpívá, dvakrát se modlí", note: "Kuřim" },
      { time: "21:00–21:05", title: "Zakončení, modlitba a požehnání pro naše město", note: "Kuřim" },
    ],
    poster: { src: `${UPLOADS}/noc-kostelu-2022-program.webp`, alt: "Program: Noc kostelů 10. 6. 2022" },
    attachments: [{ label: "Program", file: `${UPLOADS}/noc-kostelu-2022-program.pdf`, size: 468729 }],
    links: [{ label: "Noc kostelů", href: "https://www.nockostelu.cz/" }],
  },
  {
    id: "dekanatni-setkani-mladeze-2022",
    title: "Děkanátní setkání mládeže",
    start: "2022-06-18",
    time: "13:00",
    place: "Tišnov",
    text: "Mladé zveme na děkanátní setkání v Tišnově a ostatní prosíme o podporu modlitbou.",
  },
  {
    id: "petrklic-2022-2",
    title: "Petrklíč 2/2022",
    start: "2022-06-19",
    text: "Vyšlo nové vydání farního časopisu Petrklíč.",
    attachments: [{ label: "Petrklíč 2/2022", file: "/uploads/petrklic/2022-2/petrklic-2022-2.pdf", size: 10529739 }],
  },
  {
    id: "varhanni-koncert-kninice-2022",
    title: "Varhanní koncert v Moravských Knínicích",
    start: "2022-06-26",
    time: "17:00",
    place: "Moravské Knínice, kostel sv. Markéty",
    text: "Varhanní koncert Hany Bartošové. Výtěžek bude věnován na opravy knínického kostela.",
  },
  {
    id: "cyrilometodejska-pout-2022",
    title: "Cyrilometodějská pouť ke sv. Klimentu",
    start: "2022-07-05",
    time: "14:00",
    place: "Lipůvka, kaple sv. Klimenta",
    text: "Pouť ke sv. Klimentu u Lipůvky začíná u kříže nad Lipůvkou (směr Nuzířov).",
    poster: {
      src: `${UPLOADS}/cyrilometodejska-pout-2022-plakat.webp`,
      alt: "Plakát: Cyrilometodějská pouť ke sv. Klimentu u Lipůvky",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/cyrilometodejska-pout-2022-plakat.jpg`, size: 216667 }],
  },
  {
    id: "koncert-good-work-2022",
    title: "Koncert Good Work",
    start: "2022-07-09",
    time: "17:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Koncert skupiny Good Work, jehož výtěžek bude věnován na opravy fary.",
    poster: {
      src: `${UPLOADS}/koncert-good-work-2022-plakat.webp`,
      alt: "Plakát: Koncert Good Work 9. 7. 2022 v Kuřimi",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/koncert-good-work-2022-plakat.jpg`, size: 237950 }],
    links: [{ label: "Good Work", href: "https://www.goodwork.cz/" }],
  },
  {
    id: "hody-2022",
    title: "Hody v obcích farnosti",
    start: "2022-07-15",
    end: "2022-07-24",
    place: "Moravské Knínice, Kuřim a Jinačovice",
    text: "Přijměte pozvání na Markétské hody v Moravských Knínicích, Babské hody v Kuřimi a Mladé hody v Jinačovicích.",
    program: [
      { time: "15.–17. 7.", title: "Markétské hody", note: "Moravské Knínice" },
      { time: "22.–24. 7.", title: "Mladé hody a den obce", note: "Jinačovice" },
      { time: "23. 7.", title: "Babské hody", note: "Kuřim, areál ZŠ Komenského" },
    ],
    poster: {
      src: `${UPLOADS}/hody-2022-plakat-kninice.webp`,
      alt: "Plakát: Markétské hody v Moravských Knínicích 15.–17. 7. 2022",
    },
    attachments: [
      {
        label: "Plakát: Markétské hody v Moravských Knínicích",
        file: `${UPLOADS}/hody-2022-plakat-kninice.pdf`,
        size: 644133,
      },
      { label: "Plakát: Mladé hody v Jinačovicích", file: `${UPLOADS}/hody-2022-plakat-jinacovice.pdf`, size: 364780 },
      { label: "Plakát: Babské hody v Kuřimi", file: `${UPLOADS}/hody-2022-plakat-kurim.pdf`, size: 535418 },
    ],
  },
  {
    id: "farni-tabor-2022",
    title: "Farní tábor 2022",
    start: "2022-08-13",
    end: "2022-08-20",
    place: "Hostinné",
    text: "Již čtvrtý farní tábor pro kluky a holky od 7 do 14 let.",
    body: "<p>Před táborem se koná seznamovací víkendovka 18.–19. června 2022 na kuřimské faře. Kontaktní osobou je Štěpánka Kytnerová.</p>",
    poster: {
      src: `${UPLOADS}/farni-tabor-2022-plakat.webp`,
      alt: "Plakát: Farní tábor 2022 pro kluky a holky od 7 do 14 let",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/farni-tabor-2022-plakat.pdf`, size: 672929 }],
  },
  {
    id: "diecezni-pout-rodin-2022",
    title: "Diecézní pouť rodin",
    start: "2022-08-27",
    time: "10:15",
    place: "Předklášteří, klášter Porta coeli",
    text: "18. diecézní pouť rodin s pontifikální mší svatou a bohatým programem pro všechny generace.",
    body: "<p>Zpovídat se bude dopoledne od 9:30 do 11:00 během růžence a mše svaté a odpoledne při adoraci od 13:00 do 14:00. Občerstvení lze zakoupit přímo v areálu.</p>",
    program: [
      { time: "10:15", title: "Pontifikální mše svatá", note: "hlavní celebrant biskup Pavel Konzbul" },
      {
        time: "od 12:15",
        title: "Duchovní a doprovodný program",
        note: "přednáška, divadélko, prohlídky, aktivity pro děti, adorace",
      },
      { time: "15:30", title: "Zakončení pouti a požehnání" },
    ],
    poster: {
      src: `${UPLOADS}/diecezni-pout-rodin-2022-plakat.webp`,
      alt: "Plakát: 18. diecézní pouť rodin 27. 8. 2022 v Předklášteří",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/diecezni-pout-rodin-2022-plakat.pdf`, size: 570647 }],
  },
  {
    id: "pout-sedmiradostnou-cestou-2022",
    title: "Pouť sedmiradostnou cestou",
    start: "2022-08-28",
    time: "7:00",
    place: "Česká, kaple Panny Marie Růžencové",
    text: "Pěší pouť po sedmiradostné cestě z České na Vranov, mše svatá na Vranově je v 11 hodin.",
    poster: {
      src: `${UPLOADS}/pout-sedmiradostnou-cestou-2022-plakat.webp`,
      alt: "Plakát: IV. výročí Vranovská pouť sedmiradostnou cestou 28. 8. 2022",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/pout-sedmiradostnou-cestou-2022-plakat.pdf`, size: 328734 }],
  },
  {
    id: "vranovske-pouti-2022",
    title: "Vranovské poutě k Panně Marii",
    start: "2022-09-03",
    end: "2022-10-02",
    place: "Vranov u Brna",
    text: "Přehled všech zářijových poutí k Panně Marii na Vranově.",
    attachments: [{ label: "Program poutí", file: `${UPLOADS}/vranovske-pouti-2022-program.pdf`, size: 304343 }],
  },
  {
    id: "medovy-den-2022",
    title: "Medový den",
    start: "2022-09-04",
    time: "10:00",
    place: "Kuřim, areál ZŠ Komenského",
    text: "Tradiční celodenní akce plná zábavy, pestrého programu a medu.",
  },
  {
    id: "cyklopout-na-vranov-2022",
    title: "Cyklopouť na Vranov",
    start: "2022-09-11",
    time: "12:30",
    place: "Kuřim, park na ulici Havlíčkova",
    text: "Cyklopouť z Kuřimi na odpolední mši svatou na Vranově v 15 hodin.",
    body: "<p>Tempo skupiny bude přizpůsobeno dětem. Ostatní poutníky rádi potkáme na Vranově na mši. Na kolech jedeme jen za nedeštivého počasí.</p>",
    poster: {
      src: `${UPLOADS}/cyklopout-na-vranov-2022-plakat.webp`,
      alt: "Plakát: Cyklopouť Kuřim – Vranov 11. 9. 2022",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/cyklopout-na-vranov-2022-plakat.pdf`, size: 472161 }],
  },
  {
    id: "vystava-clovek-a-vira-2022",
    title: "Výstava fotografií Člověk a Víra",
    start: "2022-09-14",
    end: "2022-09-25",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Výstava velkoformátových fotografií společenství Člověk a Víra. Vstup zdarma.",
    body:
      "<p>Člověk a Víra je společenství fotografů, kteří ve svém volném čase bez nároku na odměnu dokumentují život církve, sakrální architekturu a víru člověka obecně.</p>" +
      "<p>Výstavu si můžete prohlédnout před bohoslužbami a po nich a v neděli 18. září od 14:00 při Dni národnostních menšin.</p>",
    poster: {
      src: `${UPLOADS}/vystava-clovek-a-vira-2022-plakat.webp`,
      alt: "Plakát: Výstava velkoformátových fotografií Člověk a Víra",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/vystava-clovek-a-vira-2022-plakat.pdf`, size: 4118986 }],
    links: [{ label: "Člověk a Víra", href: "https://www.clovekavira.cz/" }],
  },
  {
    id: "den-narodnostnich-mensin-2022",
    title: "Den národnostních menšin",
    start: "2022-09-18",
    time: "14:00",
    place: "Kuřim, areál zámku",
    text: "Přijměte pozvání na Den národnostních menšin v areálu kuřimského zámku.",
    poster: {
      src: `${UPLOADS}/den-narodnostnich-mensin-2022-plakat.webp`,
      alt: "Plakát: Den národnostních menšin 18. 9. 2022 v areálu zámku Kuřim",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/den-narodnostnich-mensin-2022-plakat.jpg`, size: 1758856 }],
  },
  {
    id: "pesi-pout-na-vranov-2022",
    title: "Pěší pouť na Vranov",
    start: "2022-09-25",
    time: "7:00",
    place: "Moravské Knínice a Kuřim",
    text: "Tradiční pěší pouť s krojovaným procesím a Pannou Marií Vranovskou na mši svatou v 11 hodin.",
    program: [
      { time: "7:00", title: "Odchod z Moravských Knínic", note: "u č. p. 2" },
      { time: "7:20", title: "Odchod z Kuřimi", note: "u kostela, požehnání" },
      { time: "11:00", title: "Mše svatá na Vranově" },
    ],
    poster: {
      src: `${UPLOADS}/pesi-pout-na-vranov-2022-plakat.webp`,
      alt: "Plakát: Pěší pouť na Vranov 25. září 2022",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/pesi-pout-na-vranov-2022-plakat.pdf`, size: 1989129 }],
  },
  {
    id: "hody-v-ceske-2022",
    title: "Hody v České",
    start: "2022-09-30",
    end: "2022-10-02",
    place: "Česká",
    text: "Stavění máje, krojovaný průvod obcí, hodová zábava a mše svatá v Kuřimi.",
    body: "<p>Žehnání obci a hodovníkům bude po příchodu krojovaného průvodu ke kapli Panny Marie Růžencové v sobotu přibližně v 15 hodin.</p>",
    program: [
      { time: "pá 16:00", title: "Stavění máje", note: "stárci a hodová chasa" },
      {
        time: "so po 15:00",
        title: "Průvod obcí od sokolovny",
        note: "předání hodového práva, svěcení práva a vína u kapličky",
      },
      { time: "so 20:00", title: "Hodová zábava", note: "hraje DH Blučiňáci" },
      {
        time: "ne 11:00",
        title: "Mše svatá",
        note: "kostel sv. Maří Magdalény v Kuřimi, autobus odjíždí v 10:30 z návsi",
      },
      { time: "ne 17:00", title: "Posezení u cimbálu v sokolovně", note: "CM Primáš" },
    ],
    poster: { src: `${UPLOADS}/hody-v-ceske-2022-plakat.webp`, alt: "Plakát: Hody v České 30. 9. – 2. 10. 2022" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/hody-v-ceske-2022-plakat.pdf`, size: 2313217 }],
  },
  {
    id: "at-svoboda-zni-2022",
    title: "Ať svoboda zní",
    start: "2022-10-02",
    time: "18:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Srdečně zveme na koncert duchovní hudby Ať svoboda zní.",
    poster: {
      src: `${UPLOADS}/at-svoboda-zni-2022-plakat.webp`,
      alt: "Plakát: Koncert duchovní hudby Ať svoboda zní 2. 10. 2022",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/at-svoboda-zni-2022-plakat.jpg`, size: 541213 }],
  },
  {
    id: "petrklic-2022-3",
    title: "Petrklíč 3/2022",
    start: "2022-10-09",
    text: "Vyšlo nové vydání farního časopisu Petrklíč.",
    attachments: [{ label: "Petrklíč 3/2022", file: "/uploads/petrklic/2022-3/petrklic-2022-3.pdf", size: 16921150 }],
  },
  {
    id: "kurz-samuel-2022",
    title: "Kurz Samuel",
    start: "2022-10-09",
    end: "2023-08-29",
    text: "Jednoletý kurz pro mladé od 16 do 33 let, který pomáhá rozlišit a zvolit životní povolání. Přihlášky do 31. srpna.",
    body:
      "<p>Kurz připravil tým pastorace povolání v brněnské diecézi a vedou ho kněží a řeholní sestry z různých kongregací. Součástí je modlitba, ztišení, sdílení a duchovní doprovázení, na konci kurzu duchovní cvičení a pěší pouť.</p>" +
      "<p>Setkání jsou jednou měsíčně v neděli od 15 do 19 hodin na různých místech diecéze. Účast je bezplatná. Přihlášku s motivačním dopisem pošlete do 31. srpna 2022.</p>",
    attachments: [{ label: "Informace", file: `${UPLOADS}/kurz-samuel-2022-informace.pdf`, size: 355514 }],
    links: [
      { label: "Kurz Samuel na webu biskupství", href: "https://www.biskupstvi.cz/2022-05-23-kurz-samuel" },
      { label: "kurz.samuel@seznam.cz", href: "mailto:kurz.samuel@seznam.cz" },
    ],
    registrationDeadline: "2022-08-31",
    sessions: [
      "2022-10-09",
      "2022-11-13",
      "2022-12-11",
      "2023-01-15",
      "2023-02-12",
      "2023-03-12",
      "2023-04-23",
      "2023-05-14",
      "2023-06-11",
      { date: "2023-08-27", end: "2023-08-29" },
    ],
  },
  {
    id: "adoracni-den-2022",
    title: "Adorační den farnosti",
    start: "2022-10-12",
    time: "9:00–17:30",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Celodenní adorace v kuřimském kostele. Zapište se do archu pod kůrem, kdy přijdete adorovat.",
    body: "<p>Rozpis adoračních stráží je po půlhodinách. Adorace bude zakončena modlitbou růžence a v 18:00 mší svatou se zpěvem chrámového sboru.</p>",
  },
  {
    id: "misijni-nedele-2022",
    title: "Misijní neděle",
    start: "2022-10-23",
    text: "Světový den misií si letos připomíná 200. výročí Papežského misijního díla šíření víry. Podpořit ho můžete modlitbou i darem.",
    body: "<p>Dar můžete poslat na účet Papežského misijního díla šíření víry <strong>72540444/2700</strong>, variabilní symbol <strong>10</strong>. Za vaše modlitby a dary děkujeme.</p>",
    poster: { src: `${UPLOADS}/misijni-nedele-2022-plakat.webp`, alt: "Plakát: Misijní neděle 23. 10. 2022" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/misijni-nedele-2022-plakat.pdf`, size: 219156 }],
  },
  {
    id: "konference-o-evangelizaci-2022",
    title: "Konference o evangelizaci",
    start: "2022-11-11",
    end: "2022-11-12",
    place: "Olomouc, Clarion Congress Hotel",
    text: "V. konference o evangelizaci „Přinášejme naději, kterou máme v Bohu živém“: přednášky, workshopy, svědectví a chvály.",
    price: "200 Kč/den, studenti a mládež 100 Kč/den",
    poster: {
      src: `${UPLOADS}/konference-o-evangelizaci-2022-plakat.webp`,
      alt: "Plakát: V. konference o evangelizaci v Olomouci",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/konference-o-evangelizaci-2022-plakat.pdf`, size: 4279152 }],
    links: [{ label: "Konference o evangelizaci", href: "https://www.evangelizace.cz/" }],
  },
  {
    id: "tyden-modliteb-za-mladez-2022",
    title: "Týden modliteb za mládež",
    start: "2022-11-13",
    end: "2022-11-20",
    text: "Spojme se ve vzájemné modlitbě s mladými lidmi za mladé lidi.",
    poster: {
      src: `${UPLOADS}/tyden-modliteb-za-mladez-2022-plakat.webp`,
      alt: "Plakát: Týden modliteb za mládež 13.–20. 11. 2022",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/tyden-modliteb-za-mladez-2022-plakat.pdf`, size: 180886 }],
    links: [
      {
        label: "Týden modliteb za mládež",
        href: "https://www.cirkev.cz/cs/aktuality/220915tyden-modliteb-za-mladez-2022",
      },
    ],
  },
  {
    id: "charitativni-beh-2022",
    title: "Charitativní běh pro Ukrajinu",
    start: "2022-11-19",
    time: "10:00",
    place: "Lelekovice, vodojem Na Pasekách",
    text: "Přijďte si zaběhat a přispět na dobrou věc: 6. charitativní běh, jehož výtěžek půjde na konto SOS Ukrajina Člověka v tísni.",
    program: [
      { time: "10:00", title: "Prezence" },
      { time: "10:30", title: "Start", note: "u vodojemu Na Pasekách" },
    ],
    price: "dobrovolné startovné",
    poster: {
      src: `${UPLOADS}/charitativni-beh-2022-plakat.webp`,
      alt: "Plakát: 6. charitativní běh pro Ukrajinu 19. 11. 2022",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/charitativni-beh-2022-plakat.pdf`, size: 311298 }],
  },
  {
    id: "charitativni-jarmark-ceska-2022",
    title: "Charitativní jarmark v České",
    start: "2022-11-20",
    time: "13:30–16:30",
    place: "Česká, sokolovna",
    text: "Tradiční 22. farní charitativní jarmark, letos pro Ukrajinu. Výtěžek půjde na konto SOS Ukrajina Člověka v tísni.",
    body: "<p>Přispějte svým ručně vyrobeným zbožím nebo nabídněte své speciality do stánku s občerstvením. Příspěvky se shromažďují v sobotu 19. 11. od 17 do 18 hodin v sokolovně v České.</p>",
    poster: {
      src: `${UPLOADS}/charitativni-jarmark-ceska-2022-plakat.webp`,
      alt: "Plakát: 22. tradiční farní charitativní jarmark pro Ukrajinu",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/charitativni-jarmark-ceska-2022-plakat.pdf`, size: 701586 }],
  },
  {
    id: "cervena-streda-2022",
    title: "Červená středa",
    start: "2022-11-23",
    time: "17:00–20:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Připomeňme si všechny, kdo jsou pronásledováni pro víru: nasvícený kostel, mše svatá a tichá adorace.",
    program: [
      { time: "17:00–20:00", title: "Kostel nasvícený červeně" },
      { time: "18:00", title: "Mše svatá za lidi pronásledované pro víru" },
      { time: "po mši", title: "Tichá adorace a modlitba při svíčkách" },
    ],
    poster: { src: `${UPLOADS}/cervena-streda-2022-plakat.webp`, alt: "Plakát: Červená středa 23. listopadu 2022" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/cervena-streda-2022-plakat.pdf`, size: 4787221 }],
    links: [{ label: "Červená středa", href: "https://www.cervenastreda.cz/" }],
  },
  {
    id: "farni-silvestr-2022",
    title: "Farní silvestr",
    start: "2022-11-26",
    time: "15:00",
    place: "Kuřim",
    text: "Farní silvestr na konci církevního roku: mše svatá, vyprávění o pouti do Říma, dražba dortu, kvíz a ohňostroj.",
    program: [
      { time: "15:00", title: "Mše svatá" },
      { time: "16:30", title: "Pouť do Říma Petry Šiprové" },
      { time: "18:00", title: "Dražba dortu a kvíz" },
      { time: "19:00", title: "Hudba a ohňostroj" },
    ],
    poster: { src: `${UPLOADS}/farni-silvestr-2022-plakat.webp`, alt: "Plakát: Farní silvestr 26. listopadu 2022" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/farni-silvestr-2022-plakat.pdf`, size: 25860 }],
  },
  {
    id: "rozsviceni-vanocniho-stromu-2022",
    title: "Rozsvícení vánočního stromu",
    start: "2022-11-27",
    place: "Kuřim a Česká",
    text: "Slavnostní rozsvícení vánočního stromu v Kuřimi a v České.",
    program: [
      {
        time: "16:30",
        title: "Rozsvícení stromu v České",
        note: "u lípy, vystoupení dětí z MŠ Česká a sboru Lelkováček",
      },
      { time: "17:30", title: "Vystoupení ZUŠ Kuřim", note: "Kuřim, náměstí 1. května" },
      { time: "18:00", title: "Rozsvícení stromu v Kuřimi" },
    ],
    poster: {
      src: `${UPLOADS}/rozsviceni-vanocniho-stromu-2022-plakat-kurim.webp`,
      alt: "Plakát: Rozsvícení vánočního stromu 2022 v Kuřimi",
    },
    attachments: [
      { label: "Plakát: Kuřim", file: `${UPLOADS}/rozsviceni-vanocniho-stromu-2022-plakat-kurim.pdf`, size: 904712 },
      { label: "Plakát: Česká", file: `${UPLOADS}/rozsviceni-vanocniho-stromu-2022-plakat-ceska.pdf`, size: 1480829 },
    ],
  },
  {
    id: "adventni-duchovni-obnova-2022",
    title: "Adventní duchovní obnova",
    start: "2022-12-03",
    time: "9:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Adventní duchovní obnova s P. Zdeňkem Jančaříkem, salesiánem a spisovatelem.",
    program: [
      { time: "9:00", title: "Mše svatá", note: "kostel sv. Maří Magdalény" },
      { time: "10:00", title: "Promluva a diskuse", note: "sál fary" },
      { time: "11:30", title: "Adorace a závěrečné požehnání" },
    ],
    poster: {
      src: `${UPLOADS}/adventni-duchovni-obnova-2022-plakat.webp`,
      alt: "Plakát: Adventní duchovní obnova s P. Zdeňkem Jančaříkem 3. 12. 2022",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/adventni-duchovni-obnova-2022-plakat.jpg`, size: 174307 }],
  },
  {
    id: "zbigniew-czendlik-2022",
    title: "P. Zbigniew Czendlik v Kuřimi",
    start: "2022-12-07",
    time: "16:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Na mši svaté bude hostovat P. Zbigniew Czendlik, děkan v Lanškrouně.",
    body: "<p>Večer v 17:00 následuje setkání se Zbigniewem Czendlikem, které pořádá Společenské a kulturní centrum Kuřim.</p>",
    poster: {
      src: `${UPLOADS}/zbigniew-czendlik-2022-pozvanka.webp`,
      alt: "Pozvánka: Zbigniew Czendlik, středa 7. 12. 2022 v 17:00",
    },
    attachments: [{ label: "Pozvánka", file: `${UPLOADS}/zbigniew-czendlik-2022-pozvanka.pdf`, size: 179167 }],
  },
  {
    id: "petrklic-2022-4",
    title: "Petrklíč 4/2022",
    start: "2022-12-17",
    text: "Vyšlo nové vydání farního časopisu Petrklíč. Výtisky za 20 Kč jsou k dispozici v kuřimském kostele pod kůrem.",
    attachments: [{ label: "Petrklíč 4/2022", file: "/uploads/petrklic/2022-4/petrklic-2022-4.pdf", size: 6587270 }],
  },
  {
    id: "vystava-betlemu-2022",
    title: "Výstava betlémů",
    start: "2022-12-18",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Srdečně zveme na výstavu betlémů v oratořích kuřimského kostela.",
    links: [{ label: "Křesťanské Vánoce", href: "https://www.krestanskevanoce.cz/kostel/470/" }],
  },
  {
    id: "stedry-den-2022",
    title: "Štědrý den v kuřimském kostele",
    start: "2022-12-24",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Výstava betlémů, dětská katecheze s divadelní vánoční hrou a „půlnoční“ mše svatá se zpěvem chrámového sboru.",
    program: [
      { time: "13:00–15:00", title: "Výstava betlémů" },
      { time: "15:00", title: "Dětská katecheze", note: "s divadelní vánoční hrou a koledami" },
      { time: "22:00", title: "„Půlnoční“ mše svatá", note: "chrámový sbor zpívá Missu pastoralis J. Schreiera" },
    ],
    poster: { src: `${UPLOADS}/stedry-den-2022-program.webp`, alt: "Program: Štědrý den v kuřimském kostele 2022" },
    attachments: [{ label: "Program", file: `${UPLOADS}/stedry-den-2022-program.pdf`, size: 1170927 }],
  },
  {
    id: "zaznam-mse-bozi-hod-2022",
    title: "Zvukový záznam mše svaté na Boží hod",
    start: "2022-12-25",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Poslechněte si záznam mše svaté na Boží hod vánoční se zpěvem chrámového sboru.",
    attachments: [
      { label: "Záznam mše svaté", file: `${UPLOADS}/zaznam-mse-bozi-hod-2022-zaznam.mp3`, size: 32684452 },
    ],
  },
  {
    id: "vanocni-zpivani-zs-divizna-2022",
    title: "Vánoční zpívání ZŠ DiviZna",
    start: "2022-12-26",
    time: "16:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Přijměte pozvání na vánoční zpívání základní školy DiviZna.",
    poster: {
      src: `${UPLOADS}/vanocni-zpivani-zs-divizna-2022-plakat.webp`,
      alt: "Plakát: Vánoční zpívání ZŠ DiviZna",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/vanocni-zpivani-zs-divizna-2022-plakat.jpg`, size: 313278 }],
  },
];
