import type { NewsEvent } from "@/content/types/news";
import { UPLOADS } from "./uploads";

export const events2025: NewsEvent[] = [
  {
    id: "vanocni-koncert-magnificat-2025",
    title: "Vánoční koncert sboru Magnificat",
    start: "2025-01-05",
    end: "2025-01-12",
    place: "Lelekovice a Štěpánov nad Svratkou",
    text: "Chrámový sbor Magnificat a orchestr z Lelekovic zvou na vánoční koncert: Adam Michna z Otradovic, Missa super „Již Slunce z Hvězdy vyšlo“.",
    program: [
      { time: "5. 1. 17:00", title: "Koncert v Lelekovicích", note: "kostel sv. Filipa a Jakuba" },
      { time: "12. 1. 15:00", title: "Koncert ve Štěpánově nad Svratkou", note: "kostel sv. Petra a Pavla" },
    ],
    poster: {
      src: `${UPLOADS}/vanocni-koncert-magnificat-2025-plakat.webp`,
      alt: "Plakát: Vánoční koncert, Adam Michna z Otradovic – Missa super Již Slunce z Hvězdy vyšlo",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/vanocni-koncert-magnificat-2025-plakat.jpg`, size: 405248 }],
    sessions: [
      { date: "2025-01-05", time: "17:00" },
      { date: "2025-01-12", time: "15:00" },
    ],
  },
  {
    id: "diecezni-setkani-katechetu-2025",
    title: "Diecézní setkání katechetů",
    start: "2025-01-18",
    time: "9:00–15:30",
    place: "Brno, CMCZŠ Lerchova 65",
    text: "Diecézní setkání katechetů s biskupem, přednáškami a mší svatou.",
    poster: {
      src: `${UPLOADS}/diecezni-setkani-katechetu-2025-plakat.webp`,
      alt: "Plakát: Diecézní setkání katechetů 18. ledna 2025",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/diecezni-setkani-katechetu-2025-plakat.png`, size: 644632 }],
  },
  {
    id: "ekumenicke-setkani-2025",
    title: "Ekumenické setkání",
    start: "2025-01-22",
    time: "18:00",
    place: "Kuřim, Sbor Dr. Karla Farského",
    mapQuery: "Farského 349/22, Kuřim",
    text: "Ekumenické setkání v rámci Týdne modliteb za jednotu křesťanů, ve spolupráci s Církví československou husitskou.",
    body:
      "<p>Setkání se koná ve Sboru Dr. Karla Farského v ulici Farského 22 (u kuřimského nádraží). Letošní motto zní „Věříš tomu?“ (Jan 11,26).</p>" +
      "<p>Texty k setkání připravila ekumenická mnišská komunita v Bose v severozápadní Itálii.</p>",
    attachments: [{ label: "Pozvánka", file: `${UPLOADS}/ekumenicke-setkani-2025-pozvanka.pdf`, size: 68443 }],
  },
  {
    id: "dekanatni-setkani-pomocniku-v-kostele-2025",
    title: "Děkanátní setkání pomocníků v kostele",
    start: "2025-01-24",
    time: "18:00–20:00",
    place: "Tišnov, sál pod kinem Svratka",
    text: "Setkání floristů, květinářů, výzdobářů a uklízečů v kostele tišnovského děkanství.",
    program: [
      { time: "18:00", title: "Mše svatá v kostele sv. Václava" },
      {
        time: "19:00–20:00",
        title: "Setkání v sále pod kinem",
        note: "poděkování za službu, malé překvapení a sdílení",
      },
      { time: "20:00", title: "Závěrečné požehnání" },
    ],
    poster: {
      src: `${UPLOADS}/dekanatni-setkani-pomocniku-v-kostele-2025-plakat.webp`,
      alt: "Plakát: Děkanátní setkání floristů, květinářů, výzdobářů a uklízečů v kostele",
    },
    attachments: [
      { label: "Plakát", file: `${UPLOADS}/dekanatni-setkani-pomocniku-v-kostele-2025-plakat.png`, size: 1969671 },
    ],
  },
  {
    id: "seminar-zivot-v-duchu-2025",
    title: "Seminář Život v Duchu",
    start: "2025-01-26",
    end: "2025-03-30",
    time: "19:00",
    place: "Tišnov, fara",
    mapQuery: "Kostelní 16, Tišnov",
    text: "Desetitýdenní duchovní obnova v Tišnově pod vedením P. Petra Beneše, vždy v neděli večer.",
    body: "<p>Náplní zhruba dvouhodinových setkání je společná modlitba chval, uvedení do tématu, sdílení a adorace. Účastníci věnují také každý den čtvrthodinku modlitbě s Písmem svatým k tématům semináře. Seminář pomáhá obnovit vztah s Bohem a objevit vlastní obdarování.</p>",
    poster: { src: `${UPLOADS}/seminar-zivot-v-duchu-2025-plakat.webp`, alt: "Plakát: Seminář Život v Duchu, Tišnov" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/seminar-zivot-v-duchu-2025-plakat.pdf`, size: 2646507 }],
    sessions: [
      "2025-01-26",
      "2025-02-02",
      "2025-02-09",
      "2025-02-16",
      "2025-02-23",
      "2025-03-02",
      "2025-03-09",
      "2025-03-16",
      "2025-03-23",
      "2025-03-30",
    ],
  },
  {
    id: "postni-obnova-lomnice-2025",
    title: "Postní duchovní obnova v Lomnici",
    start: "2025-03-14",
    end: "2025-04-11",
    time: "17:30",
    place: "Lomnice u Tišnova, Orlovna",
    text: "Farnost Lomnice u Tišnova zve na postní duchovní obnovu na téma Jubilejní rok: mše svatá a po ní přednáška.",
    program: [
      { time: "14. 3.", title: "JUDr. Mgr. Václav Kotlár", note: "jáhen, Tišnov" },
      { time: "28. 3.", title: "S. M. Marka OP", note: "Žernůvka" },
      { time: "11. 4.", title: "P. Jiří Landa, ISch", note: "farní vikář, Tišnov" },
    ],
    poster: {
      src: `${UPLOADS}/postni-obnova-lomnice-2025-plakat.webp`,
      alt: "Plakát: Postní duchovní obnova v Lomnici, téma Jubilejní rok",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/postni-obnova-lomnice-2025-plakat.jpg`, size: 504241 }],
    sessions: ["2025-03-14", "2025-03-28", "2025-04-11"],
  },
  {
    id: "koncert-scholy-brnenske-mladeze-2025",
    title: "Koncert Scholy brněnské mládeže",
    start: "2025-03-16",
    time: "18:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Zazpívá Schola brněnské mládeže (SBM) za doprovodu kapely a komorního orchestru.",
    body: "<p>Akci finančně podpořilo město Kuřim.</p>",
    price: "dobrovolné vstupné",
    poster: {
      src: `${UPLOADS}/koncert-scholy-brnenske-mladeze-2025-plakat.webp`,
      alt: "Plakát: Koncert Scholy brněnské mládeže 16. března 2025",
    },
    attachments: [
      { label: "Plakát", file: `${UPLOADS}/koncert-scholy-brnenske-mladeze-2025-plakat.jpg`, size: 415057 },
    ],
  },
  {
    id: "postni-duchovni-obnova-kurim-2025",
    title: "Postní duchovní obnova v Kuřimi",
    start: "2025-03-22",
    time: "17:00",
    place: "Kuřim, fara",
    text: "Duchovní obnova na téma Křížová cesta našeho Pána Ježíše Krista jako příprava na Velikonoce. Vede P. Jaroslav Filka.",
    body: "<p>Volně navážeme na téma z loňského roku.</p>",
    poster: {
      src: `${UPLOADS}/postni-duchovni-obnova-kurim-2025-plakat.webp`,
      alt: "Plakát: Postní duchovní obnova na téma Křížová cesta našeho Pána Ježíše Krista",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/postni-duchovni-obnova-kurim-2025-plakat.pdf`, size: 125945 }],
  },
  {
    id: "dekovna-mse-pierre-goursat-2025",
    title: "Děkovná mše za ctihodného Pierra Goursata",
    start: "2025-03-24",
    time: "17:30",
    place: "Brno, kostel sv. Tomáše",
    text: "Děkovná mše svatá za uznání hrdinských ctností Pierra Goursata, zakladatele komunity Emmanuel.",
    body:
      "<p>Papež František uznal hrdinské ctnosti Pierra Goursata na konci roku 2024. Mše se slaví v předvečer slavnosti Zvěstování Páně, která je zároveň dnem Pierrova návratu k Otci.</p>" +
      "<p>Pierre Goursat je spolu s Martine Laffitte-Catta zakladatelem komunity Emmanuel. Modlitební společenství, které původně založili, se rychle rozrostlo na komunitu po celé Francii a následně do celého světa.</p>",
    poster: {
      src: `${UPLOADS}/dekovna-mse-pierre-goursat-2025-plakat.webp`,
      alt: "Plakát: Ctihodný Pierre Goursat, děkovná mše svatá",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/dekovna-mse-pierre-goursat-2025-plakat.pdf`, size: 833149 }],
  },
  {
    id: "postni-obnova-pro-zeny-2025",
    title: "Postní duchovní obnova pro ženy",
    start: "2025-03-27",
    end: "2025-03-28",
    place: "Brno-Husovice, fara",
    text: "Duchovní obnova pro ženy s Pavlou Cenkovou na téma Učednictví ve světle zjevení Nejsvětějšího srdce Ježíšova.",
    body: "<p>Program zahrnuje promluvy, adoraci (také soukromou celonoční), mši svatou a sdílení ve skupinkách. V sobotu bude možnost svátosti smíření a duchovního rozhovoru s bratrem Didakem.</p>",
    program: [
      { time: "pátek 19:00", title: "Úvodní informace a večeře" },
      { time: "pátek 20:00", title: "I. promluva a adorace" },
      { time: "sobota 9:00", title: "II. promluva a společná adorace" },
      { time: "sobota 12:00", title: "Mše svatá" },
      { time: "sobota 14:00", title: "III. promluva" },
      { time: "sobota 17:00", title: "Závěr" },
    ],
    poster: {
      src: `${UPLOADS}/postni-obnova-pro-zeny-2025-informace.webp`,
      alt: "Leták: Postní duchovní obnova pro ženy s Pavlou Cenkovou",
    },
    attachments: [{ label: "Informace", file: `${UPLOADS}/postni-obnova-pro-zeny-2025-informace.pdf`, size: 3754252 }],
  },
  {
    id: "kurz-pro-pruvodce-2025",
    title: "Kurz pro průvodce v sakrálním prostoru",
    start: "2025-03-29",
    time: "9:00–16:00",
    place: "Brno, Biskupství brněnské",
    mapQuery: "Petrov 2, Brno",
    text: "Diecézní muzeum Brno pořádá kurz pro průvodce v kostelech a dalších sakrálních prostorech.",
    body: "<p>Na kurzu se seznámíte s historií a uměním sakrálních prostor a naučíte se provádět návštěvníky a předávat jim informace o daném místě. Kurz se koná v sále Biskupství brněnského, Petrov 2.</p>",
    registrationDeadline: "2025-03-23",
    poster: {
      src: `${UPLOADS}/kurz-pro-pruvodce-2025-plakat.webp`,
      alt: "Plakát: Kurz pro průvodce v sakrálním prostoru",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/kurz-pro-pruvodce-2025-plakat.jpg`, size: 639231 }],
  },
  {
    id: "pastyrsky-list-o-nadeji-2025",
    title: "Pastýřský list biskupa Pavla o naději",
    start: "2025-03-30",
    text: "Pastýřský list biskupa Pavla Konzbula o naději, čtený při bohoslužbách na neděli Laetare.",
    attachments: [
      { label: "Pastýřský list", file: `${UPLOADS}/pastyrsky-list-o-nadeji-2025-pastyrsky-list.pdf`, size: 67701 },
    ],
  },
  {
    id: "uprava-dopravy-kurim-2025",
    title: "Úprava dopravy u fary",
    start: "2025-04-02",
    end: "2025-08-31",
    place: "Kuřim, ulice Zámecká a Křížkovského",
    text: "Kvůli stavbě nové autobusové zastávky v ulici Zámecká bude v okolí fary dočasně upravený provoz.",
    body:
      "<p>Ulice Zámecká a Křížkovského budou jednosměrné. Pro osobní dopravu bude zavedena objízdná trasa ulicí Křížkovského s náhradní zastávkou u fary, nákladní doprava pojede přes Moravské Knínice.</p>" +
      "<p>Výstavba proběhne ve dvou etapách, druhá krátkodobě omezí vjezd ke garážím.</p>",
    attachments: [
      { label: "Informace města Kuřimi", file: `${UPLOADS}/uprava-dopravy-kurim-2025-informace.pdf`, size: 695415 },
    ],
  },
  {
    id: "dotaznik-farnost-2025",
    title: "Dotazník k životu v kuřimské farnosti",
    start: "2025-04-06",
    end: "2025-05-04",
    text: "Dotazník shromažďuje podněty k prohloubení života naší farnosti a pomáhá rozpoznat, na co se do budoucna zaměřit. Vyplnit jej bylo možné do 4. května.",
  },
  {
    id: "velikonoce-2025",
    title: "Pořad velikonočních bohoslužeb a zpovídání",
    start: "2025-04-10",
    end: "2025-04-21",
    place: "Kuřim a Moravské Knínice",
    text: "Bohoslužby, zpovídání, adorace a křížové cesty o Velikonocích v Kuřimi a v Moravských Knínicích.",
    body:
      "<ul>" +
      "<li><strong>Zelený čtvrtek 17. 4.:</strong> mše svatá v 18:00, adorace a zpovídání do 22:00 v Kuřimi</li>" +
      "<li><strong>Velký pátek 18. 4.:</strong> křížová cesta ve 14:00 v Chudčicích, velkopáteční obřady v 18:00 v Kuřimi, křížová cesta ulicemi Kuřimi ve 20:00</li>" +
      "<li><strong>Bílá sobota 19. 4.:</strong> adorace u Božího hrobu 8:00–10:00, vigilie ve 20:00 v Kuřimi</li>" +
      "<li><strong>Neděle Zmrtvýchvstání 20. 4.:</strong> mše svaté v 8:00 a 9:30 v Kuřimi, v 11:00 v Moravských Knínicích</li>" +
      "</ul>" +
      "<p>Pašije se zpívají na Květnou neděli v 8:00 a na Velký pátek při obřadech. Chrámový sbor zpívá na Bílou sobotu ve 20:00 a o slavnosti Zmrtvýchvstání v 9:30.</p>",
    attachments: [
      { label: "Pořad bohoslužeb a zpovídání", file: `${UPLOADS}/velikonoce-2025-porad-bohosluzeb.pdf`, size: 78482 },
    ],
  },
  {
    id: "petrklic-2025-1",
    title: "Petrklíč 1/2025",
    start: "2025-04-11",
    text: "Právě vyšlo nové vydání farního zpravodaje Petrklíč.",
    attachments: [{ label: "Petrklíč 1/2025", file: "/uploads/petrklic/2025-1/petrklic-2025-1.pdf", size: 1363130 }],
  },
  {
    id: "velikonoce-v-altottingu-2025",
    title: "Velikonoce v Altöttingu",
    start: "2025-04-17",
    end: "2025-04-21",
    place: "Altötting, Německo",
    text: "Velikonoční setkání pro mladé v bavorském poutním místě Altötting.",
    poster: {
      src: `${UPLOADS}/velikonoce-v-altottingu-2025-plakat.webp`,
      alt: "Plakát: Velikonoce v Altöttingu, velikonoční setkání pro mladé",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/velikonoce-v-altottingu-2025-plakat.png`, size: 1748263 }],
  },
  {
    id: "dekanatni-setkani-mladeze-2025",
    title: "Děkanátní setkání mládeže",
    start: "2025-04-26",
    time: "10:00",
    place: "Lomnice u Tišnova, kostel Navštívení Panny Marie",
    text: "Děkanátní setkání mládeže s mottem „Jsem poutníkem naděje“.",
    program: [
      { time: "10:00", title: "Registrace" },
      { time: "10:30", title: "Mše svatá" },
      { time: "11:30", title: "Herní putování Lomnicí" },
      { time: "13:15", title: "Oběd" },
      { time: "14:30", title: "Přednášky podle výběru" },
      { time: "16:00", title: "Koncert v synagoze" },
    ],
    poster: {
      src: `${UPLOADS}/dekanatni-setkani-mladeze-2025-plakat.webp`,
      alt: "Plakát: Děkanátní setkání mládeže 2025 v Lomnici u Tišnova",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/dekanatni-setkani-mladeze-2025-plakat.png`, size: 754122 }],
  },
  {
    id: "ministrantsky-den-2025",
    title: "Ministrantský den v Olomouci",
    start: "2025-05-03",
    place: "Olomouc",
    text: "Setkání ministrantů v Olomouci.",
    registrationDeadline: "2025-03-24",
    poster: {
      src: `${UPLOADS}/ministrantsky-den-2025-plakat.webp`,
      alt: "Plakát: Ministrantský den v Olomouci 3. května 2025",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/ministrantsky-den-2025-plakat.jpg`, size: 471528 }],
  },
  {
    id: "den-rodin-2025",
    title: "Den rodin",
    start: "2025-05-18",
    time: "14:00",
    place: "Kuřim, areál ZŠ Komenského",
    text: "Zábavné odpoledne pro celé rodiny: soutěže pro děti, skákací hrady, malování na obličej, bublinový workshop, kouzelník a taneční vystoupení.",
    program: [
      { time: "14:00", title: "Zahájení" },
      { time: "14:15", title: "Vystoupení T-Group Dance" },
      { time: "15:00", title: "Vystoupení kouzelníka" },
      { time: "15:30", title: "Bublinová show" },
      { time: "16:15", title: "Taneční vystoupení Lumíku" },
      { time: "17:00", title: "Vystoupení T-Group Dance" },
    ],
    price: "dobrovolné vstupné",
    poster: {
      src: `${UPLOADS}/den-rodin-2025-plakat.webp`,
      alt: "Plakát: Den rodin v areálu ZŠ Komenského 18. 5. 2025",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/den-rodin-2025-plakat.pdf`, size: 137222 }],
  },
  {
    id: "setkani-katechetu-2025",
    title: "Setkání katechetů",
    start: "2025-05-22",
    time: "17:30",
    place: "Tišnov, fara",
    text: "Setkání katechetů tišnovského děkanství: vzájemné sdílení a účast Diecézního katechetického centra.",
    poster: {
      src: `${UPLOADS}/setkani-katechetu-2025-plakat.webp`,
      alt: "Plakát: Setkání katechetů tišnovského děkanství 22. května 2025",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/setkani-katechetu-2025-plakat.pdf`, size: 489700 }],
  },
  {
    id: "noc-kostelu-2025",
    title: "Noc kostelů",
    start: "2025-05-23",
    place: "Vranov u Brna a Česká",
    text: "Noc kostelů na Vranově a v kapli Panny Marie Růžencové v České.",
    body: "<p>Kaple v České je otevřena od 18:00 do 22:00: prohlídka, výklad o historii kapličky a obce Česká, staré dokumenty a fotografie, růženec a malé občerstvení.</p>",
    poster: {
      src: `${UPLOADS}/noc-kostelu-2025-program-vranov.webp`,
      alt: "Program Noci kostelů 23. 5. 2025 na Vranově",
    },
    attachments: [
      { label: "Program: Vranov", file: `${UPLOADS}/noc-kostelu-2025-program-vranov.jpg`, size: 217218 },
      { label: "Program: Česká", file: `${UPLOADS}/noc-kostelu-2025-program-ceska.pdf`, size: 165221 },
    ],
    links: [{ label: "Noc kostelů", href: "https://www.nockostelu.cz/" }],
  },
  {
    id: "noc-kostelu-full-of-life-2025",
    title: "Noc kostelů a festival Full of Life v Řečkovicích",
    start: "2025-05-23",
    end: "2025-05-24",
    place: "Brno-Řečkovice",
    text: "Tradiční Noc kostelů a farní festival Full of Life v Řečkovicích.",
    links: [
      {
        label: "Farnost Řečkovice",
        href: "https://farnostreckovice.cz/2025/03/06/noc-kostelu-a-festival-full-of-life/",
      },
    ],
  },
  {
    id: "promitani-filmu-chatrc-2025",
    title: "Promítání filmu Chatrč",
    start: "2025-05-29",
    time: "16:00–19:30",
    place: "Kuřim, kinosál SKC",
    mapQuery: "Společenské a kulturní centrum Kuřim",
    text: "Promítání filmu Chatrč s následnou diskusí a občerstvením pro mladé od 15 do 25 let. Pořádá společenství mladých.",
    body: "<p>Je možné odpustit neodpustitelné? Proč je to důležité? Kým je pro křesťany Bůh a jak může vypadat snaha filmařsky ho přiblížit? Diskuse po filmu se soustředí na témata a poselství snímku. Vstup byl zdarma po registraci.</p>",
    price: "zdarma",
    poster: {
      src: `${UPLOADS}/promitani-filmu-chatrc-2025-plakat.webp`,
      alt: "Plakát: Tam, kde končí bolest… promítání filmu Chatrč",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/promitani-filmu-chatrc-2025-plakat.pdf`, size: 573979 }],
  },
  {
    id: "oslavy-790-let-moravskych-kninic-2025",
    title: "790 let Moravských Knínic",
    start: "2025-06-06",
    end: "2025-06-08",
    place: "Moravské Knínice",
    text: "Moravské Knínice oslavují 790 let obce. Oslavy vyvrcholí nedělní mší svatou a koncertem Jiřího Pavlici s Hradišťanem.",
    body: "<p>Program zahrnuje taneční zábavu, den otevřených dveří, program pro děti, divadelní představení a besedu u cimbálu.</p>",
    poster: {
      src: `${UPLOADS}/oslavy-790-let-moravskych-kninic-2025-plakat.webp`,
      alt: "Plakát: 790 let obce Moravské Knínice",
    },
    attachments: [
      { label: "Plakát", file: `${UPLOADS}/oslavy-790-let-moravskych-kninic-2025-plakat.jpg`, size: 162746 },
    ],
  },
  {
    id: "farni-den-2025",
    title: "Farní den",
    start: "2025-06-14",
    time: "14:00",
    place: "Kuřim, areál fary",
    text: "Farní den s mottem „Být poutníky naděje“. Novinkou je dopolední evangelizace ve spolupráci s komunitou Emmanuel.",
    body: "<p>Všichni jste srdečně zváni zapojit se do misijní iniciativy i do upevňování vztahů v naší farnosti.</p>",
    program: [
      { time: "10:00", title: "Mše svatá", note: "kostel sv. Maří Magdalény" },
      {
        time: "15:00",
        title: "Program v areálu fary",
        note: "Radovan Voříšek: Impuls o naději, prezentace Charity Tišnov, zážitky z evangelizace, aktivity pro děti",
      },
      { time: "17:30", title: "Zpívání u táboráku" },
    ],
    poster: {
      src: `${UPLOADS}/farni-den-2025-plakat.webp`,
      alt: "Plakát: Farní den 14. 6. 2025, motto být poutníky naděje",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/farni-den-2025-plakat.png`, size: 1958683 }],
  },
  {
    id: "zalmy-nejsou-zalozpevy-2025",
    title: "Žalmy nejsou žalozpěvy",
    start: "2025-06-15",
    time: "17:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Tradiční koncert duchovní hudby: Brněnský ekumenický sbor a komorní orchestr barokních nástrojů pod vedením Luboše Rause uvedou díla renesančních a barokních skladatelů.",
    price: "dobrovolné vstupné",
    poster: {
      src: `${UPLOADS}/zalmy-nejsou-zalozpevy-2025-plakat.webp`,
      alt: "Plakát: Brněnský ekumenický sbor – Žalmy nejsou žalozpěvy",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/zalmy-nejsou-zalozpevy-2025-plakat.pdf`, size: 592596 }],
  },
  {
    id: "zpivejte-hospodinu-pisen-novou-2025",
    title: "Zpívejte Hospodinu píseň novou",
    start: "2025-06-15",
    time: "17:00",
    place: "Moravské Knínice, kostel sv. Markéty",
    text: "Koncert Brněnského varhanního festivalu: na varhany hraje Přemysl Kšica, zpívá sopranistka Karolína Janů.",
    body: "<p>Koncert pořádají Římskokatolická farnost Kuřim a Klub moravských skladatelů.</p>",
    price: "dobrovolné vstupné",
    poster: {
      src: `${UPLOADS}/zpivejte-hospodinu-pisen-novou-2025-plakat.webp`,
      alt: "Plakát: Zpívejte Hospodinu píseň novou, varhanní koncert v Moravských Knínicích",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/zpivejte-hospodinu-pisen-novou-2025-plakat.pdf`, size: 246478 }],
  },
  {
    id: "petrklic-2025-2",
    title: "Petrklíč 2/2025",
    start: "2025-06-22",
    text: "Právě vyšlo nové vydání farního zpravodaje Petrklíč.",
    attachments: [{ label: "Petrklíč 2/2025", file: "/uploads/petrklic/2025-2/petrklic-2025-2.pdf", size: 4311596 }],
  },
  {
    id: "farni-tabor-2025",
    title: "Farní tábor 2025",
    start: "2025-08-09",
    end: "2025-08-16",
    place: "Velké Vrbno, chata Olšanka",
    text: "Letní farní tábor pro děti od 8 do 15 let.",
    body: "<p>Předtáborová víkendovka se konala 7.–8. června na faře v Kuřimi.</p>",
    price: "3 700 Kč",
    poster: { src: `${UPLOADS}/farni-tabor-2025-plakat.webp`, alt: "Plakát: Farní letní tábor 9.–16. 8. 2025" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/farni-tabor-2025-plakat.pdf`, size: 2418984 }],
  },
  {
    id: "diecezni-pout-rodin-2025",
    title: "Diecézní pouť rodin",
    start: "2025-08-30",
    time: "9:30",
    place: "Brno, bazilika Nanebevzetí Panny Marie",
    mapQuery: "Mendlovo náměstí, Brno",
    text: "Diecézní pouť rodin k Jubileu 2025: mši svatou celebruje biskup Pavel Konzbul, potom následuje program pro rodiny.",
    program: [
      { time: "9:30", title: "Mše svatá", note: "celebruje brněnský biskup Mons. Pavel Konzbul" },
      {
        time: "od 10:30",
        title: "Program pro rodiny v areálu Augustiniánského opatství",
        note: "stanoviště pro děti, divadlo Mikro-teatro, volný vstup do Mendelova muzea, malování na obličej",
      },
    ],
    poster: {
      src: `${UPLOADS}/diecezni-pout-rodin-2025-plakat.webp`,
      alt: "Plakát: Diecézní pouť rodin k Jubileu 2025",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/diecezni-pout-rodin-2025-plakat.jpg`, size: 223819 }],
    links: [
      {
        label: "Program pouti",
        href: "https://www.crsp.cz/nabizime/duchovni-programy/diecezni-pout-rodin",
      },
    ],
  },
  {
    id: "marianske-pouti-2025",
    title: "Mariánské poutě na Vranově a v Žarošicích",
    start: "2025-08-31",
    end: "2025-09-21",
    place: "Vranov u Brna a Žarošice",
    text: "Kuřimská farnost organizuje nebo podporuje tři tradiční mariánské poutě.",
    program: [
      {
        time: "31. 8. 7:00",
        title: "7. pouť Sedmiradostnou cestou Česká – Lelekovice – Vranov",
        note: "z České od kapličky, z Lelekovic v 7:45, mše svatá v 11:00",
      },
      {
        time: "13. 9.",
        title: "Zlatá sobota v Žarošicích",
        note: "krojovaný světelný průvod se soškami Panny Marie po hlavní mši",
      },
      {
        time: "21. 9. 7:00",
        title: "13. pěší pouť Moravské Knínice – Kuřim – Vranov",
        note: "z Kuřimi v 7:20 po požehnání u kostela, krojované procesí na mši v 11:00",
      },
    ],
    poster: {
      src: `${UPLOADS}/marianske-pouti-2025-plakat-pesi-pout.webp`,
      alt: "Plakát: Pěší pouť kuřimské farnosti na Vranov 21. září 2025",
    },
    attachments: [
      {
        label: "Plakát: Pěší pouť na Vranov",
        file: `${UPLOADS}/marianske-pouti-2025-plakat-pesi-pout.pdf`,
        size: 897287,
      },
      {
        label: "Plakát: Sedmiradostná cesta",
        file: `${UPLOADS}/marianske-pouti-2025-plakat-sedmiradostna-cesta.pdf`,
        size: 333651,
      },
      {
        label: "Plakát: Zlatá sobota v Žarošicích",
        file: `${UPLOADS}/marianske-pouti-2025-plakat-zlata-sobota.jpg`,
        size: 130513,
      },
      { label: "Program vranovských poutí", file: `${UPLOADS}/marianske-pouti-2025-program-vranov.pdf`, size: 239743 },
    ],
  },
  {
    id: "hody-ceska-2025",
    title: "Hody v České",
    start: "2025-10-03",
    end: "2025-10-05",
    place: "Česká",
    text: "Přijměte pozvání na tradiční hody v České.",
    poster: { src: `${UPLOADS}/hody-ceska-2025-plakat.webp`, alt: "Plakát: Hody v České 3.–5. 10. 2025" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/hody-ceska-2025-plakat.pdf`, size: 1970857 }],
  },
  {
    id: "obnova-pro-rodice-s-detmi-2025",
    title: "Duchovní obnova pro rodiče s dětmi",
    start: "2025-10-04",
    place: "Brno, Lidická 24",
    text: "Nadechni se: duchovní obnova pro rodiče malých dětí, kterou pořádá komunita Emmanuel. Přednáška, chvály, sdílení a čas pro pár.",
    poster: {
      src: `${UPLOADS}/obnova-pro-rodice-s-detmi-2025-plakat.webp`,
      alt: "Plakát: Nadechni se, duchovní obnova pro rodiče malých dětí",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/obnova-pro-rodice-s-detmi-2025-plakat.jpg`, size: 137136 }],
    links: [{ label: "Komunita Emmanuel", href: "https://www.emmanuel.cz/" }],
  },
  {
    id: "at-svoboda-zni-2025",
    title: "Ať svoboda zní",
    start: "2025-10-05",
    time: "18:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Koncert duchovní hudby k výročí projevu Martina Luthera Kinga „Mám sen“. Vystoupí Dej Nám Akord – DNA a Simply Gospel.",
    body: "<p>Akce se koná s podporou města Kuřimi.</p>",
    price: "dobrovolné vstupné",
    poster: {
      src: `${UPLOADS}/at-svoboda-zni-2025-plakat.webp`,
      alt: "Plakát: Koncert duchovní hudby Ať svoboda zní 5. 10. 2025",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/at-svoboda-zni-2025-plakat.pdf`, size: 4668134 }],
  },
  {
    id: "obnova-o-odpusteni-krtiny-2025",
    title: "Duchovní obnova o odpuštění ve Křtinách",
    start: "2025-10-11",
    time: "9:00",
    place: "Křtiny, kostel Jména Panny Marie",
    text: "Duchovní obnovu o odpuštění povede Vendula Zachovalová s hosty. Zváni jsou všichni, zvláště snoubenci a manželské páry.",
    program: [
      { time: "9:00", title: "První přednáška" },
      { time: "10:00", title: "Druhá přednáška" },
      { time: "11:00", title: "Mše svatá" },
    ],
    poster: {
      src: `${UPLOADS}/obnova-o-odpusteni-krtiny-2025-plakat.webp`,
      alt: "Plakát: Duchovní obnova o odpuštění ve Křtinách 11. října 2025",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/obnova-o-odpusteni-krtiny-2025-plakat.pdf`, size: 1043856 }],
  },
  {
    id: "adoracni-den-2025",
    title: "Adorační den farnosti",
    start: "2025-10-12",
    time: "13:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Adorační den naší farnosti s adoračními strážemi po půlhodinách.",
    body: "<p>Na adoraci se bylo možné zapsat do archu pod kůrem nebo do sdílené tabulky.</p>",
    program: [
      { time: "13:00", title: "Výstav Nejsvětější svátosti" },
      { time: "18:00", title: "Modlitba růžence a požehnání" },
    ],
  },
  {
    id: "prednaska-tomase-petracka-2025",
    title: "Přednáška prof. Tomáše Petráčka v Tišnově",
    start: "2025-10-16",
    time: "19:00",
    place: "Tišnov, sál pod kinem",
    text: "Přednáška katolického teologa prof. Tomáše Petráčka „Víra a naděje v rozdělené společnosti: role církve a charity v minulosti a dnes“.",
    body: "<p>Vstupné je dobrovolné a podpoří Oblastní charitu Tišnov.</p>",
    price: "dobrovolné vstupné",
    poster: {
      src: `${UPLOADS}/prednaska-tomase-petracka-2025-plakat.webp`,
      alt: "Plakát: Přednáška prof. Tomáše Petráčka Víra a naděje v rozdělené společnosti",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/prednaska-tomase-petracka-2025-plakat.png`, size: 3926335 }],
  },
  {
    id: "setkani-modliteb-matek-2025",
    title: "Setkání Modliteb matek",
    start: "2025-10-17",
    time: "17:45",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Setkání hnutí křesťanských žen Modlitby matek. Zvány jsou všechny ženy.",
    program: [
      { time: "17:45", title: "Slovo koordinátorek a svědectví" },
      { time: "18:45", title: "Společná modlitba matek", note: "a dotazy" },
    ],
    poster: {
      src: `${UPLOADS}/setkani-modliteb-matek-2025-pozvanka.webp`,
      alt: "Pozvánka: Setkání Modliteb matek v kostele sv. Maří Magdalény v Kuřimi",
    },
    attachments: [{ label: "Pozvánka", file: `${UPLOADS}/setkani-modliteb-matek-2025-pozvanka.pdf`, size: 907784 }],
  },
  {
    id: "laborator-pastoracnich-prilezitosti-2025",
    title: "Laboratoř pastoračních příležitostí a projektů",
    start: "2025-10-18",
    place: "Brno, Biskupské gymnázium",
    mapQuery: "Biskupské gymnázium Brno, Barvičova",
    text: "Jednodenní seminář brněnské diecéze o vizích, plánování a propagaci farních aktivit.",
    body: "<p>Seminář dále nabídne pastorační náměty pro budování farních společenství a prorodinnou pastoraci. Přihlášení bylo možné přes web Biskupství brněnského.</p>",
    poster: {
      src: `${UPLOADS}/laborator-pastoracnich-prilezitosti-2025-plakat.webp`,
      alt: "Plakát: Laboratoř pastoračních příležitostí a projektů 18. 10. 2025",
    },
    attachments: [
      { label: "Plakát", file: `${UPLOADS}/laborator-pastoracnich-prilezitosti-2025-plakat.jpg`, size: 765445 },
    ],
  },
  {
    id: "petrklic-2025-3",
    title: "Petrklíč 3/2025",
    start: "2025-10-23",
    text: "Právě vyšlo nové vydání farního zpravodaje Petrklíč.",
    attachments: [{ label: "Petrklíč 3/2025", file: "/uploads/petrklic/2025-3/petrklic-2025-3.pdf", size: 22934136 }],
  },
  {
    id: "ministrantska-olympiada-2025",
    title: "Ministrantská olympiáda",
    start: "2025-11-08",
    time: "8:00",
    place: "Újezd u Brna",
    text: "Šlapanické děkanství pořádá pro všechny ministranty Ministrantskou olympiádu v Újezdě u Brna a okolí.",
    price: "200 Kč za osobu",
    registrationDeadline: "2025-10-12",
    poster: {
      src: `${UPLOADS}/ministrantska-olympiada-2025-plakat.webp`,
      alt: "Plakát: Ministrantská olympiáda 8. listopadu 2025",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/ministrantska-olympiada-2025-plakat.jpg`, size: 212928 }],
  },
  {
    id: "predstaveni-vysledku-dotazniku-2025",
    title: "Představení výsledků dotazníku",
    start: "2025-11-09",
    time: "10:45",
    place: "Kuřim, fara",
    text: "Pastorační rada zve na představení výsledků dotazníku k životu farnosti. Prostor bude i pro vaše otázky, názory a komentáře.",
  },
  {
    id: "setkani-pastoracnich-rad-2025",
    title: "Setkání členů pastoračních rad tišnovského děkanství",
    start: "2025-11-18",
    time: "18:00–19:30",
    place: "Tišnov, sál pod kinem",
    text: "2. setkání členů pastoračních rad Děkanství tišnovské. Vstup zdarma, drobné občerstvení zajištěno.",
    body: "<p>Na programu jsou témata „Kde jsme“ a „Učíme se vidět dobré věci“, novinky a očekávané akce v brněnské diecézi, jedinečnost děkanství a práce ve skupinách.</p>",
    poster: {
      src: `${UPLOADS}/setkani-pastoracnich-rad-2025-plakat.webp`,
      alt: "Plakát: 2. setkání členů pastoračních rad Děkanství tišnovské",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/setkani-pastoracnich-rad-2025-plakat.jpg`, size: 316521 }],
  },
  {
    id: "charitativni-beh-a-jarmark-2025",
    title: "Charitativní běh a jarmark",
    start: "2025-11-22",
    end: "2025-11-23",
    place: "Lelekovice a Česká",
    text: "9. charitativní běh a 25. farní charitativní jarmark. Výtěžek bude zaslán na sbírku SOS Ukrajina organizace Člověk v tísni.",
    program: [
      {
        time: "22. 11. 10:00",
        title: "Charitativní běh",
        note: "prezence u vodojemu Na Pasekách v Lelekovicích, start v 10:30",
      },
      { time: "23. 11. 14:00–18:00", title: "Charitativní jarmark", note: "sokolovna v České, neděle Krista Krále" },
    ],
    poster: {
      src: `${UPLOADS}/charitativni-beh-a-jarmark-2025-plakat-jarmark.webp`,
      alt: "Plakát: 25. farní charitativní jarmark 23. 11. 2025 v sokolovně v České",
    },
    attachments: [
      {
        label: "Plakát: Charitativní běh",
        file: `${UPLOADS}/charitativni-beh-a-jarmark-2025-plakat-beh.jpg`,
        size: 398700,
      },
      {
        label: "Plakát: Charitativní jarmark",
        file: `${UPLOADS}/charitativni-beh-a-jarmark-2025-plakat-jarmark.jpg`,
        size: 444664,
      },
    ],
  },
  {
    id: "jubilejni-pout-hnuti-a-spolecenstvi-2025",
    title: "Jubilejní pouť hnutí a společenství",
    start: "2025-11-28",
    time: "17:30",
    place: "Brno, Petrov",
    text: "Brněnská diecéze zve hnutí a modlitební společenství na jubilejní pouť na Petrov.",
    program: [
      { time: "17:30", title: "Mše svatá s biskupem Pavlem" },
      { time: "18:15", title: "Svědectví Zdeňka Nekuly" },
      { time: "18:30", title: "Modlitba chval", note: "kapela For HIM" },
      { time: "20:00", title: "Nikodémova noc" },
    ],
    poster: {
      src: `${UPLOADS}/jubilejni-pout-hnuti-a-spolecenstvi-2025-plakat.webp`,
      alt: "Plakát: Jubilejní pouť hnutí a modlitebních společenství v brněnské diecézi",
    },
    attachments: [
      { label: "Plakát", file: `${UPLOADS}/jubilejni-pout-hnuti-a-spolecenstvi-2025-plakat.jpg`, size: 361075 },
    ],
  },
  {
    id: "farni-silvestr-2025",
    title: "Farní silvestr",
    start: "2025-11-29",
    time: "17:00",
    place: "Kuřim, kostel sv. Maří Magdalény a fara",
    text: "Společenství mladých zve na Farní silvestr na konci liturgického roku, letos k 20. výročí Petrklíče.",
    program: [
      { time: "17:00", title: "Zahajovací mše svatá", note: "kostel sv. Maří Magdalény" },
      { time: "18:00", title: "Program na faře k 20. výročí Petrklíče" },
      { time: "18:30", title: "Panelová diskuse redaktorů Petrklíče" },
      { time: "19:30", title: "Kvíz", note: "tvůrčí koutek pro děti a soutěž o nejlepšího „šneka“" },
    ],
    poster: { src: `${UPLOADS}/farni-silvestr-2025-plakat.webp`, alt: "Plakát: Farní silvestr 29. 11. 2025" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/farni-silvestr-2025-plakat.pdf`, size: 403452 }],
  },
  {
    id: "promena-farnosti-2025",
    title: "Proměna farnosti",
    start: "2025-12-08",
    time: "19:00",
    place: "Tišnov, fara",
    text: "Kurz Launch Point se Zuzanou Palátovou pro všechny, kdo chtějí být motorem farnosti.",
    body: "<p>Kurz nabízí modlitbu, rozjímání, video a diskusi i čas skupinového rozlišování. Přejděte z udržovacího režimu k misijnímu zápalu!</p>",
    poster: {
      src: `${UPLOADS}/promena-farnosti-2025-plakat.webp`,
      alt: "Plakát: Proměna farnosti 8. 12. 2025 v Tišnově",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/promena-farnosti-2025-plakat.jpg`, size: 328784 }],
    links: [{ label: "Proměna farnosti", href: "https://www.promenafarnosti.cz/" }],
  },
  {
    id: "petrklic-2025-4",
    title: "Petrklíč 4/2025",
    start: "2025-12-12",
    text: "Právě vyšlo nové vydání farního zpravodaje Petrklíč.",
    attachments: [{ label: "Petrklíč 4/2025", file: "/uploads/petrklic/2025-4/petrklic-2025-4.pdf", size: 21913779 }],
  },
  {
    id: "adventni-duchovni-obnova-2025",
    title: "Adventní duchovní obnova",
    start: "2025-12-13",
    time: "9:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Adventní duchovní obnova s P. Michaelem Martinkem na téma Naděje v současném světě a v adventu.",
    body: "<p>Obnova začíná mší svatou, po ní následuje promluva a prostor pro otázky. P. Michael Martinek je salesián, teolog, cestovatel a autor videí Očima křesťana.</p>",
  },
  {
    id: "vanocni-pribeh-2025",
    title: "Vánoční příběh",
    start: "2025-12-24",
    time: "15:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Na Štědrý den vás zveme na Vánoční příběh. Přijďte prožít vánoční atmosféru.",
    poster: {
      src: `${UPLOADS}/vanocni-pribeh-2025-plakat.webp`,
      alt: "Plakát: Vánoční příběh 24. prosince 2025 v 15 hodin",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/vanocni-pribeh-2025-plakat.pdf`, size: 12033092 }],
  },
  {
    id: "pastorely-2025",
    title: "Pastorely",
    start: "2025-12-25",
    time: "8:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Pastorely při mši svaté o slavnosti Narození Páně.",
    body: "<p>Zazní „Poslyšte, bratři jen“ Petra Chaloupského, „Quem vidistis pastores“ F. X. Brixiho a „Vzhůru, pastýřové“ J. J. Ryby. Sólový zpěv Anna Keprtová, varhanní doprovod Jan Čáp.</p>",
    poster: {
      src: `${UPLOADS}/pastorely-2025-plakat.webp`,
      alt: "Plakát: Pastorely při mši svaté o slavnosti Narození Páně",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/pastorely-2025-plakat.pdf`, size: 73402 }],
  },
  {
    id: "vanocni-zpivani-zs-divizna-2025",
    title: "Vánoční zpívání ZŠ DiviZna",
    start: "2025-12-26",
    time: "16:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Přijměte pozvání na vánoční zpívání Základní školy DiviZna.",
    poster: {
      src: `${UPLOADS}/vanocni-zpivani-zs-divizna-2025-pozvanka.webp`,
      alt: "Pozvánka: Vánoční zpívání ZŠ DiviZna",
    },
    attachments: [
      { label: "Pozvánka", file: `${UPLOADS}/vanocni-zpivani-zs-divizna-2025-pozvanka.jpg`, size: 1532840 },
    ],
  },
];
