import { links } from "./site";
import type { ActivityGroup } from "./types/activities";

/*
 * Seznam aktivit (design/DESIGN.md §25), from the old site's /aktivity, shortened like the design. MK = Moravské
 * Knínice. Contacts are names only; add a phone or e-mail only for people who agreed (GDPR).
 */
export const activityGroups: ActivityGroup[] = [
  {
    id: "pravidelne",
    title: "Pravidelné",
    color: "green",
    activities: [
      { name: "Ministranti", contacts: "Michal Císař, Standa Krčma (MK)" },
      { name: "Kostelníci", contacts: "Standa Krčma (MK) · v Kuřimi hledáme" },
      { name: "Varhaníci", contacts: "Jan Čáp, Ljuba Klok, Jana Přikrylová (MK), Karel Dvořák (MK)" },
      {
        name: "Úklid kostela",
        when: "1× týdně, pátek nebo sobota dle rozpisu",
        contacts: "Anička Drahovská, Ivana Koláčková (MK)",
      },
      { name: "Květinová výzdoba kostela", contacts: "Katka Šťastná, Ivana Koláčková (MK)" },
      {
        name: "Praní a žehlení kostelních plachet",
        when: "asi 4× za rok",
        contacts: "Jiřina Krčmová, Ivana Koláčková (MK)",
      },
      { name: "Farní brigády", when: "občas, podle potřeby", contacts: "Milan Císař, Standa Krčma (MK)" },
      {
        name: "Schola Kuřim",
        when: "1× měsíčně doprovází dětské mše",
        contacts: "Lenka Psotová",
        href: links.schola,
      },
      { name: "Schola MK", when: "1× měsíčně doprovází mše", contacts: "Maruška Dvořáková, Romana Helanová" },
      { name: "Dětská scholička MK", when: "v neděli před mší", contacts: "Pavlína Kurková, Romana Helanová" },
      { name: "Chrámový sbor", contacts: "Adam Janík, Jan Čáp" },
      { name: "Farní kavárna", when: "každou neděli po mši v 10:30", contacts: "Tomáš Planer" },
      { name: "Společenství mládeže", contacts: "Olda Sychra, Lexa Krška" },
      {
        name: "Společenství chlapů",
        when: "každé 2 týdny v úterý ve 20:15",
        contacts: "Mirek Strašák, Karel Jelínek",
      },
      {
        name: "Boží pokec",
        when: "obvykle poslední neděli v měsíci",
        contacts: "Veronika Planerová, Martin Strašák",
      },
      { name: "Obědy pro p. faráře", contacts: "Maruška Dvořáková" },
      { name: "Vyučování náboženství", contacts: "otec Jaroslav", href: links.religiousEducation },
      { name: "Katecheze pro děti", when: "každou neděli při 2. mši", contacts: "Jana Kytnerová" },
      {
        name: "Komunita Emmanuel",
        when: "prvopáteční adorace, 1× měsíčně v sobotu",
        contacts: "Ladislav a Veronika Bobčíkovi",
      },
      {
        name: "Nedělní modlitby chval",
        when: "obvykle poslední neděli v měsíci v 9:00",
        contacts: "Martin Strašák",
      },
      { name: "Živý růženec", when: "denní modlitba", contacts: "Dana Gabrielová (MK), Anička Drahovská" },
      { name: "Modlitby matek (MK)", when: "každou středu dopoledne", contacts: "Terka Hermanová (MK)" },
      { name: "Růženec na dálku", when: "každé pondělí večer", contacts: "Milan Císař" },
      { name: "Křížová cesta na Strážnou", when: "celoroční stezka", contacts: "Hanka Švábová" },
    ],
  },
  {
    id: "sprava",
    title: "Správa a komunikace",
    color: "blue",
    activities: [
      { name: "Ohlášky, intence, mše", contacts: "otec Jaroslav, Standa Krčma (MK)" },
      { name: "Správa webu", contacts: "Ondra Planer" },
      { name: "Hromadné e-maily", contacts: "Milan Císař" },
      { name: "Sociální sítě (FB, IG)", contacts: "Milan Císař, Ondra Planer, Eva Fialová" },
      { name: "Farní Google kalendář", contacts: "Ondra Planer, Milan Císař" },
      { name: "Pastorační rada farnosti", contacts: "otec Jaroslav a členové PRF" },
      { name: "Ekonomická rada farnosti", contacts: "otec Jaroslav" },
      { name: "Sportovní areál (Orel)", contacts: "Aleš Hanák" },
    ],
  },
  {
    id: "jednorazove",
    title: "Jednorázové a roční",
    color: "magenta",
    activities: [
      { name: "Oslavy 800 let", when: "během celého roku", contacts: "Pavel Rajmic" },
      { name: "Tříkrálová sbírka", contacts: "Anička Drahovská" },
      { name: "Farní ples", contacts: "Tomáš Večeřa" },
      { name: "Křížové cesty", contacts: "Milan Císař, Hanka Prokopová, Eva Fialová" },
      { name: "Pletení velikonočních žil", contacts: "Milan Císař" },
      { name: "Den rodin", contacts: "Pavel Sádlík" },
      { name: "Novéna k Duchu svatému", contacts: "Komunita Emmanuel" },
      { name: "Noc kostelů", contacts: "Pavel Rajmic, Standa Krčma (MK)" },
      { name: "Varhanní koncert", contacts: "Ivana Koláčková (MK)" },
      { name: "Koncert filharmoniků", contacts: "David Keprt" },
      { name: "Farní den", contacts: "hledáme" },
      { name: "Poutní zájezdy", contacts: "Lída Císařová" },
      { name: "Farní dovolená rodin v Jeseníkách", contacts: "manželé Drahovští" },
      { name: "Farní tábor", contacts: "Tomáš Planer" },
      { name: "Pěší pouť Sedmiradostnou cestou na Vranov", contacts: "Bára Jordanová (Česká)" },
      { name: "Den národnostních menšin", contacts: "otec Jaroslav" },
      { name: "Pěší pouť na Vranov", contacts: "Milan Císař, Hanka Švábová (MK)" },
      { name: "Adorační den kuřimské farnosti", contacts: "Milan Císař" },
      { name: "Misijní neděle v MK", contacts: "Romana Helanová, Hanka Švábová" },
      { name: "Misijní kavárna", contacts: "Zuzka Jelínková" },
      { name: "Misijní koláč", contacts: "Zuzka Jelínková" },
      { name: "Charitativní jarmark a běh v České", contacts: "Bára Jordanová (Česká)" },
      { name: "Červená středa", contacts: "Tomáš Večeřa" },
      { name: "Farní silvestr", contacts: "společenství mládeže" },
      { name: "Duchovní obnovy", contacts: "Katka Rajmicová" },
      { name: "Živý betlém v MK", contacts: "Pavlína Kurková" },
      { name: "Výstava betlémů", contacts: "Milan Císař" },
      { name: "Betlémské světlo", contacts: "skauti" },
    ],
  },
];
