import { archivedEvents, UPLOADS } from "./news-archive";
import type { NewsEvent } from "./types";

// Mock content written from the live site's news and the Aktuality, Archiv and Detail mockups on 3. 10. 2026.
// Attachments without a known upload name use placeholder file names.

export const events: NewsEvent[] = [
  {
    id: "jubileum-800",
    title: "Slavnostní mše k jubileu 800 let",
    start: "2026-10-18",
    time: "9:30",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Zveme vás na slavnostní mši k jubileu 800 let kostela sv. Maří Magdalény, založeného roku 1226. Po mši je připraveno pohoštění.",
    lead: "Kostel sv. Maří Magdalény stojí v Kuřimi od roku 1226. Oslavte s námi jeho 800. výročí.",
    body:
      "<p>Letos slavíme 800 let od založení našeho kostela sv. Maří Magdalény. Zveme vás na slavnostní mši svatou, při které poděkujeme za všechny generace, které se v kostele modlily.</p>" +
      "<p>Mši doprovodí zpěvem dětská schola. Po mši jste všichni srdečně zváni do misijní kavárny na faře.</p>",
    program: [
      { time: "9:30", title: "Slavnostní mše svatá", note: "zpívá dětská schola" },
      { time: "po mši", title: "Misijní kavárna", note: "fara, Křížkovského 55/5" },
    ],
    highlights: {
      title: "800 let v datech",
      items: [
        { value: "1226", label: "založení kostela" },
        { value: "1772", label: "benedikce" },
        { value: "1889", label: "konsekrace" },
      ],
    },
    mapQuery: "kostel sv. Maří Magdalény Kuřim",
    attachments: [{ label: "Plakát", file: `${UPLOADS}/6ab538eec7721.Plakát.png` }],
    pinned: true,
  },
  {
    id: "hody-ceska",
    title: "Hody v České",
    start: "2026-10-02",
    end: "2026-10-04",
    place: "Česká",
    text: "Srdečně zveme na tradiční hody v České – stavění máje, průvod a koncert.",
    attachments: [{ label: "Plakát", file: `${UPLOADS}/6abcdf48ca24c.Plakát.png` }],
  },
  {
    id: "kolac-pro-hospic",
    title: "Koláč pro hospic",
    start: "2026-10-07",
    place: "Kuřim a okolí",
    text: "Podpořte svým darem Domácí hospic Porta Vitae. Přispět můžete také online.",
    attachments: [{ label: "Plakát", file: `${UPLOADS}/6ab932eedf2ab.Plakát.png` }],
    links: [{ label: "Koláč pro hospic", href: "https://tisnov.charita.cz/kolac-pro-hospic" }],
  },
  {
    id: "setkani-lektoru",
    title: "Děkanátní setkání lektorů Božího slova",
    start: "2026-10-09",
    end: "2026-10-10",
    place: "Tišnov",
    text: "Setkání lektorů Božího slova tišnovského děkanství. Provází MgA. Martina Pavlíková.",
    attachments: [{ label: "Pozvánka", file: `${UPLOADS}/setkani-lektoru.Pozvánka.png` }],
  },
  {
    id: "manzelske-vecery",
    title: "Manželské večery pro Tišnov a okolí",
    start: "2026-10-11",
    end: "2026-11-22",
    time: "18:00–20:30",
    place: "Tišnov",
    text: "Sedm nedělních setkání pro posílení vašeho vztahu.",
    attachments: [{ label: "Plakát", file: `${UPLOADS}/manzelske-vecery.Plakát.pdf` }],
    sessions: 7,
  },
  {
    id: "adoracni-den-2026",
    title: "Adorační den kuřimské farnosti",
    start: "2026-10-12",
    time: "13:00–18:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    mapQuery: "kostel sv. Maří Magdalény Kuřim",
    text: "Zveme všechny farníky k adoraci v kuřimském kostele – přijít můžete kdykoliv od 13 do 18 hodin.",
    lead: "Přijďte se zastavit před Nejsvětější svátostí – na chvíli, nebo na celé odpoledne.",
    program: [
      { time: "13:00", title: "Začátek adorace" },
      { time: "17:30", title: "Společná modlitba růžence" },
      { time: "18:00", title: "Závěrečné požehnání celé farnosti" },
    ],
  },
  {
    id: "hubertska-mse",
    title: "Hubertská mše",
    start: "2026-10-25",
    time: "9:30",
    place: "Kuřim",
    text: "Mši pořádají Lesy města Brna, a. s.",
    attachments: [{ label: "Pozvánka", file: `${UPLOADS}/hubertska-mse.Pozvánka.pdf` }],
  },
  {
    id: "pout-lukov-trebic",
    title: "Farní pouť do Lukova a adventní Třebíče",
    start: "2026-12-19",
    place: "Lukov a Třebíč",
    text: "Pouť do Lukova u Moravských Budějovic, rodiště blahoslaveného Jana Buly, a na adventní Třebíč. Cena 300 Kč.",
    attachments: [{ label: "Plakát", file: `${UPLOADS}/6ab933039e92d.Plakát.png` }],
    links: [{ label: "poutnicimkk@seznam.cz", href: "mailto:poutnicimkk@seznam.cz" }],
    price: "300 Kč",
    registrationDeadline: "2026-10-10",
  },
  {
    id: "obnova-v-duchu-svatem",
    title: "Obnova v Duchu svatém",
    start: "2026-10-01",
    end: "2027-04-29",
    place: "Brno, Lidická",
    text: "Seminář obnovy v Duchu svatém.",
    attachments: [{ label: "Pozvánka", file: `${UPLOADS}/6a40e5b1026d7.Pozvánka3.png` }],
    links: [{ label: "emmanuel.cz", href: "https://www.emmanuel.cz/obnova/" }],
    longTerm: { weeklyAt: "18:30" },
  },
  {
    id: "otcovo-srdce",
    title: "Seminář Otcovo srdce",
    start: "2026-03-01",
    end: "2026-11-30",
    place: "dle programu",
    text: "Seminář, který vám pomůže objevit lásku a dobrotu Nebeského Otce.",
    attachments: [{ label: "Informace", file: `${UPLOADS}/otcovo-srdce.Informace.pdf` }],
    longTerm: true,
  },
  {
    id: "prvokomunikanti",
    title: "Setkání prvokomunikantů s biskupem Pavlem",
    start: "2026-10-01",
    time: "9:00–14:30",
    place: "Brno, Petrov",
    text: "Setkání prvokomunikantů s otcem biskupem Pavlem na Petrově v Brně.",
    attachments: [{ label: "Plakát", file: `${UPLOADS}/6aa647e209023.Plakát.png` }],
  },
  {
    id: "medovy-den",
    title: "Stánek farnosti na Medovém dni",
    start: "2026-09-20",
    place: "Kuřim",
    text: "Děkujeme všem, kteří pomohli s farním stánkem.",
  },

  ...archivedEvents,
];
