import { archivedEvents, UPLOADS } from "./news-archive";
import type { NewsEvent } from "@/content/types/news";

// This year's aktuality, added with the farnost-create-aktualita skill (the first ones migrated from the old site's
// database). Earlier years are in news-archive/.

export const events: NewsEvent[] = [
  {
    id: "trikralovy-koncert-2026",
    title: "Tříkrálový koncert",
    start: "2026-01-13",
    time: "18:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Základní umělecká škola a Klub přátel ZUŠ Kuřim zvou na Tříkrálový koncert.",
    poster: { src: `${UPLOADS}/trikralovy-koncert-2026-plakat.webp`, alt: "Plakát: Tříkrálový koncert 13. 1. 2026" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/trikralovy-koncert-2026-plakat.pdf`, size: 1893689 }],
  },
  {
    id: "farni-ples-2026",
    title: "Farní ples",
    start: "2026-01-16",
    time: "19:00",
    place: "Kuřim, Společenské a kulturní centrum",
    text: "První farní ples v roce oslav 800 let města. K tanci zahraje kapela 9K BAND a Cimbálová muzika Kyničan, připravena je i tombola.",
    body:
      "<p>Místenky lze koupit v kulturním centru, na faře nebo v Moravských Knínicích. S dotazy a rezervacemi skupin se můžete obrátit na Tomáše Večeřu.</p>" +
      "<p>Na ples jsou zváni všichni. Pořadatelé uvítají pomoc s šířením plakátů a příspěvky do tomboly.</p>",
    price: "místenka 350 Kč, večeře 150 Kč",
    poster: { src: `${UPLOADS}/farni-ples-2026-plakat.webp`, alt: "Plakát: Farní ples 16. ledna 2026" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/farni-ples-2026-plakat.png`, size: 445524 }],
  },
  {
    id: "kurz-mission-possible-2026",
    title: "Kurz Mission Possible",
    start: "2026-01-17",
    end: "2026-04-14",
    place: "Brno, komunita Emmanuel",
    text: "Kurz dialogu a misie pro angažované křesťany: jak předávat víru a hledat odpovědi na otázky misie v dnešní době.",
    body: "<p>Kurz probíhá ve dvě soboty (17. ledna a 21. března 2026) a ve čtyři úterní večery (27. ledna, 10. a 24. února a 14. dubna 2026) v komunitě Emmanuel v Brně.</p>",
    registrationDeadline: "2026-01-09",
    poster: {
      src: `${UPLOADS}/kurz-mission-possible-2026-plakat-1.webp`,
      alt: "Plakát: Mission Possible, kurz dialogu a misie",
    },
    attachments: [
      { label: "Plakát, 1. část", file: `${UPLOADS}/kurz-mission-possible-2026-plakat-1.jpg`, size: 885953 },
      { label: "Plakát, 2. část", file: `${UPLOADS}/kurz-mission-possible-2026-plakat-2.jpg`, size: 705064 },
    ],
    links: [{ label: "Přihláška na kurz", href: "https://www.emmanuel.cz/MP" }],
    sessions: 6,
  },
  {
    id: "obnova-pro-manzele-2026",
    title: "Obnova pro manžele",
    start: "2026-01-24",
    end: "2026-03-21",
    place: "Kuřim, fara",
    text: "Tři sobotní setkání pro manžele: povzbuzení, sdílení zkušeností, oživení a nová naděje.",
    body: "<p>Setkání obsahují společné chvály, přednášky, adoraci, vzájemné sdílení a mši svatou. Termíny: 24. ledna, 28. února a 21. března 2026. Pořádá farnost Kuřim s komunitou Emmanuel.</p>",
    poster: {
      src: `${UPLOADS}/obnova-pro-manzele-2026-plakat.webp`,
      alt: "Plakát: Obnova pro manžele na faře v Kuřimi",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/obnova-pro-manzele-2026-plakat.pdf`, size: 263447 }],
    links: [
      { label: "laskaapravdakurim@seznam.cz", href: "mailto:laskaapravdakurim@seznam.cz" },
      { label: "Komunita Emmanuel", href: "https://www.emmanuel.cz/" },
    ],
    sessions: 3,
  },
  {
    id: "laska-a-pravda-2026",
    title: "Láska a pravda",
    start: "2026-01-24",
    end: "2026-03-21",
    place: "Kuřim, fara",
    mapQuery: "Křížkovského 55/5, Kuřim",
    text: "Osvětově-vzdělávací program pro život manželů v lásce a pravdě: cyklus tří sobotních celodenních seminářů.",
    body: "<p>Semináře se konají <strong>24. ledna</strong>, <strong>28. února</strong> a <strong>21. března</strong> na faře v Kuřimi (Křížkovského 55/5). Lektoruje tým Komunity Emmanuel.</p>",
    poster: { src: `${UPLOADS}/laska-a-pravda-2026-plakat.webp`, alt: "Plakát: Láska a pravda, program pro manžele" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/laska-a-pravda-2026-plakat.png`, size: 270672 }],
    links: [{ label: "Program Láska a pravda", href: "https://www.emmanuel.cz/manzele/" }],
    sessions: 3,
  },
  {
    id: "prvopatecni-setkani-2026",
    title: "Prvopáteční setkání",
    start: "2026-02-06",
    time: "19:00",
    place: "Brno, kostel sv. Tomáše, nebo Kuřim, kostel sv. Maří Magdalény",
    mapQuery: "kostel sv. Tomáše, Brno",
    text: "Prvopáteční setkání s tématem uzdravení: čas v adoraci, chvále i tichu.",
    body:
      "<p>Setkání se koná v pátek 6. února od 19:00 v Brně u sv. Tomáše, nebo v Kuřimi v kostele sv. Maří Magdalény. Program z Brna můžete sledovat také online.</p>" +
      "<p>Další setkání probíhají v Batelově v kostele sv. Petra a Pavla ve čtvrtek 5. 2., 5. 3., 2. 4., 7. 5. a 4. 6. od 19:30.</p>",
    poster: { src: `${UPLOADS}/prvopatecni-setkani-2026-plakat.webp`, alt: "Plakát: Prvopáteční setkání 6. 2. 2026" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/prvopatecni-setkani-2026-plakat.pdf`, size: 100188 }],
    links: [{ label: "Přenosy z kostela sv. Tomáše", href: "https://prenosy.svtomas.net/" }],
  },
  {
    id: "seminar-otcovo-srdce-2026",
    title: "Seminář Otcovo srdce",
    start: "2026-03-05",
    end: "2026-11-10",
    text: "Seminář, který vám pomůže objevit lásku a dobrotu Nebeského Otce i vaši identitu Božího syna či dcery.",
    body:
      "<p>Program zahrnuje vyučování, osobní svědectví a modlitby za uzdravení srdce. Seminář je otevřený pro všechny církevní denominace a doprovází ho český tým Otcova srdce; dva semináře vedou manželé de Hoxar z Velké Británie.</p>" +
      "<p>Termíny 2026: 5.–10. 3. Štěkeň, 9.–14. 4. Vranov u Brna, 14.–19. 5. Tuchoměřice, 25.–30. 6. Vranov u Brna (manželé de Hoxar), 3.–8. 8. Klatovy, 15.–20. 10. Vranov u Brna, 5.–10. 11. Želiv (manželé de Hoxar).</p>",
    poster: {
      src: `${UPLOADS}/seminar-otcovo-srdce-2026-letak.webp`,
      alt: "Leták: Seminář Otcovo srdce, termíny 2026",
    },
    attachments: [{ label: "Leták", file: `${UPLOADS}/seminar-otcovo-srdce-2026-letak.pdf`, size: 11009562 }],
    links: [{ label: "Otcovo srdce", href: "https://www.otcovosrdce.cz/" }],
    longTerm: true,
  },
  {
    id: "kurz-vedoucich-ministrantu-2026-03-06",
    title: "Kurz vedoucích ministrantů ve farnostech",
    start: "2026-03-06",
    end: "2026-03-08",
    place: "Osová Bítýška, centrum MAMRE",
    text: "Víkendový kurz pro současné i budoucí vedoucí ministrantů a ministrantek od 12 let.",
    body: "<p>Cena kurzu zahrnuje materiály i občerstvení po celou dobu trvání.</p>",
    price: "501 Kč",
    poster: {
      src: `${UPLOADS}/kurz-vedoucich-ministrantu-2026-03-06-plakat.webp`,
      alt: "Plakát: Kurz vedoucích ministrantů ve farnostech 6.–8. března 2026",
    },
    attachments: [
      { label: "Plakát", file: `${UPLOADS}/kurz-vedoucich-ministrantu-2026-03-06-plakat.jpg`, size: 318492 },
    ],
  },
  {
    id: "seminar-pro-katechety-2026",
    title: "Seminář pro katechety a lektory Vstupů do škol",
    start: "2026-03-12",
    time: "17:00",
    place: "Tišnov, fara",
    text: "Seminář na téma „Mučedníci totality“ P. Jan Bula a P. Václav Drbola. Otevřen je všem zájemcům.",
    body: "<p>Setkání s podtitulem „Věrnost pravdě, síla lásky a moc odpuštění“ povede lektorka Mgr. Veronika Chabičovská.</p>",
    poster: {
      src: `${UPLOADS}/seminar-pro-katechety-2026-pozvanka.webp`,
      alt: "Pozvánka: Seminář pro katechety a lektory Vstupů do škol 12. 3. 2026",
    },
    attachments: [{ label: "Pozvánka", file: `${UPLOADS}/seminar-pro-katechety-2026-pozvanka.png`, size: 992256 }],
  },
  {
    id: "petrklic-2026-1",
    title: "Petrklíč 1/2026",
    start: "2026-03-26",
    text: "Právě vyšlo nové vydání farního zpravodaje Petrklíč.",
    attachments: [{ label: "Petrklíč 1/2026", file: "/uploads/petrklic/2026-1/petrklic-2026-1.pdf", size: 22906328 }],
  },
  {
    id: "velikonoce-v-altottingu-2026",
    title: "Velikonoce v Altöttingu",
    start: "2026-04-02",
    end: "2026-04-06",
    place: "Altötting, Německo",
    text: "Velikonoční setkání pro mladé v německém poutním místě: společné prožití největších křesťanských svátků.",
    poster: {
      src: `${UPLOADS}/velikonoce-v-altottingu-2026-plakat.webp`,
      alt: "Plakát: Velikonoce v Altöttingu 2.–6. 4. 2026",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/velikonoce-v-altottingu-2026-plakat.png`, size: 1747956 }],
    links: [{ label: "Velikonoce v Altöttingu", href: "https://mladi.emmanuel.cz/velikonoce/" }],
  },
  {
    id: "radostna-pout-na-vranov-2026",
    title: "Radostná pouť s Pannou Marií na Vranov",
    start: "2026-04-11",
    time: "11:30",
    place: "Kuřim, Lelekovice a Vranov u Brna",
    text: "Pouť s obědem v Kuřimi nebo společným putováním z Lelekovic, zakončená mší svatou na Vranově.",
    body: "<p>Trasa z Lelekovic měří 5 km, je vhodná i pro kočárky a pouť se koná za každého počasí.</p>",
    program: [
      { time: "11:30", title: "Oběd v Kuřimi" },
      { time: "13:30", title: "Putování z Lelekovic", note: "od kostela" },
      { time: "16:00", title: "Mše svatá", note: "kostel Narození Panny Marie na Vranově (přibližně)" },
    ],
    poster: {
      src: `${UPLOADS}/radostna-pout-na-vranov-2026-plakat.webp`,
      alt: "Plakát: Radostná pouť s Pannou Marií na Vranov 11. dubna 2026",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/radostna-pout-na-vranov-2026-plakat.jpg`, size: 519588 }],
  },
  {
    id: "kurz-evangelizace-2026",
    title: "Kurz evangelizace",
    start: "2026-04-18",
    end: "2026-05-23",
    text: "Kurz brněnské diecéze o tom, jak sdílet a předávat svou víru: vyučování, modlitba chval, skupinky a svědectví.",
    body: "<p>Setkání se konají v sobotu 18. 4., 25. 4. a 9. 5. a o víkendu 22.–23. 5. Témata: Pojď a uvidíš; Proč církev nemůže mlčet; Z Galileje až na konec země; Jděte a hlásejte!</p>",
    registrationDeadline: "2026-04-02",
    poster: {
      src: `${UPLOADS}/kurz-evangelizace-2026-plakat.webp`,
      alt: "Plakát: Kurz evangelizace brněnské diecéze 2026",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/kurz-evangelizace-2026-plakat.jpg`, size: 56345 }],
    links: [{ label: "Biskupství brněnské", href: "https://www.biskupstvi.cz/" }],
    sessions: 4,
  },
  {
    id: "setkani-katechetu-2026",
    title: "Setkání katechetů",
    start: "2026-04-28",
    time: "18:00",
    place: "Tišnov, fara",
    text: "Setkání katechetů tišnovského děkanství se vzájemným sdílením a za účasti pracovníků Diecézního katechetického centra.",
    poster: {
      src: `${UPLOADS}/setkani-katechetu-2026-plakat.webp`,
      alt: "Plakát: Setkání katechetů tišnovského děkanství 28. dubna 2026",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/setkani-katechetu-2026-plakat.png`, size: 3867086 }],
  },
  {
    id: "setkani-akolytu-2026",
    title: "Děkanátní setkání akolytů",
    start: "2026-05-12",
    time: "18:00",
    place: "Tišnov, kostel sv. Václava",
    text: "Setkání akolytů tišnovského děkanství na téma Návštěvy nemocných. Provede lektor P. Josef Rybecký.",
    poster: {
      src: `${UPLOADS}/setkani-akolytu-2026-plakat.webp`,
      alt: "Plakát: Děkanátní setkání akolytů 12. května 2026",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/setkani-akolytu-2026-plakat.png`, size: 801149 }],
  },
  {
    id: "den-rodin-2026",
    title: "Den rodin",
    start: "2026-05-17",
    time: "14:00",
    place: "Kuřim, areál ZŠ Komenského",
    text: "Odpoledne pro celé rodiny s hudbou, divadlem, skákacími hrady a workshopy. Vstup dobrovolný.",
    body: "<p>Těšit se můžete také na malování na obličej, taneční aktivity a klauna. Občerstvení je zajištěno.</p>",
    program: [
      { time: "14:00", title: "Zahájení" },
      { time: "14:15", title: "Vystoupení kapely Manévr" },
      { time: "15:00", title: "Dětský folklórní kroužek Floriánek" },
      { time: "15:30", title: "Divadlo Jaromír" },
      { time: "17:00", title: "Vystoupení kapely Manévr" },
      { time: "18:30", title: "Taneční vystoupení Lumiku" },
    ],
    poster: { src: `${UPLOADS}/den-rodin-2026-plakat.webp`, alt: "Plakát: Den rodin 17. 5. 2026" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/den-rodin-2026-plakat.png`, size: 678359 }],
  },
  {
    id: "charitni-pout-predklasteri-2026",
    title: "Charitní pouť do Předklášteří",
    start: "2026-05-23",
    time: "8:45",
    place: "Předklášteří, klášter Porta coeli",
    text: "Charitní pouť s otcem biskupem Pavlem Konzbulem z Tišnova do kláštera Porta coeli. Pořádá Diecézní charita Brno.",
    program: [
      { time: "8:45", title: "Sraz", note: "parkoviště Na Loukách u nádraží v Tišnově" },
      { time: "9:00–10:30", title: "Putování do Porta coeli" },
      { time: "10:30–11:00", title: "Svátost smíření", note: "bazilika Nanebevzetí Panny Marie" },
      { time: "11:00–12:00", title: "Mše svatá s otcem biskupem" },
      { time: "od 12:00", title: "Oběd, aktivity pro děti i dospělé" },
    ],
    poster: {
      src: `${UPLOADS}/charitni-pout-predklasteri-2026-plakat.webp`,
      alt: "Plakát: Charitní pouť do Předklášteří 23. 5. 2026",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/charitni-pout-predklasteri-2026-plakat.png`, size: 2205536 }],
    links: [{ label: "Diecézní charita Brno", href: "https://www.dchb.charita.cz/" }],
  },
  {
    id: "veni-creator-spiritus-2026",
    title: "Veni, Creator Spiritus",
    start: "2026-05-24",
    time: "8:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "O Slavnosti Seslání Ducha Svatého zazní při mši svaté hymnus Veni, Creator Spiritus od Pála Esterházyho.",
    body: "<p>Sólový zpěv: <strong>Anna Keprtová</strong>, varhanní doprovod: <strong>Jan Čáp</strong>.</p>",
    poster: {
      src: `${UPLOADS}/veni-creator-spiritus-2026-plakat.webp`,
      alt: "Plakát: Veni, Creator Spiritus o Slavnosti Seslání Ducha Svatého",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/veni-creator-spiritus-2026-plakat.jpg`, size: 267395 }],
  },
  {
    id: "ctyri-violoncella-2026",
    title: "Čtyři violoncella, posvátné hlasy",
    start: "2026-05-24",
    time: "17:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Koncert duchovní hudby kvarteta brněnských filharmoniků Solitutticelli Brno Cello Quartet.",
    body: "<p>Účinkují Michal Greco, Katarína Madariová, Martina Klimešová a Rudolf Mrazík.</p>",
    price: "dobrovolné vstupné",
    poster: {
      src: `${UPLOADS}/ctyri-violoncella-2026-plakat.webp`,
      alt: "Plakát: Cellos Sacred Voices, Solitutticelli Brno Cello Quartet",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/ctyri-violoncella-2026-plakat.jpg`, size: 260115 }],
  },
  {
    id: "noc-kostelu-2026",
    title: "Noc kostelů: Schola Gregoriana Pragensis",
    start: "2026-05-29",
    time: "19:30",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "V rámci Noci kostelů zazpívá soubor Schola Gregoriana Pragensis gregoriánský chorál.",
    price: "dobrovolné vstupné",
    poster: {
      src: `${UPLOADS}/noc-kostelu-2026-plakat.webp`,
      alt: "Plakát: Schola Gregoriana Pragensis v Kuřimi 29. 5. 2026",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/noc-kostelu-2026-plakat.jpg`, size: 482147 }],
  },
  {
    id: "farni-den-2026",
    title: "Farní den k výročí 800 let",
    start: "2026-06-13",
    time: "14:00",
    place: "Kuřim, fara",
    mapQuery: "Křížkovského 55/5, Kuřim",
    text: "Farní den k výročí 800 let Kuřimi: mše svatá venku, diskuse s pamětníky, workshopy a táborák.",
    body: "<p>Od 15:30 do 17:00 probíhají workshopy (hudební, výtvarný, sportovní, retrohry), od 15:00 do 18:00 je otevřen stánek čajovny s možností rozhovoru a sdílení. Pro děti a rodiny je připraven odpolední katechetický program.</p>",
    program: [
      { time: "14:00", title: "Mše svatá venku" },
      { time: "14:45", title: "Zahájení programu" },
      { time: "15:00", title: "Moderovaná diskuse s pamětníky z farnosti" },
      { time: "15:45", title: "Špeky z farní kroniky", note: "Adam Janík" },
      { time: "16:15", title: "Povídání o historii fary a kostela", note: "p. Laurincová" },
      { time: "16:45", title: "Prezentace výstupů workshopů" },
      { time: "od 17:00", title: "Táborák s hudebním doprovodem" },
    ],
    poster: { src: `${UPLOADS}/farni-den-2026-plakat.webp`, alt: "Plakát: Farní den 13. června 2026, výročí 800 let" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/farni-den-2026-plakat.jpg`, size: 205047 }],
  },
  {
    id: "slavnostni-mse-800-let-kurimi-2026",
    title: "Slavnostní mše k 800 letům Kuřimi",
    start: "2026-06-28",
    time: "9:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Slavnostní mše svatá k výročí 800 let od první zmínky o Kuřimi, výjimečně v 9:00. Mše se nakonec přesunula z náměstí do kostela.",
    program: [
      { time: "9:00", title: "Mše svatá", note: "zpívá kuřimská dětská schola" },
      { time: "10:15", title: "Divadlo" },
      { time: "11:30", title: "Vystoupení Pavla Helana" },
    ],
  },
  {
    id: "malhostovska-pout-2026",
    title: "Malhostovská pouť",
    start: "2026-06-28",
    time: "14:00",
    place: "Malhostovice, kostel sv. Vavřince",
    text: "Slavnostní mší poděkujeme za 45 let obětavé kněžské služby pana faráře Pavla Kopeckého.",
    body: "<p>Od 15 hodin je sousedské posezení před kostelem s drobným občerstvením.</p>",
    poster: { src: `${UPLOADS}/malhostovska-pout-2026-plakat.webp`, alt: "Plakát: Malhostovská pouť 28. 6. 2026" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/malhostovska-pout-2026-plakat.png`, size: 133455 }],
  },
  {
    id: "hody-jinacovice-2026",
    title: "Krojované hody v Jinačovicích",
    start: "2026-07-24",
    end: "2026-07-26",
    place: "Jinačovice, sokolské hřiště",
    text: "TJ Sokol Jinačovice, obec a stárci zvou na Mladé hody a Den obce Jinačovice.",
    body: "<p>Vstup ve společenském oblečení.</p>",
    program: [
      { time: "pá 18:00", title: "Stavění a hlídání máje" },
      { time: "so 19:00", title: "Hodová zábava s DH Šardičanka", note: "vstupné 200 Kč" },
      { time: "ne 11:00", title: "Slavnostní hodová mše svatá" },
      { time: "ne 14:00", title: "Den obce s CM Primáš z Boleradic" },
    ],
    poster: {
      src: `${UPLOADS}/hody-jinacovice-2026-plakat.webp`,
      alt: "Plakát: Krojované hody v Jinačovicích 24.–26. července 2026",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/hody-jinacovice-2026-plakat.jpg`, size: 5950526 }],
  },
  {
    id: "paray-le-monial-2026",
    title: "Paray-le-Monial s komunitou Emmanuel",
    start: "2026-07-26",
    end: "2026-07-31",
    place: "Paray-le-Monial, Francie",
    text: "Mezinárodní duchovní program s komunitou Emmanuel s mottem „Nebojte se… stát se mými učedníky!“.",
    body: "<p>Čeká vás čas naplněný chválami, radostnou liturgií, vyučováním i ztišením u Ježíšova Srdce a prostor pro sdílení s ostatními.</p>",
    registrationDeadline: "2026-04-20",
    poster: {
      src: `${UPLOADS}/paray-le-monial-2026-plakat.webp`,
      alt: "Plakát: Nebojte se… stát se mými učedníky! Paray-le-Monial 2026",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/paray-le-monial-2026-plakat.pdf`, size: 2323426 }],
    links: [{ label: "Informace a přihláška", href: "https://www.emmanuel.cz/nebojte-se/" }],
  },
  {
    id: "promena-farnosti-2026",
    title: "Proměna farnosti s Patrikem Páleníkem z Tchaj-wanu",
    start: "2026-08-03",
    time: "9:30",
    place: "Brno, Petrov",
    mapQuery: "Petrov 2, Brno",
    text: "Inspirující setkání o proměně farnosti s misionářem Patrikem Páleníkem.",
    program: [
      { time: "9:30", title: "Setkání s kněžími z diecéze a absolventy Kickstartu" },
      { time: "13:00", title: "Diskuse a kafe s absolventy Kickstartu" },
      { time: "17:00", title: "Setkání s laiky a členy leadership týmů" },
    ],
    poster: {
      src: `${UPLOADS}/promena-farnosti-2026-pozvanka.webp`,
      alt: "Pozvánka: Proměna farnosti s Patrikem Páleníkem z Tchaj-wanu",
    },
    attachments: [{ label: "Pozvánka", file: `${UPLOADS}/promena-farnosti-2026-pozvanka.jpg`, size: 306063 }],
  },
  {
    id: "farni-tabor-2026",
    title: "Farní tábor 2026",
    start: "2026-08-08",
    end: "2026-08-15",
    text: "Letní farní tábor pro děti.",
  },
  {
    id: "celostatni-setkani-mladeze-2026",
    title: "Celostátní setkání mládeže Ostrava 2026",
    start: "2026-08-11",
    end: "2026-08-16",
    place: "Ostrava",
    text: "Celostátní setkání mládeže s tématem „Odvahu! Já jsem přemohl svět“ (Jan 16,33).",
    poster: {
      src: `${UPLOADS}/celostatni-setkani-mladeze-2026-plakat.webp`,
      alt: "Plakát: Celostátní setkání mládeže Ostrava 11.–16. 8. 2026",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/celostatni-setkani-mladeze-2026-plakat.pdf`, size: 782250 }],
    links: [{ label: "@csm_ostrava na Instagramu", href: "https://www.instagram.com/csm_ostrava/" }],
  },
  {
    id: "vranovska-pout-2026",
    title: "8. výroční Vranovská pouť",
    start: "2026-08-30",
    time: "7:00",
    place: "Česká, Lelekovice a Vranov u Brna",
    text: "Pouť Sedmiradostnou cestou z České a Lelekovic na Vranov, zakončená mší svatou.",
    body: "<p>Po mši svaté je připraveno občerstvení na farní zahradě.</p>",
    program: [
      { time: "7:00", title: "Sraz poutníků v České", note: "u kapličky" },
      { time: "7:45", title: "Sraz poutníků v Lelekovicích", note: "u kostela sv. Filipa a Jakuba" },
      { time: "11:00", title: "Mše svatá", note: "kostel Narození Panny Marie ve Vranově u Brna" },
    ],
    poster: {
      src: `${UPLOADS}/vranovska-pout-2026-plakat.webp`,
      alt: "Plakát: 8. výroční Vranovská pouť Sedmiradostnou cestou 30. srpna 2026",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/vranovska-pout-2026-plakat.jpg`, size: 762346 }],
    links: [{ label: "Sedmiradostná cesta", href: "https://www.sedmiradostnacesta.com/" }],
  },
  {
    id: "kurz-vedoucich-ministrantu-2026-09-12",
    title: "Kurz vedoucích ministrantů",
    start: "2026-09-12",
    time: "18:00–20:00",
    place: "Tišnov, fara",
    text: "Kurz pro vedoucí ministrantů a ministrantek z tišnovského děkanství.",
    body: "<p>Program zahrnuje vedení skupiny, liturgii, organizaci schůzek a praktické tipy z praxe. Občerstvení a materiály jsou zajištěny.</p>",
    price: "zdarma",
    poster: {
      src: `${UPLOADS}/kurz-vedoucich-ministrantu-2026-09-12-pozvanka.webp`,
      alt: "Pozvánka: Kurz vedoucích ministrantů 12. 9. 2026",
    },
    attachments: [
      { label: "Pozvánka", file: `${UPLOADS}/kurz-vedoucich-ministrantu-2026-09-12-pozvanka.jpg`, size: 219900 },
    ],
  },
  {
    id: "vystava-pozvedam-sve-oci-2026",
    title: "Pozvedám své oči k Tobě – výstava obrazů",
    start: "2026-09-13",
    time: "14:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Výstava obrazů Kamily Veroniky Planerové Pozvedám své oči k Tobě.",
    poster: {
      src: `${UPLOADS}/vystava-pozvedam-sve-oci-2026-plakat.webp`,
      alt: "Plakát: výstava obrazů Kamily Veroniky Planerové Pozvedám své oči k Tobě",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/vystava-pozvedam-sve-oci-2026-plakat.pdf`, size: 27544297 }],
  },
  {
    id: "den-narodnostnich-mensin-2026",
    title: "Den národnostních menšin",
    start: "2026-09-13",
    time: "13:00",
    place: "Kuřim, zámek",
    text: "Město Kuřim a Společenské a kulturní centrum Kuřim zvou na Den národnostních menšin.",
    body: "<p>Součástí programu je také výstava obrazů v kostele sv. Maří Magdalény.</p>",
    poster: {
      src: `${UPLOADS}/den-narodnostnich-mensin-2026-plakat.webp`,
      alt: "Plakát: Den národnostních menšin 13. 9. 2026",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/den-narodnostnich-mensin-2026-plakat.jpg`, size: 10451263 }],
  },
  {
    id: "mse-s-pozehnanim-namesti-2026",
    title: "Mše svatá s požehnáním nového náměstí",
    start: "2026-09-20",
    time: "9:00",
    place: "Kuřim, náměstí Osvobození",
    text: "Mše svatá s požehnáním nově opraveného náměstí a farní kroniky za doprovodu dětské farní scholy.",
    body: "<p>Slavnost se koná při příležitosti oslav 800 let od první písemné zmínky o Kuřimi.</p>",
    poster: {
      src: `${UPLOADS}/mse-s-pozehnanim-namesti-2026-plakat.webp`,
      alt: "Plakát: Mše svatá s požehnáním nového náměstí 20. září 2026",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/mse-s-pozehnanim-namesti-2026-plakat.pdf`, size: 2143021 }],
  },
  {
    id: "pesi-pout-na-vranov-2026",
    title: "Pěší pouť kuřimské farnosti na Vranov",
    start: "2026-09-27",
    time: "7:00",
    place: "Moravské Knínice, Kuřim a Vranov u Brna",
    text: "Tradiční pěší pouť z Moravských Knínic přes Kuřim na Vranov s krojovaným procesím.",
    program: [
      { time: "7:00", title: "Start z Moravských Knínic" },
      { time: "7:20", title: "Požehnání poutníkům", note: "u kostela v Kuřimi" },
      { time: "11:00", title: "Krojované procesí a mše svatá na Vranově" },
    ],
    poster: {
      src: `${UPLOADS}/pesi-pout-na-vranov-2026-plakat.webp`,
      alt: "Plakát: Pěší pouť kuřimské farnosti na Vranov 27. září 2026",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/pesi-pout-na-vranov-2026-plakat.pdf`, size: 594521 }],
  },
  {
    id: "setkani-prvokomunikantu-2026",
    title: "Setkání prvokomunikantů s biskupem Pavlem",
    start: "2026-10-01",
    time: "9:00–14:30",
    place: "Brno, Petrov",
    text: "Setkání prvokomunikantů s otcem biskupem Pavlem na Petrově v Brně s mottem „Dám vám nové srdce“.",
    program: [
      { time: "9:00", title: "Příchod na Petrov" },
      { time: "10:00", title: "Mše svatá" },
      { time: "11:00–13:50", title: "Stanoviště a hry", note: "vlastní svačina" },
      { time: "14:00–14:30", title: "Adorace a ukončení" },
    ],
    poster: {
      src: `${UPLOADS}/setkani-prvokomunikantu-2026-plakat.webp`,
      alt: "Plakát: Setkání prvokomunikantů s biskupem Pavlem 1. 10. 2026",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/setkani-prvokomunikantu-2026-plakat.png`, size: 1843554 }],
  },
  {
    id: "obnova-v-duchu-svatem-2026",
    title: "Obnova v Duchu svatém",
    start: "2026-10-01",
    end: "2027-04-29",
    place: "Brno, Lidická",
    text: "Seminář obnovy v Duchu svatém s Komunitou Emmanuel: každý čtvrtek přednášky, adorace a modlitba.",
    attachments: [{ label: "Pozvánka", file: `${UPLOADS}/obnova-v-duchu-svatem-2026-pozvanka.png`, size: 217722 }],
    links: [{ label: "Obnova v Duchu svatém", href: "https://www.emmanuel.cz/obnova/" }],
    longTerm: { weeklyAt: "18:30" },
  },
  {
    id: "hody-ceska-2026",
    title: "Hody v České",
    start: "2026-10-02",
    end: "2026-10-04",
    place: "Česká",
    text: "Srdečně zveme na tradiční hody v České: stavění máje, průvod obcí, česká beseda, hodová zábava a hodová mše svatá.",
    program: [
      { time: "pá 16:00", title: "Stavění máje stárky a hodovou chasou" },
      { time: "pá 17:00", title: "Posezení pod májou", note: "s HCM Kubíci a Staňou Rosypalem" },
      { time: "so 9:00", title: "Zvaní na hody" },
      {
        time: "so 15:00",
        title: "Průvod obcí od sokolovny",
        note: "předání hodového práva, svěcení práva a vína u kapličky",
      },
      { time: "so 18:00", title: "Česká beseda pod májou" },
      { time: "so 20:00", title: "Hodová zábava s DH Blučiňáci", note: "vstupné 200 Kč, krojovaní zdarma" },
      {
        time: "ne 11:00",
        title: "Mše svatá v kostele sv. Maří Magdalény v Kuřimi",
        note: "zpívá chrámový sbor Magnificat, autobus v 10:30 z návsi",
      },
      { time: "ne 18:00", title: "Hodové dozvuky s CM Primáš", note: "dobrovolné vstupné" },
    ],
    poster: { src: `${UPLOADS}/hody-ceska-2026-plakat.webp`, alt: "Plakát: Hody v České 2.–4. října 2026" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/hody-ceska-2026-plakat.png`, size: 482268 }],
  },
  {
    id: "novy-web-farnosti",
    title: "Nový web farnosti",
    start: "2026-10-05",
    end: "2026-10-31",
    text: "Farní web dostal novou podobu. Některé méně navštěvované stránky ještě připravujeme.",
    lead: "Vítejte na novém webu farnosti Kuřim.",
    body:
      "<p>Farní web prošel úplnou proměnou: nový vzhled, přehlednější aktuality, pořad bohoslužeb, kalendář a fotogalerie a pohodlné čtení na mobilu.</p>" +
      "<p>Některé vedlejší stránky ještě připravujeme a budeme je postupně doplňovat. Do té doby najdete jejich obsah na původním webu.</p>",
    links: [{ label: "Původní web farnosti", href: "https://stary.farakurim.cz/" }],
  },
  {
    id: "kolac-pro-hospic-2026",
    title: "Koláč pro hospic",
    start: "2026-10-07",
    place: "Kuřim, Tišnov a Veverská Bítýška",
    text: "Podpořte svým darem Domácí hospic Porta Vitae a za příspěvek dostanete chutný koláč.",
    body:
      "<p>Domácí hospic Porta Vitae poskytuje na Tišnovsku a Kuřimsku péči nevyléčitelně nemocným a umírajícím. Přispět je možné i online.</p>" +
      "<ul><li><strong>Kuřim</strong> – před prodejnou Kaufland, 7:00–15:00</li><li><strong>Tišnov</strong> – před prodejnou Albert, 7:00–16:00, a v Domácím hospici Porta Vitae, 8:00–15:00</li><li><strong>Veverská Bítýška</strong> – nám. Na Městečku, 9:00–12:00</li></ul>",
    poster: { src: `${UPLOADS}/kolac-pro-hospic-2026-plakat.webp`, alt: "Plakát: Koláč pro hospic 7. 10. 2026" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/kolac-pro-hospic-2026-plakat.png`, size: 3418665 }],
    links: [{ label: "Koláč pro hospic", href: "https://tisnov.charita.cz/kolac-pro-hospic" }],
  },
  {
    id: "setkani-lektoru-2026",
    title: "Děkanátní setkání lektorů Božího slova",
    start: "2026-10-09",
    end: "2026-10-10",
    place: "Tišnov, kostel sv. Václava",
    text: "Formační setkání lektorů Božího slova tišnovského děkanství. Provází MgA. Martina Pavlíková.",
    program: [
      { time: "pá 18:00", title: "Mše svatá" },
      { time: "pá 19:00–20:30", title: "I. formační setkání" },
      { time: "so 9:00–12:00", title: "II. formační setkání", note: "praktické čtení v kostele" },
    ],
    poster: {
      src: `${UPLOADS}/setkani-lektoru-2026-pozvanka.webp`,
      alt: "Pozvánka: Děkanátní setkání lektorů Božího slova 9.–10. 10. 2026",
    },
    attachments: [{ label: "Pozvánka", file: `${UPLOADS}/setkani-lektoru-2026-pozvanka.png`, size: 1807834 }],
  },
  {
    id: "manzelske-vecery-2026",
    title: "Manželské večery pro Tišnov a okolí",
    start: "2026-10-11",
    end: "2026-11-22",
    time: "18:00–20:30",
    place: "Tišnov, děkanství",
    text: "Sedm nedělních setkání pro posílení vašeho vztahu.",
    body: "<p>Přihlášky se otevřely 1. 6. 2026 v 8:00 přes web nebo QR kód na plakátu. Kontakt: M. Lavičková, tel. 733 741 739.</p>",
    poster: { src: `${UPLOADS}/manzelske-vecery-2026-plakat.webp`, alt: "Plakát: Manželské večery pro Tišnov a okolí" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/manzelske-vecery-2026-plakat.pdf`, size: 461974 }],
    links: [{ label: "Přihláška", href: "https://bit.ly/randeprovsechny" }],
    sessions: 7,
  },
  {
    id: "setkani-varhaniku-a-schol-2026",
    title: "Děkanátní setkání varhaníků a schol",
    start: "2026-10-17",
    time: "9:30–11:30",
    place: "Tišnov, fara",
    text: "Setkání varhaníků a schol tišnovského děkanství na téma Jak prožívat mši svatou jako služebník při mši.",
    body: "<p>Setkání se koná v novém farním sále na faře v Tišnově. Lektorem je P. Mgr. Marcel Javora. Drobné občerstvení je zajištěno, přihlásit se můžete přes QR kód na plakátu.</p>",
    price: "zdarma",
    poster: {
      src: `${UPLOADS}/setkani-varhaniku-a-schol-2026-plakat.webp`,
      alt: "Plakát: Děkanátní setkání varhaníků a schol 17. 10. 2026",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/setkani-varhaniku-a-schol-2026-plakat.png`, size: 1455515 }],
  },
  {
    id: "jubileum-800-2026",
    title: "Slavnostní mše k jubileu 800 let",
    start: "2026-10-18",
    time: "9:30",
    place: "Kuřim, kostel sv. Maří Magdalény",
    mapQuery: "kostel sv. Maří Magdalény Kuřim",
    text: "Zveme vás na slavnostní mši k jubileu 800 let kostela sv. Maří Magdalény za doprovodu dětské scholy.",
    lead: "Kostel sv. Maří Magdalény stojí v Kuřimi od roku 1226. Oslavte s námi jeho 800. výročí.",
    body: "<p>Po mši jste všichni srdečně zváni do misijní kavárny na faře.</p>",
    program: [
      { time: "9:30", title: "Slavnostní mše svatá", note: "zpívá dětská schola" },
      { time: "po mši", title: "Misijní kavárna", note: "fara, Křížkovského 55/5" },
    ],
    highlights: {
      title: "800 let v datech",
      items: [
        { value: "1226", label: "založení kostela" },
        { value: "1772", label: "benedikce" },
        { value: "1889", label: "konsekrace" },
      ],
    },
    poster: {
      src: `${UPLOADS}/jubileum-800-2026-plakat.webp`,
      alt: "Plakát: Slavnostní mše k jubileu 800 let 18. října 2026",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/jubileum-800-2026-plakat.png`, size: 2245169 }],
    pinned: true,
  },
  {
    id: "hubertska-mse-2026",
    title: "Hubertská mše",
    start: "2026-10-25",
    time: "9:30",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Společnost Lesy města Brna, a. s., srdečně zve na Hubertskou mši.",
    poster: { src: `${UPLOADS}/hubertska-mse-2026-pozvanka.webp`, alt: "Pozvánka: Hubertská mše 25. 10. 2026" },
    attachments: [{ label: "Pozvánka", file: `${UPLOADS}/hubertska-mse-2026-pozvanka.pdf`, size: 2594721 }],
  },
  {
    id: "pokoj-srdce-2026",
    title: "Pokoj srdce – víkendové setkání pro mladé ženy",
    start: "2026-11-06",
    end: "2026-11-08",
    place: "Žernůvka u Tišnova",
    text: "Sestry františkánky pod ochranou Svaté rodiny zvou mladé ženy od 18 let na víkend s tématem Pokoj srdce… kde jej nacházím a kde ztrácím.",
    poster: {
      src: `${UPLOADS}/pokoj-srdce-2026-plakat.webp`,
      alt: "Plakát: Pokoj srdce, víkendové setkání pro mladé ženy",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/pokoj-srdce-2026-plakat.pdf`, size: 298911 }],
    links: [{ label: "frantiska@frantiskanky.cz", href: "mailto:frantiska@frantiskanky.cz" }],
  },
  {
    id: "konference-o-evangelizaci-2026",
    title: "Konference o evangelizaci – Riskujme lásce",
    start: "2026-11-13",
    end: "2026-11-14",
    place: "Olomouc",
    text: "Konference s přednáškami, kulatým stolem, duchovním programem a praktickými workshopy evangelizace.",
    body: "<p>Hlavním hostem je P. Patrick Gonyeau a Encounter Ministries (USA), dále mimo jiné P. Vojtěch Koukal, manželé Strežovi, P. Daniel Vícha, P. Libor Všetula, Pavel Vopalecký, sr. Dominika Konečná, Lámačské chvály a Gedeon worship.</p>",
    poster: {
      src: `${UPLOADS}/konference-o-evangelizaci-2026-plakat.webp`,
      alt: "Plakát: Konference o evangelizaci Riskujme lásce, Olomouc 13.–14. 11. 2026",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/konference-o-evangelizaci-2026-plakat.jpg`, size: 304654 }],
    links: [{ label: "evangelizace.cz", href: "https://evangelizace.cz/" }],
  },
  {
    id: "pout-lukov-trebic",
    title: "Farní pouť do Lukova a adventní Třebíče",
    start: "2026-12-19",
    place: "Lukov a Třebíč",
    text: "Pouť do Lukova u Moravských Budějovic, rodiště blahoslaveného Jana Buly, a na adventní trhy do Třebíče.",
    price: "300 Kč",
    registrationDeadline: "2026-10-10",
    poster: {
      src: `${UPLOADS}/pout-lukov-trebic-plakat.webp`,
      alt: "Plakát: Farní pouť do Lukova a adventní Třebíče 19. 12. 2026",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/pout-lukov-trebic-plakat.png`, size: 4393631 }],
    links: [{ label: "poutnicimkk@seznam.cz", href: "mailto:poutnicimkk@seznam.cz" }],
  },

  ...archivedEvents,
];
