import type { NewsEvent } from "./types";

// Mock content written from the live site's news and the Aktuality, Archiv and Detail mockups on 3. 10. 2026.
// Attachments without a known upload name use placeholder file names.

const UPLOADS = "https://farakurim.cz/nahrane/aktuality";

type ArchivedRow = [
  start: string,
  end: string,
  time: string,
  title: string,
  place: string,
  text: string,
  attachment?: [label: string, file: string],
];

/** Compact rows for the finished events of the archive mock. */
const archived = (rows: ArchivedRow[]): NewsEvent[] =>
  rows.map(([start, end, time, title, place, text, attachment], i) => ({
    id: `archiv-${i + 1}`,
    title,
    start,
    end: end || undefined,
    time: time || undefined,
    place,
    text,
    attachments: attachment && [{ label: attachment[0], file: `${UPLOADS}/${attachment[1]}` }],
  }));

export const events: NewsEvent[] = [
  {
    id: "jubileum-800",
    title: "Slavnostní mše k jubileu 800 let",
    start: "2026-10-18",
    time: "9:30",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Zveme vás na slavnostní mši k jubileu 800 let kostela sv. Maří Magdalény, založeného roku 1226. Po mši je připraveno pohoštění.",
    lead: "Kostel sv. Maří Magdalény stojí v Kuřimi od roku 1226. Oslavte s námi jeho 800. výročí.",
    body:
      "<p>Letos slavíme 800 let od založení našeho kostela sv. Maří Magdalény. Zveme vás na slavnostní mši svatou, při které poděkujeme za všechny generace, které se v kostele modlily.</p>" +
      "<p>Mši doprovodí zpěvem dětská schola. Po mši jste všichni srdečně zváni do misijní kavárny na faře.</p>",
    program: [
      { time: "9:30", title: "Slavnostní mše svatá", note: "zpívá dětská schola" },
      { time: "po mši", title: "Misijní kavárna", note: "fara, Křížkovského 55/5" },
    ],
    highlights: {
      title: "800 let v datech",
      items: [
        { value: "1226", label: "založení kostela" },
        { value: "1772", label: "benedikce" },
        { value: "1889", label: "konsekrace" },
      ],
    },
    mapQuery: "kostel sv. Maří Magdalény Kuřim",
    attachments: [{ label: "Plakát", file: `${UPLOADS}/6ab538eec7721.Plakát.png` }],
    pinned: true,
  },
  {
    id: "hody-ceska",
    title: "Hody v České",
    start: "2026-10-02",
    end: "2026-10-04",
    place: "Česká",
    text: "Srdečně zveme na tradiční hody v České – stavění máje, průvod a koncert.",
    attachments: [{ label: "Plakát", file: `${UPLOADS}/6abcdf48ca24c.Plakát.png` }],
  },
  {
    id: "kolac-pro-hospic",
    title: "Koláč pro hospic",
    start: "2026-10-07",
    place: "Kuřim a okolí",
    text: "Podpořte svým darem Domácí hospic Porta Vitae. Přispět můžete také online.",
    attachments: [{ label: "Plakát", file: `${UPLOADS}/6ab932eedf2ab.Plakát.png` }],
    links: [{ label: "Koláč pro hospic", href: "https://tisnov.charita.cz/kolac-pro-hospic" }],
  },
  {
    id: "setkani-lektoru",
    title: "Děkanátní setkání lektorů Božího slova",
    start: "2026-10-09",
    end: "2026-10-10",
    place: "Tišnov",
    text: "Setkání lektorů Božího slova tišnovského děkanství. Provází MgA. Martina Pavlíková.",
    attachments: [{ label: "Pozvánka", file: `${UPLOADS}/setkani-lektoru.Pozvánka.png` }],
  },
  {
    id: "manzelske-vecery",
    title: "Manželské večery pro Tišnov a okolí",
    start: "2026-10-11",
    end: "2026-11-22",
    time: "18:00–20:30",
    place: "Tišnov",
    text: "Sedm nedělních setkání pro posílení vašeho vztahu.",
    attachments: [{ label: "Plakát", file: `${UPLOADS}/manzelske-vecery.Plakát.pdf` }],
    sessions: 7,
  },
  {
    id: "hubertska-mse",
    title: "Hubertská mše",
    start: "2026-10-25",
    time: "9:30",
    place: "Kuřim",
    text: "Mši pořádají Lesy města Brna, a. s.",
    attachments: [{ label: "Pozvánka", file: `${UPLOADS}/hubertska-mse.Pozvánka.pdf` }],
  },
  {
    id: "pout-lukov-trebic",
    title: "Farní pouť do Lukova a adventní Třebíče",
    start: "2026-12-19",
    place: "Lukov a Třebíč",
    text: "Pouť do Lukova u Moravských Budějovic, rodiště blahoslaveného Jana Buly, a na adventní Třebíč. Cena 300 Kč.",
    attachments: [{ label: "Plakát", file: `${UPLOADS}/6ab933039e92d.Plakát.png` }],
    links: [{ label: "poutnicimkk@seznam.cz", href: "mailto:poutnicimkk@seznam.cz" }],
    price: "300 Kč",
    registrationDeadline: "2026-10-10",
  },
  {
    id: "obnova-v-duchu-svatem",
    title: "Obnova v Duchu svatém",
    start: "2026-10-01",
    end: "2027-04-29",
    place: "Brno, Lidická",
    text: "Seminář obnovy v Duchu svatém.",
    attachments: [{ label: "Pozvánka", file: `${UPLOADS}/6a40e5b1026d7.Pozvánka3.png` }],
    links: [{ label: "emmanuel.cz", href: "https://www.emmanuel.cz/obnova/" }],
    longTerm: { weeklyAt: "18:30" },
  },
  {
    id: "otcovo-srdce",
    title: "Seminář Otcovo srdce",
    start: "2026-03-01",
    end: "2026-11-30",
    place: "dle programu",
    text: "Seminář, který vám pomůže objevit lásku a dobrotu Nebeského Otce.",
    attachments: [{ label: "Informace", file: `${UPLOADS}/otcovo-srdce.Informace.pdf` }],
    longTerm: true,
  },
  {
    id: "prvokomunikanti",
    title: "Setkání prvokomunikantů s biskupem Pavlem",
    start: "2026-10-01",
    time: "9:00–14:30",
    place: "Brno, Petrov",
    text: "Setkání prvokomunikantů s otcem biskupem Pavlem na Petrově v Brně.",
    attachments: [{ label: "Plakát", file: `${UPLOADS}/6aa647e209023.Plakát.png` }],
  },
  {
    id: "medovy-den",
    title: "Stánek farnosti na Medovém dni",
    start: "2026-09-20",
    place: "Kuřim",
    text: "Děkujeme všem, kteří pomohli s farním stánkem.",
  },

  // Finished events for the archive (from the Archiv mockup).
  ...archived([
    [
      "2026-08-08",
      "2026-08-15",
      "",
      "Farní tábor 2026",
      "tábor pro děti z farnosti",
      "Letní tábor pro děti z farnosti.",
    ],
    [
      "2026-08-03",
      "",
      "9:30",
      "Proměna farnosti s Patrikem Páleníkem z Tchaj-wanu",
      "Brno, Petrov",
      "Setkání o proměně farnosti s misionářem z Tchaj-wanu.",
      ["Pozvánka", "promena-farnosti.Pozvánka.jpg"],
    ],
    [
      "2026-07-26",
      "2026-07-31",
      "",
      "Paray-le-Monial",
      "Paray-le-Monial, Francie",
      "Pouť a setkání rodin v Paray-le-Monial.",
      ["Plakát", "paray-le-monial.Plakát.pdf"],
    ],
    [
      "2026-07-24",
      "2026-07-26",
      "",
      "Krojované hody v Jinačovicích",
      "Jinačovice, sokolovna",
      "Tradiční krojované hody v Jinačovicích.",
      ["Plakát", "hody-jinacovice.Plakát.jpg"],
    ],
    [
      "2026-06-28",
      "",
      "9:00",
      "Slavnostní mše – 800 let Kuřimi",
      "Kuřim, kostel sv. Maří Magdalény",
      "Slavnostní mše k 800 letům Kuřimi.",
    ],
    [
      "2026-06-28",
      "",
      "",
      "Malhostovská pouť",
      "Malhostovice, kostel sv. Vavřince",
      "Pouť v Malhostovicích.",
      ["Plakát", "malhostovska-pout.Plakát.png"],
    ],
    [
      "2026-06-13",
      "",
      "14:00",
      "Farní den – výročí 800 let",
      "Kuřim",
      "Farní den k výročí 800 let.",
      ["Plakát", "farni-den.Plakát.jpeg"],
    ],
    [
      "2026-05-29",
      "",
      "19:30",
      "Noc kostelů",
      "Kuřim, kostel sv. Maří Magdalény",
      "Večerní program v otevřeném kostele.",
      ["Plakát", "noc-kostelu.Plakát.jpg"],
    ],
    [
      "2026-05-24",
      "",
      "17:00",
      "Čtyři violoncella, posvátné hlasy",
      "Kuřim, kostel sv. Maří Magdalény",
      "Koncert duchovní hudby.",
      ["Plakát", "ctyri-violoncella.Plakát.jpg"],
    ],
    [
      "2026-05-24",
      "",
      "8:00",
      "Veni, Creator Spiritus",
      "Kuřim, kostel sv. Maří Magdalény",
      "Slavnost Seslání Ducha svatého.",
      ["Plakát", "veni-creator.Plakát.jpg"],
    ],
    [
      "2026-05-23",
      "",
      "",
      "Charitní pouť v Předklášteří",
      "Předklášteří, Porta coeli",
      "Pouť charity do kláštera Porta coeli.",
      ["Informace", "charitni-pout.Informace.png"],
    ],
    [
      "2026-05-17",
      "",
      "14:00",
      "Den rodin",
      "Kuřim, areál ZŠ Komenského",
      "Odpoledne pro rodiny s dětmi.",
      ["Plakát", "den-rodin.Plakát.png"],
    ],
    [
      "2026-05-12",
      "",
      "18:00",
      "Děkanátní setkání akolytů",
      "Tišnov, kostel sv. Václava",
      "Setkání akolytů tišnovského děkanství.",
      ["Plakát", "setkani-akolytu.Plakát.png"],
    ],
    [
      "2026-04-28",
      "",
      "18:00",
      "Setkání katechetů",
      "Tišnov, fara",
      "Setkání katechetů děkanství.",
      ["Plakát", "setkani-katechetu.Plakát.png"],
    ],
    [
      "2026-04-11",
      "",
      "11:30",
      "Radostná pouť s Pannou Marií na Vranov",
      "Vranov u Brna",
      "Pouť na Vranov u Brna.",
      ["Plakát", "pout-vranov.Plakát.jpg"],
    ],
    [
      "2026-04-02",
      "2026-04-06",
      "",
      "Velikonoce v Altöttingu",
      "Altötting, Německo",
      "Velikonoční pouť do Altöttingu.",
      ["Plakát", "altotting.Plakát.png"],
    ],
    [
      "2026-03-26",
      "",
      "",
      "Nový Petrklíč",
      "zpravodaj farnosti",
      "Vyšlo nové číslo farního zpravodaje.",
      ["Petrklíč", "petrklic-jaro.Petrklíč.pdf"],
    ],
    [
      "2026-03-12",
      "",
      "17:00",
      "Seminář pro katechety a lektory",
      "Tišnov, fara",
      "Seminář pro katechety a lektory Božího slova.",
      ["Informace", "seminar-katechete.Informace.png"],
    ],
    [
      "2026-03-06",
      "2026-03-08",
      "",
      "Kurz vedoucích ministrantů",
      "Osová Bítýška, MAMRE",
      "Víkendový kurz pro vedoucí ministrantů.",
      ["Informace", "kurz-ministrantu.Informace.jpg"],
    ],
    [
      "2026-02-06",
      "",
      "19:00",
      "První pátek",
      "Brno, sv. Tomáš, nebo Kuřim",
      "Prvopáteční setkání.",
      ["Plakát", "prvni-patek.Plakát.pdf"],
    ],
    [
      "2026-01-13",
      "",
      "18:00",
      "Tříkrálový koncert",
      "Kuřim, kostel sv. Maří Magdalény",
      "Koncert k Tříkrálové sbírce.",
      ["Plakát", "trikralovy-koncert.Plakát.pdf"],
    ],
    [
      "2025-12-26",
      "",
      "16:00",
      "Vánoční zpívání ZŠ DiviZna",
      "Kuřim, kostel sv. Maří Magdalény",
      "Vánoční zpívání žáků ZŠ DiviZna.",
      ["Pozvánka", "vanocni-zpivani.Pozvánka.jpg"],
    ],
    [
      "2025-12-25",
      "",
      "8:00",
      "Pastorely",
      "Kuřim, při mši svaté",
      "Pastorely při mši svaté o Narození Páně.",
      ["Plakát", "pastorely.Plakát.pdf"],
    ],
    [
      "2025-12-24",
      "",
      "15:00",
      "Vánoční příběh",
      "Kuřim",
      "Vánoční příběh pro děti i dospělé.",
      ["Plakát", "vanocni-pribeh.Plakát.pdf"],
    ],
  ]),
];
