import type { NewsEvent } from "./types";

// Finished events for the archive, from the Archiv mockup (see news.ts).

export const UPLOADS = "https://farakurim.cz/uploads/aktuality";

type ArchivedRow = [
  start: string,
  end: string,
  time: string,
  title: string,
  place: string,
  text: string,
  attachment?: [label: string, file: string],
];

/** Compact rows for the finished events of the archive mock. */
const archived = (rows: ArchivedRow[]): NewsEvent[] =>
  rows.map(([start, end, time, title, place, text, attachment], i) => ({
    id: `archiv-${i + 1}`,
    title,
    start,
    end: end || undefined,
    time: time || undefined,
    place,
    text,
    attachments: attachment && [{ label: attachment[0], file: `${UPLOADS}/${attachment[1]}` }],
  }));

export const archivedEvents: NewsEvent[] = archived([
  ["2026-08-08", "2026-08-15", "", "Farní tábor 2026", "tábor pro děti z farnosti", "Letní tábor pro děti z farnosti."],
  [
    "2026-08-03",
    "",
    "9:30",
    "Proměna farnosti s Patrikem Páleníkem z Tchaj-wanu",
    "Brno, Petrov",
    "Setkání o proměně farnosti s misionářem z Tchaj-wanu.",
    ["Pozvánka", "promena-farnosti.Pozvánka.jpg"],
  ],
  [
    "2026-07-26",
    "2026-07-31",
    "",
    "Paray-le-Monial",
    "Paray-le-Monial, Francie",
    "Pouť a setkání rodin v Paray-le-Monial.",
    ["Plakát", "paray-le-monial.Plakát.pdf"],
  ],
  [
    "2026-07-24",
    "2026-07-26",
    "",
    "Krojované hody v Jinačovicích",
    "Jinačovice, sokolovna",
    "Tradiční krojované hody v Jinačovicích.",
    ["Plakát", "hody-jinacovice.Plakát.jpg"],
  ],
  [
    "2026-06-28",
    "",
    "9:00",
    "Slavnostní mše – 800 let Kuřimi",
    "Kuřim, kostel sv. Maří Magdalény",
    "Slavnostní mše k 800 letům Kuřimi.",
  ],
  [
    "2026-06-28",
    "",
    "",
    "Malhostovská pouť",
    "Malhostovice, kostel sv. Vavřince",
    "Pouť v Malhostovicích.",
    ["Plakát", "malhostovska-pout.Plakát.png"],
  ],
  [
    "2026-06-13",
    "",
    "14:00",
    "Farní den – výročí 800 let",
    "Kuřim",
    "Farní den k výročí 800 let.",
    ["Plakát", "farni-den.Plakát.jpeg"],
  ],
  [
    "2026-05-29",
    "",
    "19:30",
    "Noc kostelů",
    "Kuřim, kostel sv. Maří Magdalény",
    "Večerní program v otevřeném kostele.",
    ["Plakát", "noc-kostelu.Plakát.jpg"],
  ],
  [
    "2026-05-24",
    "",
    "17:00",
    "Čtyři violoncella, posvátné hlasy",
    "Kuřim, kostel sv. Maří Magdalény",
    "Koncert duchovní hudby.",
    ["Plakát", "ctyri-violoncella.Plakát.jpg"],
  ],
  [
    "2026-05-24",
    "",
    "8:00",
    "Veni, Creator Spiritus",
    "Kuřim, kostel sv. Maří Magdalény",
    "Slavnost Seslání Ducha svatého.",
    ["Plakát", "veni-creator.Plakát.jpg"],
  ],
  [
    "2026-05-23",
    "",
    "",
    "Charitní pouť v Předklášteří",
    "Předklášteří, Porta coeli",
    "Pouť charity do kláštera Porta coeli.",
    ["Informace", "charitni-pout.Informace.png"],
  ],
  [
    "2026-05-17",
    "",
    "14:00",
    "Den rodin",
    "Kuřim, areál ZŠ Komenského",
    "Odpoledne pro rodiny s dětmi.",
    ["Plakát", "den-rodin.Plakát.png"],
  ],
  [
    "2026-05-12",
    "",
    "18:00",
    "Děkanátní setkání akolytů",
    "Tišnov, kostel sv. Václava",
    "Setkání akolytů tišnovského děkanství.",
    ["Plakát", "setkani-akolytu.Plakát.png"],
  ],
  [
    "2026-04-28",
    "",
    "18:00",
    "Setkání katechetů",
    "Tišnov, fara",
    "Setkání katechetů děkanství.",
    ["Plakát", "setkani-katechetu.Plakát.png"],
  ],
  [
    "2026-04-11",
    "",
    "11:30",
    "Radostná pouť s Pannou Marií na Vranov",
    "Vranov u Brna",
    "Pouť na Vranov u Brna.",
    ["Plakát", "pout-vranov.Plakát.jpg"],
  ],
  [
    "2026-04-02",
    "2026-04-06",
    "",
    "Velikonoce v Altöttingu",
    "Altötting, Německo",
    "Velikonoční pouť do Altöttingu.",
    ["Plakát", "altotting.Plakát.png"],
  ],
  [
    "2026-03-26",
    "",
    "",
    "Nový Petrklíč",
    "zpravodaj farnosti",
    "Vyšlo nové číslo farního zpravodaje.",
    ["Petrklíč", "petrklic-jaro.Petrklíč.pdf"],
  ],
  [
    "2026-03-12",
    "",
    "17:00",
    "Seminář pro katechety a lektory",
    "Tišnov, fara",
    "Seminář pro katechety a lektory Božího slova.",
    ["Informace", "seminar-katechete.Informace.png"],
  ],
  [
    "2026-03-06",
    "2026-03-08",
    "",
    "Kurz vedoucích ministrantů",
    "Osová Bítýška, MAMRE",
    "Víkendový kurz pro vedoucí ministrantů.",
    ["Informace", "kurz-ministrantu.Informace.jpg"],
  ],
  [
    "2026-02-06",
    "",
    "19:00",
    "První pátek",
    "Brno, sv. Tomáš, nebo Kuřim",
    "Prvopáteční setkání.",
    ["Plakát", "prvni-patek.Plakát.pdf"],
  ],
  [
    "2026-01-13",
    "",
    "18:00",
    "Tříkrálový koncert",
    "Kuřim, kostel sv. Maří Magdalény",
    "Koncert k Tříkrálové sbírce.",
    ["Plakát", "trikralovy-koncert.Plakát.pdf"],
  ],
  [
    "2025-12-26",
    "",
    "16:00",
    "Vánoční zpívání ZŠ DiviZna",
    "Kuřim, kostel sv. Maří Magdalény",
    "Vánoční zpívání žáků ZŠ DiviZna.",
    ["Pozvánka", "vanocni-zpivani.Pozvánka.jpg"],
  ],
  [
    "2025-12-25",
    "",
    "8:00",
    "Pastorely",
    "Kuřim, při mši svaté",
    "Pastorely při mši svaté o Narození Páně.",
    ["Plakát", "pastorely.Plakát.pdf"],
  ],
  [
    "2025-12-24",
    "",
    "15:00",
    "Vánoční příběh",
    "Kuřim",
    "Vánoční příběh pro děti i dospělé.",
    ["Plakát", "vanocni-pribeh.Plakát.pdf"],
  ],
]);
