// Adds a confirmed ohlášky sheet to src/content/ohlasky/ (farnost-create-porad-bohosluzeb skill, through
// `pnpm stage porad <pdf> --record <record.json>`, which stages the PDF and passes its week). Each sheet is one
// generated file, <validFrom>.ts, joined by index.ts; a sheet of the same week (a corrected PDF) replaces its file.
// Sheets may share only their boundary day (sheetOrderProblems()). The sheets before the current one (the last whose
// week has started, today in Prague) are removed: the site needs the current sheet and the ones after it. The record's
// rules are serviceSheetSchema's (src/lib/services/schema.ts).

import { existsSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import * as z from "zod";
import type { ServiceSheet } from "@/content/types/services";
import type { IsoDate } from "@/content/types/shared";
import { serviceSheetSchema } from "@/lib/services/schema";
import { currentSheet, sheetOrderProblems } from "@/lib/services/service-sheet";
import { pragueDate } from "@/lib/shared/prague";
import { newsIds, toSource } from "./add-aktualita";

const root = fileURLToPath(new URL("..", import.meta.url));
export const OHLASKY_DIR = join(root, "src/content/ohlasky");

/** The fields the script takes from the staged PDF, never from the record. */
const WEEK_FIELDS = ["pdfUrl", "validFrom", "validTo"] as const;
export type SheetWeek = Pick<ServiceSheet, (typeof WEEK_FIELDS)[number]>;

const SHEET_FILE = /^(\d{4}-\d{2}-\d{2})\.ts$/;
const TYPE_IMPORT = 'import type { ScheduleException, ServiceSheet } from "@/content/types/services";';
const SHEETS_ARRAY = /^export const serviceSheets: ServiceSheet\[\] = \[[^\]]*\];$/m;

/** The export name of the sheet starting on `validFrom`: "sheet20261004". */
export const sheetName = (validFrom: IsoDate) => `sheet${validFrom.replaceAll("-", "")}`;

/** The source of a sheet's file; Prettier formats it afterwards. */
export function sheetSource(sheet: ServiceSheet): string {
  return [
    'import "server-only";',
    'import type { ServiceSheet } from "@/content/types/services";',
    "",
    "// Generated by `pnpm stage porad … --record` (farnost-create-porad-bohosluzeb skill); a corrected record of the",
    "// same week replaces this file.",
    `export const ${sheetName(sheet.validFrom)}: ServiceSheet = ${toSource(sheet)};`,
    "",
  ].join("\n");
}

/** `index` (ohlasky/index.ts) with one import per sheet and `serviceSheets` listing them, in `validFroms` order. */
export function setSheets(index: string, validFroms: IsoDate[]): string {
  if (!index.includes(TYPE_IMPORT) || !SHEETS_ARRAY.test(index))
    throw new Error("ohlasky/index.ts has an unexpected shape");
  const imports = validFroms.map((d) => `import { ${sheetName(d)} } from "./${d}";`);
  return index
    .replace(/^import \{ sheet\d{8} \} from "\.\/\d{4}-\d{2}-\d{2}";\n/gm, "")
    .replace(TYPE_IMPORT, [TYPE_IMPORT, ...imports].join("\n"))
    .replace(SHEETS_ARRAY, `export const serviceSheets: ServiceSheet[] = [${validFroms.map(sheetName).join(", ")}];`);
}

/** The week of every sheet file in `dir`, sorted by `validFrom` (read from the generated source). */
function readWeeks(dir: string): Pick<ServiceSheet, "validFrom" | "validTo">[] {
  return readdirSync(dir)
    .flatMap((file) => SHEET_FILE.exec(file)?.[1] ?? [])
    .sort()
    .map((validFrom) => {
      const validTo = /\bvalidTo: "(\d{4}-\d{2}-\d{2})"/.exec(readFileSync(join(dir, `${validFrom}.ts`), "utf8"))?.[1];
      if (!validTo) throw new Error(`ohlasky/${validFrom}.ts has no validTo`);
      return { validFrom, validTo };
    });
}

export type AddOhlaskyResult = {
  sheet: ServiceSheet;
  /** The sheet's file name in ohlasky/. */
  target: string;
  /** A sheet of the same week was replaced. */
  replaced: boolean;
  /** The outdated sheet files removed (or that would be). */
  removed: string[];
  /** The laterExceptions dates the sheets now cover: the agent removes them from index.ts. */
  covered: IsoDate[];
  /** The files written (absolute), for formatAndTest; empty with `check`. */
  written: string[];
};

/**
 * Adds `input` (the record: days and announcements) for the staged PDF's `week` to `ohlaskyDir`, prunes the sheets
 * before the current one and returns what it did; `check` only validates. Throws with every problem found.
 */
export function addOhlasky(
  ohlaskyDir: string,
  newsDir: string,
  input: unknown,
  week: SheetWeek,
  { check = false, now = new Date() } = {},
): AddOhlaskyResult {
  if (input === null || typeof input !== "object" || Array.isArray(input))
    throw new Error("the record is not an object");
  if (WEEK_FIELDS.some((field) => field in input)) {
    throw new Error(
      "leave pdfUrl, validFrom and validTo out of the record: the script reads pdfUrl, validFrom and validTo from the PDF",
    );
  }
  const parsed = serviceSheetSchema.safeParse({ ...week, ...input });
  if (!parsed.success) throw new Error(`the record is not valid:\n${z.prettifyError(parsed.error)}`);
  const sheet = parsed.data;
  const ids = newsIds(newsDir);
  const unknown = sheet.announcements.flatMap((a, i) =>
    a.newsId && !ids.has(a.newsId) ? [`announcement ${i + 1}: no aktualita with the id ${a.newsId}`] : [],
  );
  if (unknown.length > 0) throw new Error(unknown.join("\n"));

  const existing = readWeeks(ohlaskyDir);
  const replaced = existing.some((s) => s.validFrom === sheet.validFrom);
  const all = [...existing.filter((s) => s.validFrom !== sheet.validFrom), sheet].sort((a, b) =>
    a.validFrom < b.validFrom ? -1 : 1,
  );
  const current = currentSheet(all, pragueDate(now))!;
  const kept = all.filter((s) => s.validFrom >= current.validFrom);
  if (!kept.includes(sheet)) {
    throw new Error(
      `the sheet ${sheet.validFrom} – ${sheet.validTo} is before the current sheet (${current.validFrom}): nothing to add`,
    );
  }
  const problems = sheetOrderProblems(kept);
  if (problems.length > 0) throw new Error(problems.join("\n"));

  const target = `${sheet.validFrom}.ts`;
  const removed = all.filter((s) => !kept.includes(s)).map((s) => `${s.validFrom}.ts`);
  const indexPath = join(ohlaskyDir, "index.ts");
  const index = readFileSync(indexPath, "utf8");
  const lastDay = kept.at(-1)!.validTo;
  // Only laterExceptions carries `date:` in index.ts, in the one-line and in the expanded form.
  const covered = [...index.matchAll(/\bdate: "(\d{4}-\d{2}-\d{2})"/g)]
    .map((m) => m[1])
    .filter((date) => date <= lastDay);
  // Before anything is written: a shape problem must fail the check too and leave the files unchanged.
  const nextIndex = setSheets(
    index,
    kept.map((s) => s.validFrom),
  );
  const written: string[] = [];
  if (!check) {
    writeFileSync(join(ohlaskyDir, target), sheetSource(sheet));
    for (const file of removed) if (existsSync(join(ohlaskyDir, file))) rmSync(join(ohlaskyDir, file));
    writeFileSync(indexPath, nextIndex);
    written.push(join(ohlaskyDir, target), indexPath);
  }
  return { sheet, target, replaced, removed, covered, written };
}

/** The lines the command prints for `result`. */
export function ohlaskyLines(result: AddOhlaskyResult, check: boolean): string[] {
  const { sheet, target, replaced, removed, covered } = result;
  const verb = replaced ? (check ? "Would replace" : "Replaced") : check ? "Would add" : "Added";
  return [
    `${verb} the sheet ${sheet.validFrom} – ${sheet.validTo} ${replaced ? "in" : "to"} src/content/ohlasky/${target}`,
    ...removed.map((file) => `${check ? "Would remove" : "Removed"} the outdated sheet src/content/ohlasky/${file}`),
    ...covered.map(
      (date) => `laterExceptions on ${date} is now covered by the sheet: remove it from src/content/ohlasky/index.ts`,
    ),
  ];
}
