import type { NewsEvent } from "../types";
import { UPLOADS } from "./uploads";

export const events2020: NewsEvent[] = [
  {
    id: "trikralova-sbirka-2020",
    title: "Tříkrálová sbírka 2020",
    start: "2020-01-01",
    end: "2020-01-14",
    place: "Kuřim",
    text: "Jubilejní 20. ročník Tříkrálové sbírky. Hledáme dobrovolníky starší 15 let, kteří povedou koledující skupinky.",
    body:
      "<p>Blíží se jubilejní 20. ročník Tříkrálové sbírky. Sháníme dobrovolníky (starší 15 let), kteří by vedli koledující skupinky.</p>" +
      "<p>Podrobnější informace najdete v přílohách a u Aničky Drahovské.</p>",
    poster: { src: `${UPLOADS}/trikralova-sbirka-2020-letak-1.webp`, alt: "Leták: Tříkrálová sbírka 2020" },
    attachments: [
      { label: "Leták 1", file: `${UPLOADS}/trikralova-sbirka-2020-letak-1.jpg`, size: 1734800 },
      { label: "Leták 2", file: `${UPLOADS}/trikralova-sbirka-2020-letak-2.jpg`, size: 1793338 },
      { label: "Informace", file: `${UPLOADS}/trikralova-sbirka-2020-informace.pdf`, size: 1031304 },
    ],
    links: [{ label: "Tříkrálová sbírka", href: "https://www.trikralovasbirka.cz/" }],
  },
  {
    id: "trikralovy-pruvod-2020",
    title: "Tříkrálový průvod v Tišnově",
    start: "2020-01-06",
    time: "16:00",
    place: "Tišnov, kostel sv. Václava",
    text: "Oslava 20. výročí Tříkrálové sbírky: tříkrálové požehnání a průvod s lucerničkami a hudbou k tišnovské radnici.",
    body: "<p>Zveme všechny koledníky, vedoucí skupinek i dárce. Každý účastník požehnání v tříkrálové koruně bude zařazen do slosování o zajímavé ceny. Po průvodu je zajištěno drobné občerstvení.</p>",
    program: [
      { time: "16:00", title: "Tříkrálové požehnání", note: "kostel sv. Václava" },
      {
        time: "16:15–16:45",
        title: "Průvod s lucerničkami a hudbou",
        note: "k tišnovské radnici, slavnostní troubení",
      },
    ],
    poster: {
      src: `${UPLOADS}/trikralovy-pruvod-2020-plakat.webp`,
      alt: "Plakát: Tříkrálový průvod v Tišnově 6. ledna 2020",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/trikralovy-pruvod-2020-plakat.pdf`, size: 650140 }],
  },
  {
    id: "kurz-alfa-tisnov-2020",
    title: "Kurz Alfa v Tišnově",
    start: "2020-01-16",
    end: "2020-04-02",
    time: "18:30",
    place: "Tišnov, fara",
    mapQuery: "Kostelní 16, Tišnov",
    text: "Evangelizační kurz Alfa v našem děkanství: každý čtvrtek večer na faře v Tišnově.",
    body:
      "<p>Kurzy Alfa jsou bezplatné kurzy organizované dobrovolníky, které se snaží odpovědět na základní otázky lidského života z křesťanského úhlu pohledu.</p>" +
      "<p>Setkání začínají vždy večeří, následuje promluva na dané téma a nakonec se o tématu diskutuje v malých skupinkách. Setkání trvá obvykle kolem dvou hodin a účast na všech večerech je nezávazná. První setkání je 16. 1. v 18:30 na faře v Tišnově (Kostelní 16).</p>",
    attachments: [{ label: "Informace", file: `${UPLOADS}/kurz-alfa-tisnov-2020-informace.pdf`, size: 99647 }],
    links: [{ label: "Kurzy Alfa", href: "https://www.kurzyalfa.cz/" }],
    sessions: 12,
  },
  {
    id: "on-je-zivy-2020",
    title: "On je živý",
    start: "2020-02-07",
    end: "2020-02-09",
    place: "Trenčín, Slovensko",
    text: "Zveme mladé na setkání On je živý v Trenčíně na Slovensku.",
    links: [{ label: "On je živý", href: "https://www.onjezivy.sk/" }],
  },
  {
    id: "valentinska-pout-2020",
    title: "Valentinská pouť",
    start: "2020-02-14",
    time: "17:00",
    place: "Brno, kostel sv. Michala",
    mapQuery: "kostel sv. Michala, Dominikánské náměstí, Brno",
    text: "Valentinská pouť v kostele sv. Michala na Dominikánském náměstí v Brně.",
    poster: { src: `${UPLOADS}/valentinska-pout-2020-plakat.webp`, alt: "Plakát: Valentinská pouť 14. 2. 2020" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/valentinska-pout-2020-plakat.jpg`, size: 467347 }],
  },
  {
    id: "postni-zpovidani-2020",
    title: "Postní zpovídání",
    start: "2020-02-27",
    end: "2020-03-01",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Využijte příležitosti ke svátosti smíření na začátku postní doby.",
    body: "<p>Zpovídat se bude <strong>27. 2.</strong>, <strong>29. 2.</strong> a <strong>1. 3.</strong> vždy v <strong>7:30</strong> před mší svatou a <strong>28. 2.</strong> v <strong>18:30</strong> po mši svaté.</p>",
  },
  {
    id: "zruseni-bohosluzeb-koronavirus-2020",
    title: "Zrušení bohoslužeb kvůli pandemii koronaviru",
    start: "2020-03-12",
    text: "Do odvolání se ruší všechny bohoslužby a jiná shromáždění v kostelích brněnské diecéze.",
    body:
      "<p>Od čtvrtka 12. března 2020 od 14:00 se do odvolání ruší všechny (tedy nejen nedělní) bohoslužby, společné pobožnosti, duchovní obnovy, modlitební setkání a jiná shromáždění v kostelích, kaplích a jiných prostorách římskokatolické církve na území brněnské diecéze. Kněží budou slavit mše svaté bez účasti lidu na úmysly, na které by byly slouženy veřejně.</p>" +
      "<p>Ježíše Krista je možné v těchto případech přijímat duchovně, tedy vyjádřením touhy po jeho přijetí a spojením se s ním v duchovní jednotě.</p>",
    attachments: [
      {
        label: "Rozhodnutí biskupa",
        file: `${UPLOADS}/zruseni-bohosluzeb-koronavirus-2020-rozhodnuti.pdf`,
        size: 110791,
      },
      { label: "Manuál ke koronaviru", file: `${UPLOADS}/zruseni-bohosluzeb-koronavirus-2020-manual.pdf`, size: 93458 },
    ],
    links: [
      {
        label: "Rozhodnutí biskupa na webu biskupství",
        href: "https://www.biskupstvi.cz/2020-03-12-rozhodnuti-biskupa-covid",
      },
    ],
  },
  {
    id: "postni-duchovni-obnova-2020",
    title: "Postní duchovní obnova",
    start: "2020-03-21",
    time: "13:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Duchovní obnova na téma Zpytování (s)vědomí, kterou provede o. Michael Macek.",
    body: "<p>Přijďte se v postní době ztišit, načerpat sílu a zůstat pár chvil s Pánem v Nejsvětější svátosti. Během obnovy bude možnost přistoupit ke svátosti smíření.</p>",
    program: [
      { time: "13:00", title: "Začátek duchovní obnovy", note: "téma Zpytování (s)vědomí, o. Michael Macek" },
      { time: "16:00", title: "Mše svatá" },
    ],
    poster: {
      src: `${UPLOADS}/postni-duchovni-obnova-2020-plakat.webp`,
      alt: "Plakát: Postní duchovní obnova – Zpytování (s)vědomí",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/postni-duchovni-obnova-2020-plakat.pdf`, size: 114191 }],
  },
  {
    id: "prenosy-bohosluzeb-2020",
    title: "Přenosy bohoslužeb na internetu",
    start: "2020-03-22",
    text: "Využijte nabídky přenosů bohoslužeb, zvláště nedělních, v televizi, rozhlase a na internetu.",
    body: "<p>TV Noe přenáší nedělní mši svatou v 10:30 a v 18:00, Radio Proglas v 9:00 a v 19:30. Přehled přenosů najdete také na webu Mše online.</p>",
    links: [
      { label: "Mše online", href: "https://mseonline.cz/" },
      { label: "TV Noe – živé vysílání", href: "https://www.tvnoe.cz/live" },
      {
        label: "Radio Proglas – příjem vysílání",
        href: "https://www.proglas.cz/kontakty-a-info/prijem-vysilani/internet/",
      },
    ],
  },
  {
    id: "iniciativy-papeze-frantiska-2020",
    title: "Iniciativy papeže Františka v době pandemie",
    start: "2020-03-25",
    end: "2020-03-27",
    text: "Papež František zve ke společné modlitbě Otče náš a k modlitebnímu zastavení s požehnáním Urbi et orbi.",
    body:
      "<p>„Všechny vyzývám, aby se ve středu <strong>25. března v poledne</strong> pomodlili všichni zároveň Otče náš. V den, kdy si mnozí křesťané připomínají, že bylo Panně Marii zvěstováno Vtělení Slova, kéž Pán vyslyší jednomyslnou modlitbu všech svých učedníků.</p>" +
      "<p>S tímtéž úmyslem budu v pátek <strong>27. března v 18 hodin</strong> předsedat modlitebnímu zastavení na prázdném náměstí před bazilikou sv. Petra. Budeme naslouchat Božímu slovu, vzneseme svoji úpěnlivou prosbu a budeme adorovat Nejsvětější svátost, kterou na závěr udělím požehnání Urbi et orbi, spojené s příležitostí obdržet plnomocné odpustky.“</p>" +
      "<p>Modlitební zastavení mimořádně vysílá TV Noe.</p>",
    attachments: [
      { label: "Celá zpráva", file: `${UPLOADS}/iniciativy-papeze-frantiska-2020-zprava.pdf`, size: 171840 },
    ],
    links: [
      {
        label: "TV Noe – požehnání Urbi et orbi",
        href: "https://www.tvnoe.cz/porad/27687-mimoradne-pozehnani-urbi-et-orbi",
      },
    ],
  },
  {
    id: "planovane-opravy-2020",
    title: "Plánované opravy v roce 2020",
    start: "2020-03-28",
    text: "Letos se opravuje krov a střecha kostela v Moravských Knínicích, ohradní zeď a přístavba kuřimské fary. Budeme vděční za jakoukoliv podporu.",
    body:
      "<p>V Moravských Knínicích na kostele sv. Markéty proběhnou opravy krovu a střechy nad chrámovou lodí a fixace vrcholu věže. Na kuřimské faře se dokončuje oprava ohradní zdi, proběhne oprava kanalizace, zavedení plynu a další navazující práce. V přístavbě se připravuje sociální zázemí. V kuřimském kostele se předpokládá běžná údržba, na kapli pod kostelem obnova nátěrů okenních rámů a ošetření omítky soklu.</p>" +
      "<p>Budeme vděční za jakoukoliv podporu. Dárcům bude na požádání vystaven doklad pro daňové přiznání. Účet farnosti: <strong>247704317/0300</strong>, variabilní symbol:</p>" +
      "<ul><li><strong>4444</strong> pro dary na opravy knínického kostela,</li><li><strong>5555</strong> pro dary na opravy kuřimské fary.</li></ul>",
    attachments: [
      { label: "Informace", file: `${UPLOADS}/planovane-opravy-2020-informace.pdf`, size: 66718 },
      { label: "Foto: krov knínického kostela", file: `${UPLOADS}/planovane-opravy-2020-foto-1.jpg`, size: 3793026 },
      { label: "Foto: půda knínického kostela", file: `${UPLOADS}/planovane-opravy-2020-foto-2.jpg`, size: 2732187 },
      {
        label: "Foto: půda u věže knínického kostela",
        file: `${UPLOADS}/planovane-opravy-2020-foto-3.jpg`,
        size: 2693716,
      },
      { label: "Foto: stará zeď fary", file: `${UPLOADS}/planovane-opravy-2020-foto-4.jpg`, size: 2650692 },
      { label: "Foto: otloukání omítky zdi", file: `${UPLOADS}/planovane-opravy-2020-foto-5.jpg`, size: 4599645 },
      { label: "Foto: zdění přístavby fary", file: `${UPLOADS}/planovane-opravy-2020-foto-6.jpg`, size: 3350764 },
      {
        label: "Foto: betonování stropu přístavby",
        file: `${UPLOADS}/planovane-opravy-2020-foto-7.jpg`,
        size: 2449324,
      },
      { label: "Foto: věnec přístavby fary", file: `${UPLOADS}/planovane-opravy-2020-foto-8.jpg`, size: 3419551 },
    ],
  },
  {
    id: "katolicky-tydenik-zdarma-2020",
    title: "Katolický týdeník zdarma",
    start: "2020-03-29",
    text: "Kvůli nouzovému stavu je Katolický týdeník dočasně k dispozici zdarma ke stažení v PDF.",
    links: [
      {
        label: "Katolický týdeník ke stažení",
        href: "https://www.katyd.cz/clanky/novy-kt-ke-stazeni-zdarma-vzdy-od-soboty-1.html",
      },
    ],
  },
  {
    id: "velikonoce-2020",
    title: "Velikonoce 2020",
    start: "2020-04-05",
    end: "2020-04-12",
    text: "Velikonoce bez veřejných bohoslužeb: přenos mše svaté z kuřimského kostela, texty k domácí liturgii a zpověď touhy.",
    body:
      "<p>Na Boží hod velikonoční <strong>12. dubna v 9:30</strong> můžete živě sledovat mši svatou z kuřimského kostela na YouTube kanálu Kuřimského magazínu. Kuřimská kabelová televize Kotva připravila pořad s poselstvím k letošním velikonočním svátkům, natáčený v kuřimském kostele.</p>" +
      "<p><strong>Velikonoční zpověď – „zpověď touhy“:</strong> v nouzovém stavu je mimořádná možnost získat odpuštění hříchů, a to i smrtelných, dokonalou lítostí vycházející z lásky k Bohu milovanému nade všechno, vyjádřenou upřímnou žádostí o odpuštění a doprovázenou pevným předsevzetím jít ke svátostné zpovědi, jakmile to bude možné.</p>",
    attachments: [
      { label: "Bohoslužba domácí církve", file: `${UPLOADS}/velikonoce-2020-liturgie.pdf`, size: 195507 },
      { label: "Křížová cesta v době pandemie", file: `${UPLOADS}/velikonoce-2020-krizova-cesta.pdf`, size: 333726 },
      { label: "Pastýřský list biskupa Vojtěcha", file: `${UPLOADS}/velikonoce-2020-pastyrsky-list.pdf`, size: 80637 },
      { label: "Velikonoční výzva biskupů", file: `${UPLOADS}/velikonoce-2020-vyzva-biskupu.pdf`, size: 1083141 },
    ],
    links: [
      { label: "Kuřimský magazín na YouTube", href: "https://www.youtube.com/channel/UCx_BAFyPjTICyoOeRDy18VA/videos" },
    ],
  },
  {
    id: "petrklic-2020-1",
    title: "Velikonoční Petrklíč 1/2020",
    start: "2020-04-06",
    text: "Vyšlo nové, velikonoční vydání farního časopisu Petrklíč.",
    attachments: [{ label: "Petrklíč 1/2020", file: "/uploads/petrklic/2020-1/petrklic-2020-1.pdf", size: 1171053 }],
  },
  {
    id: "zivy-prenos-mse-svate-2020-04-19",
    title: "Živý přenos mše svaté 19. dubna",
    start: "2020-04-19",
    time: "9:30",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Opět živě přenášíme nedělní mši svatou z kuřimského kostela.",
    links: [{ label: "Záznam na YouTube", href: "https://youtu.be/Egsz1VeojxY" }],
  },
  {
    id: "zivy-prenos-mse-svate-2020-04-26",
    title: "Živý přenos mše svaté 26. dubna",
    start: "2020-04-26",
    time: "11:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Další přenos nedělní mše svaté z kuřimského kostela, opět na YouTube kanálu Kuřimského magazínu.",
    links: [
      { label: "Kuřimský magazín na YouTube", href: "https://www.youtube.com/channel/UCx_BAFyPjTICyoOeRDy18VA/videos" },
    ],
  },
  {
    id: "farni-pout-polsko-2020",
    title: "Farní pouť do Polska",
    start: "2020-04-30",
    end: "2020-05-03",
    place: "Čenstochová, Licheň a Křešov",
    text: "Pouť na mariánská poutní místa v Polsku, kterou chceme společně vstoupit do májového měsíce pod ochranou Panny Marie.",
    body:
      "<p>Navštívíme Čenstochovou, Starý Licheň a Křešov. Cena zahrnuje cestu autobusem, tři noclehy, stravu a skupinové vstupné. Odjíždí se ve čtvrtek 30. dubna v 7:45 od kuřimské fary.</p>" +
      "<p>Přihlášky jsou na stolečku pod kůrem.</p>",
    poster: {
      src: `${UPLOADS}/farni-pout-polsko-2020-plakat.webp`,
      alt: "Plakát: Farní pouť do Polska 30. dubna – 3. května 2020",
    },
    attachments: [
      { label: "Plakát", file: `${UPLOADS}/farni-pout-polsko-2020-plakat.pdf`, size: 2045883 },
      { label: "Informace", file: `${UPLOADS}/farni-pout-polsko-2020-informace.pdf`, size: 78866 },
      { label: "Přihláška", file: `${UPLOADS}/farni-pout-polsko-2020-prihlaska.pdf`, size: 36536 },
    ],
    price: "2 800 Kč, děti do 6 let 2 500 Kč",
  },
  {
    id: "velikonocni-prani-dusana-hladika-2020",
    title: "Velikonoční přání Mons. Dušana Hladíka",
    start: "2020-05-02",
    text: "Prohlédněte si přání k Velikonocům od kuřimského rodáka Mons. Dušana Hladíka.",
    poster: {
      src: `${UPLOADS}/velikonocni-prani-dusana-hladika-2020-prani.webp`,
      alt: "Velikonoční přání Mons. Dušana Hladíka",
    },
    attachments: [
      { label: "Přání", file: `${UPLOADS}/velikonocni-prani-dusana-hladika-2020-prani.png`, size: 8562135 },
    ],
  },
  {
    id: "zivy-prenos-mse-svate-2020-05-03",
    title: "Živý přenos mše svaté z Moravských Knínic",
    start: "2020-05-03",
    time: "11:00",
    place: "Moravské Knínice, kostel sv. Markéty",
    text: "Přenos nedělní mše svaté z knínického kostela, tentokrát s lepší kamerou a dopředu vyzkoušený.",
    links: [{ label: "Záznam na YouTube", href: "https://youtu.be/04eqa-zMdE8" }],
  },
  {
    id: "list-papeze-k-mesici-kvetnu-2020",
    title: "List Svatého otce k měsíci květnu",
    start: "2020-05-04",
    text: "Papež František zve v měsíci květnu všechny ke znovuobjevení krásy domácí modlitby růžence.",
    attachments: [
      { label: "List Svatého otce", file: `${UPLOADS}/list-papeze-k-mesici-kvetnu-2020-list.pdf`, size: 80973 },
    ],
  },
  {
    id: "koncert-violoncellistu-2020",
    title: "Koncert violoncellistů Filharmonie Brno",
    start: "2020-05-24",
    time: "17:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Violoncellisté Filharmonie Brno zahrají skladby Vivaldiho, Grafa, Mahlera a Rossiniho.",
    body: "<p>Koncert pod uměleckým vedením koncertního mistra Pavla Šabackého se koná ku příležitosti znovuzahájení koncertní činnosti a je věnován spoluobčanům jako poděkování. Koncert se koná s podporou města Kuřimi.</p>",
    poster: {
      src: `${UPLOADS}/koncert-violoncellistu-2020-plakat.webp`,
      alt: "Plakát: Brněnští violoncellisté v Kuřimi 24. 5. 2020",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/koncert-violoncellistu-2020-plakat.pdf`, size: 155115 }],
  },
  {
    id: "pouti-na-vranov-2020",
    title: "Putování na Vranov",
    start: "2020-05-30",
    end: "2020-08-30",
    place: "Vranov u Brna",
    text: "K 780. výročí poutního místa Vranov u Brna zve vranovská farnost na čtyři poutě z okolních obcí.",
    body:
      "<p>Vranovská farnost by ráda umožnila lidem vžít se do mentality poutníků, kteří po staletí putovali s vděčností za dobro, kterého se jim dostávalo, a s touhou svěřit své starosti někomu, kdo osobně zakusil, že u Boha není nic nemožné.</p>" +
      "<p>Více se dozvíte z plakátu a z dopisu vranovského faráře Pavla Kříže.</p>",
    poster: {
      src: `${UPLOADS}/pouti-na-vranov-2020-plakat.webp`,
      alt: "Plakát: Putování na Vranov s vděčností a prosbou",
    },
    attachments: [
      { label: "Plakát", file: `${UPLOADS}/pouti-na-vranov-2020-plakat.pdf`, size: 469016 },
      { label: "Dopis vranovského faráře", file: `${UPLOADS}/pouti-na-vranov-2020-dopis.pdf`, size: 102937 },
    ],
    links: [{ label: "Poutní místo Vranov", href: "https://www.dc-vranov.cz/" }],
    sessions: 4,
  },
  {
    id: "farni-den-2020",
    title: "Farní den",
    start: "2020-06-21",
    time: "15:00",
    place: "Kuřim, areál za farou",
    text: "Přátelské setkání a posezení s opékáním špekáčků v areálu za farou.",
    links: [{ label: "Fotogalerie na Zoneramě", href: "https://www.zonerama.com/FarnostKurim/Album/6323662" }],
  },
  {
    id: "svatomarketske-hody-2020",
    title: "Svatomarkétské hody",
    start: "2020-07-17",
    end: "2020-07-19",
    place: "Moravské Knínice",
    text: "Zveme všechny farníky do Moravských Knínic na oslavu patronky místního kostela sv. Markéty.",
    poster: {
      src: `${UPLOADS}/svatomarketske-hody-2020-program.webp`,
      alt: "Plakát: Markétské hody v Moravských Knínicích 17.–19. července 2020",
    },
    attachments: [{ label: "Program", file: `${UPLOADS}/svatomarketske-hody-2020-program.pdf`, size: 1097717 }],
  },
  {
    id: "hody-kurim-jinacovice-2020",
    title: "Hody v Kuřimi a Jinačovicích",
    start: "2020-07-24",
    end: "2020-07-26",
    place: "Kuřim a Jinačovice",
    text: "Přijměte pozvání na Babské hody v Kuřimi a na Mladé hody a den obce v Jinačovicích.",
    poster: { src: `${UPLOADS}/hody-kurim-jinacovice-2020-plakat-kurim.webp`, alt: "Plakát: 8. Babské hody Kuřim" },
    attachments: [
      {
        label: "Plakát: Babské hody v Kuřimi",
        file: `${UPLOADS}/hody-kurim-jinacovice-2020-plakat-kurim.pdf`,
        size: 119158,
      },
      {
        label: "Plakát: Mladé hody v Jinačovicích",
        file: `${UPLOADS}/hody-kurim-jinacovice-2020-plakat-jinacovice.pdf`,
        size: 356778,
      },
    ],
  },
  {
    id: "koncert-pro-jasminku-2020",
    title: "Koncert pro Jasmínku",
    start: "2020-07-26",
    time: "18:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Koncert mladých muzikantů, jehož výtěžek je věnován Jasmínce a její rodině.",
    body:
      "<p>Zazní skladby například od Telemanna, Vranického a Bacha. Ze známých tváří uslyšíte Tomáše Novotného či Dorotku a Štěpánku Kytnerovy.</p>" +
      "<p>Jasmínka je téměř dvanáctiletá usměvavá slečna. Když jí bylo pět let, srazil ji na přechodu nepozorný řidič a od té doby je upoutána na vozík. Úsměv, optimismus a smysl pro humor ji ale neopustily.</p>",
    poster: {
      src: `${UPLOADS}/koncert-pro-jasminku-2020-plakat.webp`,
      alt: "Plakát: Koncert pro Jasmínku 26. 7. 2020",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/koncert-pro-jasminku-2020-plakat.pdf`, size: 1008259 }],
  },
  {
    id: "farni-tabor-2020",
    title: "Farní tábor 2020",
    start: "2020-08-15",
    end: "2020-08-22",
    text: "Společenství mladých opět pořádá letní farní tábor.",
    links: [{ label: "Fotogalerie na Zoneramě", href: "https://www.zonerama.com/FarnostKurim/Album/6515817" }],
  },
  {
    id: "marianske-pouti-2020",
    title: "Mariánské poutě",
    start: "2020-09-06",
    end: "2020-09-20",
    place: "Vranov u Brna a Žarošice",
    text: "Přijměte pozvání na cyklopouť a pěší pouť na Vranov a na Zlatou sobotu v Žarošicích.",
    program: [
      {
        time: "6. 9. 12:30",
        title: "Cyklopouť z Kuřimi na Vranov",
        note: "z parku na ulici Havlíčkova, mše svatá v 15:00",
      },
      { time: "12. 9.", title: "Zlatá sobota v Žarošicích", note: "odpoledne" },
      { time: "20. 9. 7:30", title: "Tradiční pěší pouť Moravské Knínice – Kuřim – Vranov", note: "mše svatá v 11:00" },
    ],
    poster: {
      src: `${UPLOADS}/marianske-pouti-2020-plakat-pesi-pout.webp`,
      alt: "Plakát: Tradiční pěší pouť na Vranov 20. září 2020",
    },
    attachments: [
      {
        label: "Plakát: Pěší pouť na Vranov",
        file: `${UPLOADS}/marianske-pouti-2020-plakat-pesi-pout.pdf`,
        size: 682311,
      },
      {
        label: "Plakát: Cyklopouť na Vranov",
        file: `${UPLOADS}/marianske-pouti-2020-plakat-cyklopout.pdf`,
        size: 333088,
      },
      {
        label: "Plakát: Zlatá sobota v Žarošicích",
        file: `${UPLOADS}/marianske-pouti-2020-plakat-zlata-sobota.pdf`,
        size: 2265750,
      },
      {
        label: "Plakát: Sedmiradostná cesta",
        file: `${UPLOADS}/marianske-pouti-2020-plakat-sedmiradostna-cesta.pdf`,
        size: 327454,
      },
    ],
  },
  {
    id: "varhanni-koncert-kninice-2020",
    title: "Varhanní koncert v Moravských Knínicích",
    start: "2020-09-13",
    time: "17:00",
    place: "Moravské Knínice, kostel sv. Markéty",
    text: "Dobročinný koncert varhanice Hany Bartošové a flétnistky Hany Hána, výtěžek je určen na opravy kostela.",
    body: "<p>Podvečer u varhan se starými mistry v rámci Brněnského varhanního festivalu. Na programu jsou skladby L. Vinciho, M. Weckmanna, J. K. Vaňhala, J. Segera a J. K. Kuchaře. Vstupné dobrovolné.</p>",
    poster: {
      src: `${UPLOADS}/varhanni-koncert-kninice-2020-plakat.webp`,
      alt: "Plakát: Varhanní koncert v Moravských Knínicích 13. září 2020",
    },
    attachments: [
      { label: "Plakát", file: `${UPLOADS}/varhanni-koncert-kninice-2020-plakat.pdf`, size: 340327 },
      { label: "O Haně Bartošové", file: `${UPLOADS}/varhanni-koncert-kninice-2020-hana-bartosova.pdf`, size: 180618 },
      { label: "O Haně Hána", file: `${UPLOADS}/varhanni-koncert-kninice-2020-hana-hana.pdf`, size: 284126 },
    ],
  },
  {
    id: "diktatura-versus-nadeje-2020",
    title: "Výstava Diktatura versus naděje",
    start: "2020-09-18",
    end: "2020-10-08",
    place: "Brno, kostel sv. Jakuba",
    text: "Výstava o pronásledování římskokatolické církve v Československu v letech 1948–1989. Vstup volný.",
    body: "<p>Výstavu uspořádal Ústav pro studium totalitních režimů a Archiv Kanceláře prezidenta republiky ve spolupráci s brněnským biskupstvím.</p>",
    poster: {
      src: `${UPLOADS}/diktatura-versus-nadeje-2020-plakat.webp`,
      alt: "Plakát: výstava Diktatura versus naděje",
    },
    attachments: [
      { label: "Plakát", file: `${UPLOADS}/diktatura-versus-nadeje-2020-plakat.pdf`, size: 4029188 },
      { label: "Pozvánka", file: `${UPLOADS}/diktatura-versus-nadeje-2020-pozvanka.jpg`, size: 509478 },
    ],
    links: [
      { label: "Výstava na webu cirkev.cz", href: "https://www.cirkev.cz/cs/aktuality/200810diktatura-versus-nadeje" },
    ],
  },
  {
    id: "concentus-moraviae-2020",
    title: "Concentus Moraviae",
    start: "2020-09-23",
    time: "19:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Koncert XXV. ročníku festivalu Concentus Moraviae: na varhany hraje Kateřina Chroboková. Vstupenky v předprodeji.",
    links: [{ label: "Program festivalu", href: "https://concentus-moraviae.cz/program-2020/" }],
  },
  {
    id: "rozhovor-o-sv-vaclavu-2020",
    title: "Rozhovor o sv. Václavu",
    start: "2020-09-28",
    text: "Kuřimská televize Kotva odvysílala rozhovor o sv. Václavu, patronu českého národa.",
    links: [{ label: "Kotva TV na YouTube", href: "https://www.youtube.com/user/kotvaka/videos" }],
  },
  {
    id: "at-svoboda-zni-2020",
    title: "Ať svoboda zní",
    start: "2020-10-04",
    time: "18:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Koncert duchovní hudby k výročí projevu Martina Luthera Kinga „Mám sen“. Vystoupí brněnská skupina DNA a pražská Let’s Go.",
    price: "dobrovolné vstupné",
    poster: { src: `${UPLOADS}/at-svoboda-zni-2020-plakat.webp`, alt: "Plakát: Koncert duchovní hudby Ať svoboda zní" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/at-svoboda-zni-2020-plakat.jpg`, size: 397648 }],
  },
  {
    id: "vystava-kardinal-spidlik-2020",
    title: "Výstava o kardinálu Špidlíkovi",
    start: "2020-10-11",
    time: "14:00–18:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Výstava o kardinálu Tomáši Špidlíkovi a beseda se senátorkou Jaromírou Vítkovou.",
    program: [
      { time: "14:00", title: "Otevření výstavy" },
      { time: "15:00", title: "Beseda se senátorkou Ing. Jaromírou Vítkovou", note: "s prezentací fotografií" },
    ],
  },
  {
    id: "adoracni-den-2020",
    title: "Adorační den farnosti",
    start: "2020-10-12",
    time: "8:00–19:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Adorační den naší farnosti. Zapište se pod kůrem, kdy přijdete adorovat.",
    body: "<p>Děkujeme všem, kdo se zapsali do rozpisu adorací, a vybízíme i ostatní, aby se také zapojili.</p>",
    program: [
      { time: "8:00", title: "Mše svatá", note: "zahájení" },
      { time: "8:30–19:00", title: "Tichá adorace" },
      { time: "19:00", title: "Modlitba růžence a požehnání farnosti" },
    ],
  },
  {
    id: "vyzva-biskupu-nebojte-se-2020",
    title: "Výzva biskupů: Nebojte se!",
    start: "2020-10-25",
    text: "Biskupové Čech, Moravy a Slezska se obracejí na věřící slovy sv. Jana Pavla II.: Nebojte se!",
    attachments: [{ label: "Výzva biskupů", file: `${UPLOADS}/vyzva-biskupu-nebojte-se-2020-vyzva.pdf`, size: 119429 }],
  },
  {
    id: "pastyrsky-list-vsech-svatych-2020",
    title: "Pastýřský list biskupa Vojtěcha",
    start: "2020-11-01",
    text: "K slavnosti Všech svatých posílá biskup Vojtěch Cikrle věřícím pastýřský list „Všichni jsme na cestě ke svatosti“.",
    attachments: [
      {
        label: "Pastýřský list",
        file: `${UPLOADS}/pastyrsky-list-vsech-svatych-2020-pastyrsky-list.pdf`,
        size: 182691,
      },
    ],
  },
  {
    id: "zivy-prenos-mse-svate-2020-11-15",
    title: "Živý přenos mše svaté 15. listopadu",
    start: "2020-11-15",
    time: "9:30",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Nedělní mši svatou zkušebně vysíláme na YouTube.",
    links: [{ label: "Záznam na YouTube", href: "https://youtu.be/YSz_Yj9PWF0" }],
  },
  {
    id: "adoracni-odpoledne-kurim-2020",
    title: "Adorační odpoledne v Kuřimi",
    start: "2020-11-15",
    time: "13:00–20:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Výstav Nejsvětější svátosti s rozpisem adorujících po půlhodinách.",
    body: "<p>Adorovat se bude po dvojicích (případně členové jedné domácnosti). Příležitost ke svaté zpovědi bude během adorace od 15 do 17 hodin.</p>",
  },
  {
    id: "adoracni-odpoledne-kninice-2020",
    title: "Adorační odpoledne v Moravských Knínicích",
    start: "2020-11-22",
    time: "12:00–20:00",
    place: "Moravské Knínice, kostel sv. Markéty",
    text: "Výstav Nejsvětější svátosti v knínickém kostele. Rozpis pro střídání je vyvěšen na kostelních dveřích.",
    body: "<p>Příležitost ke svaté zpovědi bude během adorace od 14:00 do 15:30 v sakristii.</p>",
  },
  {
    id: "charitativni-jarmark-ceska-2020",
    title: "Charitativní jarmark v České",
    start: "2020-11-22",
    place: "Česká",
    text: "Jubilejní 20. ročník jarmarku se letos koná netradičně formou sbírky, do které může přispět každý.",
    poster: {
      src: `${UPLOADS}/charitativni-jarmark-ceska-2020-letak.webp`,
      alt: "Leták: 20. netradiční farní charitativní jarmark",
    },
    attachments: [{ label: "Leták", file: `${UPLOADS}/charitativni-jarmark-ceska-2020-letak.pdf`, size: 450138 }],
  },
  {
    id: "cervena-streda-2020",
    title: "Červená středa",
    start: "2020-11-25",
    time: "18:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Mezinárodní připomínka lidí pronásledovaných pro víru: kostel nasvícený červeně, mše svatá a adorace.",
    program: [
      { time: "13:00", title: "Online konference", note: "s českými i zahraničními hosty a svědky pronásledování" },
      { time: "17:00", title: "Kostel se rozsvítí červeně" },
      { time: "18:00", title: "Mše svatá za lidi pronásledované pro víru" },
      { time: "po mši", title: "Adorace do 20:00", note: "s příležitostí ke svaté zpovědi" },
    ],
    poster: { src: `${UPLOADS}/cervena-streda-2020-plakat.webp`, alt: "Plakát: Červená středa 25. listopadu 2020" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/cervena-streda-2020-plakat.jpg`, size: 433885 }],
    links: [{ label: "Červená středa", href: "https://www.cervenastreda.cz/" }],
  },
  {
    id: "krabice-od-bot-2020",
    title: "Krabice od bot",
    start: "2020-11-29",
    end: "2020-12-06",
    place: "Kuřim a Moravské Knínice",
    text: "Charitativní sbírka dárků pro děti z dětských a azylových domů.",
    body:
      "<p>Do krabice od bot můžete zabalit dárky, které by dětem udělaly radost, například hračky, školní a výtvarné potřeby, kosmetiku a doplňky, vše v bezvadném stavu. Na krabici napište, zda je určena pro kluka, nebo děvče, a věk dítěte. Pod mašličku vložte fotografii obsahu (i černobílou), nebo ji pošlete e-mailem.</p>" +
      "<p>Krabice předejte v neděli <strong>29. 11.</strong> a <strong>6. 12.</strong> od 7:30 do 10:30 v bočním vchodu kuřimského kostela, v Moravských Knínicích v sakristii před mší svatou nebo po ní. V neděli 6. 12. odpoledne je pracovník Charity odveze na sběrné místo.</p>",
    links: [{ label: "prokopovahanka@seznam.cz", href: "mailto:prokopovahanka@seznam.cz" }],
  },
  {
    id: "adventni-pribehy-pro-deti-2020",
    title: "Krátké adventní příběhy pro děti",
    start: "2020-11-29",
    end: "2020-12-20",
    text: "Každou adventní neděli je pro děti připraven příběh, ve kterém se posuneme vždy o kousek blíže k Betlému.",
  },
  {
    id: "adorace-pred-vanoci-2020",
    title: "Adorace před Vánoci",
    start: "2020-12-20",
    time: "13:00–20:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Adorace v kuřimském kostele s rozpisem adorujících.",
  },
  {
    id: "prodej-vyrobku-pro-farnost-2020",
    title: "Prodej ručně vyráběných výrobků pro farnost",
    start: "2020-12-20",
    time: "14:30–15:30",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Zakoupením ručně vyráběných výrobků můžete přispět na opravu fary. Výrobky budou k mání při adoraci.",
    body: "<p>Osobní předání lze domluvit i na jinou dobu. Bližší informace podá Lucie Sádlíková.</p>",
    attachments: [
      { label: "Katalog výrobků", file: `${UPLOADS}/prodej-vyrobku-pro-farnost-2020-katalog.pdf`, size: 644987 },
    ],
    links: [{ label: "luciesadlikova@email.cz", href: "mailto:luciesadlikova@email.cz" }],
  },
  {
    id: "porad-bohosluzeb-vanoce-2020",
    title: "Pořad bohoslužeb o Vánocích",
    start: "2020-12-20",
    end: "2021-01-10",
    place: "Kuřim a Moravské Knínice",
    text: "Pořad předvánočních a vánočních bohoslužeb včetně rozpisu zpovídání.",
    attachments: [
      {
        label: "Pořad bohoslužeb a zpovídání",
        file: `${UPLOADS}/porad-bohosluzeb-vanoce-2020-porad-bohosluzeb.pdf`,
        size: 136783,
      },
    ],
  },
  {
    id: "petrklic-2020-2",
    title: "Vánoční Petrklíč 2/2020",
    start: "2020-12-19",
    text: "Právě vyšlo nové, vánoční vydání farního časopisu Petrklíč.",
    attachments: [{ label: "Petrklíč 2/2020", file: "/uploads/petrklic/2020-2/petrklic-2020-2.pdf", size: 917356 }],
  },
  {
    id: "betlemske-svetlo-2020",
    title: "Betlémské světlo",
    start: "2020-12-23",
    place: "Kuřim",
    text: "Skauti i letos přivezou do Kuřimi Betlémské světlo a dopoledne ho roznesou až před dům.",
    body: "<p>Pokud o donesení světla stojíte, napište e-mail se svým jménem a adresou, nebo nechte lísteček v kuřimském kostele.</p>",
    poster: { src: `${UPLOADS}/betlemske-svetlo-2020-plakat.webp`, alt: "Plakát: Betlémské světlo" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/betlemske-svetlo-2020-plakat.png`, size: 2405336 }],
    links: [
      { label: "betlemskesvetlo@skautkurim.cz", href: "mailto:betlemskesvetlo@skautkurim.cz" },
      { label: "Betlémské světlo", href: "https://www.betlemskesvetlo.cz/" },
    ],
  },
];
