import type { NewsEvent } from "../types";
import { UPLOADS } from "./uploads";

export const events2021: NewsEvent[] = [
  {
    id: "trikralova-sbirka-2021",
    title: "Tříkrálová sbírka 2021",
    start: "2021-01-01",
    end: "2021-01-24",
    place: "Kuřim",
    text: "Letos se sbírka přesunula převážně do online prostoru. Přispět ale můžete i do pokladniček na vybraných místech v Kuřimi.",
    body:
      "<p>Pokladničky jsou v kostele sv. Maří Magdalény (v čase pravidelných bohoslužeb), na podatelně městského úřadu a v řadě kuřimských obchodů a lékáren, které budou označeny informačními letáky. Z bezpečnostních důvodů je nutné si pokladničku v prodejně vyžádat.</p>" +
      "<p>Seznam všech míst najdete v přílohách.</p>",
    poster: { src: `${UPLOADS}/trikralova-sbirka-2021-letak.webp`, alt: "Leták: Tříkrálová sbírka 2021" },
    attachments: [
      { label: "Leták", file: `${UPLOADS}/trikralova-sbirka-2021-letak.pdf`, size: 314872 },
      { label: "Místa pokladniček", file: `${UPLOADS}/trikralova-sbirka-2021-mista.pdf`, size: 392006 },
      { label: "Informace", file: `${UPLOADS}/trikralova-sbirka-2021-informace.pdf`, size: 127861 },
    ],
    links: [{ label: "Tříkrálová sbírka", href: "https://www.trikralovasbirka.cz/" }],
  },
  {
    id: "narodni-tyden-manzelstvi-2021",
    title: "Národní týden manželství",
    start: "2021-02-08",
    end: "2021-02-14",
    text: "Patnáctý ročník Národního týdne manželství nese motto O manželství a dětech.",
    body: "<p>Každý rok se v rámci tohoto týdne koná více než sto akcí po celé republice. Organizátoři v době lockdownu nabízejí také sérii webinářů pro manželské páry.</p>",
    attachments: [
      { label: "Tisková zpráva", file: `${UPLOADS}/narodni-tyden-manzelstvi-2021-zprava.pdf`, size: 1009692 },
    ],
    links: [{ label: "Národní týden manželství", href: "https://www.tydenmanzelstvi.cz/" }],
  },
  {
    id: "poselstvi-papeze-den-nemocnych-2021",
    title: "Poselství papeže Františka ke Světovému dni nemocných",
    start: "2021-02-11",
    text: "Přečtěte si poselství papeže Františka k 29. Světovému dni nemocných.",
    links: [
      {
        label: "Poselství na webu cirkev.cz",
        href: "https://www.cirkev.cz/cs/aktuality/210121poselstvi-svateho-otce-frantiska-k-29-svetovemu-dni-nemocnych",
      },
    ],
  },
  {
    id: "daruj-lasku-z-kufru-auta-2021",
    title: "Daruj lásku z kufru auta",
    start: "2021-02-13",
    end: "2021-02-14",
    place: "Kuřim, u kostela sv. Maří Magdalény",
    text: "Prodej ručně vyráběných výrobků ke svátku sv. Valentýna, jehož výtěžek půjde na opravu fary.",
    body:
      "<p>Kufr auta se u kuřimského kostela otevře v sobotu <strong>13. 2.</strong> od 14:00 do 15:00 a v neděli <strong>14. 2.</strong> od 9:00 do 9:30, od 10:15 do 10:45 a od 14:00 do 15:00.</p>" +
      "<p>Bližší informace podá Lucie Sádlíková.</p>",
    poster: { src: `${UPLOADS}/daruj-lasku-z-kufru-auta-2021-plakat.webp`, alt: "Plakát: Daruj lásku z kufru auta" },
    attachments: [
      { label: "Plakát", file: `${UPLOADS}/daruj-lasku-z-kufru-auta-2021-plakat.pdf`, size: 430221 },
      { label: "Foto výrobků", file: `${UPLOADS}/daruj-lasku-z-kufru-auta-2021-vyrobky.jpg`, size: 74288 },
    ],
  },
  {
    id: "mimoradne-katecheze-2021",
    title: "Mimořádné katecheze pro děti",
    start: "2021-02-21",
    text: "V době, kdy se děti nemohly scházet, pro ně byly každý týden připravovány příběhy a úkoly.",
  },
  {
    id: "adoracni-odpoledne-2021",
    title: "Adorační odpoledne",
    start: "2021-02-28",
    time: "13:00–20:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Adorace v kuřimském kostele s rozpisem adorujících po půlhodinách.",
    body: "<p>Zapisujte se prosím do rozpisu, aby byl v kostele po celou dobu někdo přítomen. Příležitost ke svaté zpovědi bude při adoraci od 14 do 16 hodin.</p>",
  },
  {
    id: "krizova-cesta-prirodou-s-obrazy-2021",
    title: "Křížová cesta přírodou s obrazy",
    start: "2021-03-05",
    end: "2021-04-05",
    place: "Moravské Knínice",
    text: "Zveme na křížovou cestu lesní stezkou z Mezihoří na Strážnou s obrazy akademického malíře Milivoje Husáka.",
    body: "<p>Křížová cesta začíná u první lípy na cestě k „Výletišti“ v Mezihoří a pokračuje přes potok Kuřimku po lesní stezce až na kopec Strážná. Obrazy vytvořil akademický malíř Milivoj Husák z Lelekovic v letech 1993–1994.</p>",
    poster: {
      src: `${UPLOADS}/krizova-cesta-prirodou-s-obrazy-2021-plakat.webp`,
      alt: "Plakát: Křížová cesta přírodou s obrazy v Moravských Knínicích",
    },
    attachments: [
      { label: "Plakát", file: `${UPLOADS}/krizova-cesta-prirodou-s-obrazy-2021-plakat.pdf`, size: 126582 },
      { label: "Mapka trasy", file: `${UPLOADS}/krizova-cesta-prirodou-s-obrazy-2021-mapka.pdf`, size: 321003 },
    ],
  },
  {
    id: "sms-pro-vranov-2021",
    title: "I jedna SMS může pomoci Vranovu",
    start: "2021-03-15",
    end: "2021-03-31",
    text: "Poutní kostel Narození Panny Marie ve Vranově soutěží o Nejlépe opravenou kulturní památku Jihomoravského kraje. Podpořte ho jednou SMS.",
    body: "<p>Hlasovat lze od 15. do 31. března 2021 jednou SMS z jednoho telefonního čísla za cenu běžného tarifu. Pošlete SMS ve tvaru <strong>HLA PAMATKY 43</strong> na číslo <strong>736 301 599</strong>. Případnou finanční odměnu chce farnost využít k dalším opravám památky.</p>",
    poster: {
      src: `${UPLOADS}/sms-pro-vranov-2021-plakat.webp`,
      alt: "Plakát: I jedna SMS může pomoci v péči o poutní místo Vranov u Brna",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/sms-pro-vranov-2021-plakat.pdf`, size: 5856302 }],
    links: [
      {
        label: "Výzva na webu poutního místa",
        href: "https://www.dc-vranov.cz/index.php/894-153-213-2021-podporte-jednou-sms-vranovsky-kostel-v-soutezi-qnejlepe-opravena-kulturni-pamatka-jihomoravskeho-kraje-v-roce-2020q",
      },
      { label: "Soutěž na webu Jihomoravského kraje", href: "https://www.kr-jihomoravsky.cz/pamatky/index.php" },
    ],
  },
  {
    id: "kvetna-nedele-2021",
    title: "Květná neděle",
    start: "2021-03-28",
    time: "9:30",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Mši svatou vysíláme živě na YouTube. Odpoledne je výstav Nejsvětější svátosti a příležitost ke svaté zpovědi.",
    program: [
      { time: "9:30", title: "Mše svatá", note: "živě na YouTube" },
      { time: "13:30–19:00", title: "Výstav Nejsvětější svátosti" },
      { time: "14:00–16:00", title: "Svatá zpověď", note: "od 14 do 15 hodin i s cizím zpovědníkem" },
    ],
    links: [{ label: "Záznam na YouTube", href: "https://youtu.be/IK2dNVg2Gto" }],
  },
  {
    id: "reportaz-hospic-sv-alzbety-2021",
    title: "Reportáž o Hospici sv. Alžběty",
    start: "2021-03-31",
    time: "20:15",
    text: "Radio Proglas odvysílá v pořadu Studio Brno reportáž o projektu rekonstrukce a dostavby Hospice sv. Alžběty.",
    links: [
      {
        label: "Projekt rekonstrukce a dostavby",
        href: "https://www.hospicbrno.cz/gallery/projekt-rekonstrukce-a-dostavby/",
      },
    ],
  },
  {
    id: "zehnani-pokrmu-2021",
    title: "Žehnání velikonočních pokrmů",
    start: "2021-04-04",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Pokrmy můžete přinést k požehnání na Boží hod velikonoční po každé mši svaté. Domácí žehnací modlitbu najdete v příloze.",
    attachments: [{ label: "Žehnací modlitba", file: `${UPLOADS}/zehnani-pokrmu-2021-modlitba.pdf`, size: 51584 }],
  },
  {
    id: "noc-kostelu-2021",
    title: "Noc kostelů",
    start: "2021-05-28",
    time: "19:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Naše farnost se do Noci kostelů zapojuje virtuální prohlídkou kuřimského kostela a zpěvem chrámového sboru.",
    poster: { src: `${UPLOADS}/noc-kostelu-2021-plakat.webp`, alt: "Plakát: Noc kostelů 2021 v kuřimském kostele" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/noc-kostelu-2021-plakat.pdf`, size: 2169663 }],
    links: [{ label: "Noc kostelů", href: "https://www.nockostelu.cz/" }],
  },
  {
    id: "farni-den-2021",
    title: "Farní den",
    start: "2021-06-05",
    time: "15:00",
    place: "Kuřim, areál za farou",
    text: "Farní odpoledne s hrami pro děti, prezentací fotografií o naší farnosti a písničkami u táboráku.",
    body: "<p>Přijďte posedět, povykládat a pobýt s námi. Občerstvení je zajištěno.</p>",
  },
  {
    id: "life-of-cellos-live-2021",
    title: "Life of Cellos Live",
    start: "2021-06-06",
    time: "17:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Tradiční jarní koncert violoncellistů Filharmonie Brno, po dlouhé době jeden z prvních před živým publikem.",
    body: "<p>Zazní Bachovy suity pro violoncello, Haydnův Koncert D dur a Popperova Koncertní polonéza. Koncert pod uměleckým vedením koncertního mistra Pavla Šabackého je věnován všem zdravotníkům jako poděkování za jejich obětavou práci. Vstupné dobrovolné.</p>",
    poster: { src: `${UPLOADS}/life-of-cellos-live-2021-plakat.webp`, alt: "Plakát: Life of Cellos Live 6. 6. 2021" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/life-of-cellos-live-2021-plakat.pdf`, size: 289408 }],
  },
  {
    id: "hody-2021",
    title: "Hody v obcích farnosti",
    start: "2021-07-17",
    end: "2021-07-25",
    place: "Moravské Knínice, Kuřim a Jinačovice",
    text: "Přijměte pozvání na hody v Moravských Knínicích, v Kuřimi a v Jinačovicích.",
    program: [
      { time: "17.–18. 7.", title: "Markétské hody v Moravských Knínicích" },
      { time: "23.–25. 7.", title: "Mladé hody a den obce v Jinačovicích" },
      { time: "24. 7.", title: "Babské hody v Kuřimi", note: "areál ZŠ Komenského" },
    ],
    poster: {
      src: `${UPLOADS}/hody-2021-plakat-kninice.webp`,
      alt: "Plakát: Markétské hody v Moravských Knínicích 17.–18. 7. 2021",
    },
    attachments: [
      {
        label: "Plakát: Markétské hody v Moravských Knínicích",
        file: `${UPLOADS}/hody-2021-plakat-kninice.pdf`,
        size: 2261629,
      },
      { label: "Plakát: Babské hody v Kuřimi", file: `${UPLOADS}/hody-2021-plakat-kurim.pdf`, size: 1165436 },
      { label: "Plakát: Mladé hody v Jinačovicích", file: `${UPLOADS}/hody-2021-plakat-jinacovice.pdf`, size: 2220190 },
    ],
  },
  {
    id: "farni-tabor-2021",
    title: "Farní tábor 2021",
    start: "2021-08-14",
    end: "2021-08-21",
    text: "Další ročník letního farního tábora pro děti.",
  },
  {
    id: "pochod-po-stopach-p-sevcika-2021",
    title: "Pochod po stopách P. Ševčíka",
    start: "2021-08-14",
    time: "9:00",
    place: "Boskovice, Modrá věž",
    text: "XVII. ročník pochodu pro turisty, cyklisty a všechny, kdo rádi putují krajinou. Start je od Modré věže v Boskovicích.",
    body: "<p>Pěší trasa vede přes kapli sv. Otýlie, Bačov a Ohradu do Vísek, cyklisté si mohou vybrat trasu od 10 do 50 km. Startovné 20 Kč, děti a senioři zdarma.</p>",
    poster: {
      src: `${UPLOADS}/pochod-po-stopach-p-sevcika-2021-plakat.webp`,
      alt: "Plakát: XVII. ročník pochodu po stopách P. Ševčíka",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/pochod-po-stopach-p-sevcika-2021-plakat.pdf`, size: 464084 }],
  },
  {
    id: "beneficni-koncert-boskovice-2021",
    title: "Benefiční koncert na podporu jižní Moravy",
    start: "2021-08-15",
    time: "17:00",
    place: "Boskovice, za Muzeem regionu Boskovicka",
    text: "Vystoupí sbor BaczBand a výtěžek bude věnován na obnovu postižené jižní Moravy.",
    poster: {
      src: `${UPLOADS}/beneficni-koncert-boskovice-2021-plakat.webp`,
      alt: "Plakát: Benefiční koncert BaczBand na podporu jižní Moravy",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/beneficni-koncert-boskovice-2021-plakat.pdf`, size: 740249 }],
  },
  {
    id: "marianske-pouti-2021",
    title: "Mariánské poutě",
    start: "2021-08-29",
    end: "2021-09-26",
    place: "Vranov u Brna a Žarošice",
    text: "Přijměte pozvání na pouť Sedmiradostnou cestou, cyklopouť a pěší pouť na Vranov a na Zlatou sobotu v Žarošicích.",
    program: [
      {
        time: "29. 8. 7:15",
        title: "Pouť Sedmiradostnou cestou Česká – Lelekovice – Vranov",
        note: "mše svatá v 11:00",
      },
      {
        time: "5. 9. 12:30",
        title: "Cyklopouť z Kuřimi na Vranov",
        note: "z parku na ulici Havlíčkova, mše svatá v 15:00",
      },
      { time: "11. 9.", title: "Zlatá sobota v Žarošicích", note: "s krojovaným procesím" },
      {
        time: "26. 9. 7:30",
        title: "Pěší pouť Moravské Knínice – Kuřim – Vranov",
        note: "s krojovaným procesím, mše svatá v 11:00",
      },
    ],
    poster: {
      src: `${UPLOADS}/marianske-pouti-2021-plakat-pesi-pout.webp`,
      alt: "Plakát: Tradiční pěší pouť na Vranov 26. září 2021",
    },
    attachments: [
      {
        label: "Plakát: Pěší pouť na Vranov",
        file: `${UPLOADS}/marianske-pouti-2021-plakat-pesi-pout.pdf`,
        size: 2280433,
      },
      {
        label: "Plakát: Sedmiradostná cesta",
        file: `${UPLOADS}/marianske-pouti-2021-plakat-sedmiradostna-cesta.pdf`,
        size: 327534,
      },
      {
        label: "Plakát: Cyklopouť na Vranov",
        file: `${UPLOADS}/marianske-pouti-2021-plakat-cyklopout.pdf`,
        size: 634558,
      },
      {
        label: "Plakát: Zlatá sobota v Žarošicích",
        file: `${UPLOADS}/marianske-pouti-2021-plakat-zlata-sobota.pdf`,
        size: 1243156,
      },
    ],
  },
  {
    id: "varhanni-koncert-kninice-2021",
    title: "Varhanní koncert v Moravských Knínicích",
    start: "2021-09-12",
    time: "17:00",
    place: "Moravské Knínice, kostel sv. Markéty",
    text: "Koncert Varhanní cesty po starém kontinentu: Kamila Dubská (varhany) a Martin Flašar (housle).",
    body: "<p>Koncert Brněnského varhanního festivalu pořádají Římskokatolická farnost Kuřim a Klub moravských skladatelů. Zazní skladby Corelliho, Purcella, Frobergera a Vivaldiho. Vstupné dobrovolné.</p>",
    poster: {
      src: `${UPLOADS}/varhanni-koncert-kninice-2021-plakat.webp`,
      alt: "Plakát: Varhanní cesty po starém kontinentu, 12. září 2021",
    },
    attachments: [
      { label: "Plakát", file: `${UPLOADS}/varhanni-koncert-kninice-2021-plakat.pdf`, size: 189085 },
      { label: "Program koncertu", file: `${UPLOADS}/varhanni-koncert-kninice-2021-program.pdf`, size: 31440 },
    ],
  },
  {
    id: "medovy-den-2021",
    title: "Farní stánek na Medovém dni",
    start: "2021-09-12",
    time: "10:00–18:00",
    place: "Kuřim, areál ZŠ Komenského",
    text: "Na Medovém dni bude mít naše farnost svůj stánek. Zisk z prodeje půjde na stavbu na faře.",
    body: "<p>Těšit se můžete na domácí meduňkovou limonádu s medem, hotdogy, párky v rohlíku a medové perníčky. Zakoupit si můžete také drobné dekorační předměty.</p>",
    program: [
      { time: "10:00", title: "Medový trh" },
      { time: "11:00", title: "Divadlo Kejkle" },
      { time: "12:30", title: "Aritmic band" },
      { time: "14:00", title: "CM Kyničan" },
      { time: "16:00", title: "Bombarďák" },
      { time: "17:00", title: "Pavel Helan" },
    ],
    poster: { src: `${UPLOADS}/medovy-den-2021-plakat.webp`, alt: "Plakát: Medový den 2021 v Kuřimi" },
    attachments: [
      { label: "Plakát", file: `${UPLOADS}/medovy-den-2021-plakat.pdf`, size: 394770 },
      { label: "Program", file: `${UPLOADS}/medovy-den-2021-program.pdf`, size: 465073 },
    ],
  },
  {
    id: "den-narodnostnich-mensin-2021",
    title: "Den národnostních menšin",
    start: "2021-09-19",
    time: "14:00",
    place: "Kuřim, zámek",
    text: "Srdečně zveme na Den národnostních menšin na kuřimském zámku.",
  },
  {
    id: "hody-ceska-2021",
    title: "Hody v České",
    start: "2021-10-01",
    end: "2021-10-03",
    place: "Česká",
    text: "Přijměte pozvání na tradiční hody do České.",
    poster: { src: `${UPLOADS}/hody-ceska-2021-plakat.webp`, alt: "Plakát: Hody v České 1.–3. října 2021" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/hody-ceska-2021-plakat.pdf`, size: 9250764 }],
  },
  {
    id: "koncert-duchovni-hudby-2021",
    title: "Koncert duchovní hudby",
    start: "2021-10-03",
    time: "18:00",
    text: "Sbory Dej Nám Akord a K-dur zazpívají duchovní skladby a spirituály.",
  },
  {
    id: "adoracni-den-2021",
    title: "Adorační den farnosti",
    start: "2021-10-12",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Adorační den naší farnosti. Zapište se pod kůrem, kdy budete v kostele držet adorační stráž.",
    body: "<p>Je potřeba, aby byli v kostele stále přítomni alespoň dva lidé. Eucharistická adorace je zdrojem velkých milostí a požehnání nejen pro ty, kdo před Pánem Ježíšem prodlévají, ale i pro všechny, které Bohu předkládáme, a pro celou církev.</p>",
  },
  {
    id: "respiratory-v-kostele-2021",
    title: "Respirátory v kostele",
    start: "2021-10-25",
    text: "Od pondělí 25. října 2021 je ve vnitřních prostorách povinnost nosit respirátor.",
    body: "<p>Respirátor je povinný ve vnitřních prostorách staveb, kde jsou přítomny alespoň dvě osoby vzdálené méně než 1,5 metru, pokud nejde o členy domácnosti. Výjimku mají celebrant, kazatel a ti, kdo přednášejí čtení, přímluvy a modlitby. Žalmisté a zpěváci nemusí mít respirátor po dobu zpěvu.</p>",
  },
  {
    id: "odpustky-za-zemrele-2021",
    title: "Odpustky za zemřelé po celý listopad",
    start: "2021-11-01",
    end: "2021-11-30",
    text: "Kvůli pandemii je možné získat plnomocné odpustky za zemřelé nejen během oktávu Všech svatých, ale po celý listopad.",
    body: "<p>Dekret v tomto smyslu oznámila Apoštolská penitenciárie.</p>",
    links: [
      {
        label: "Zpráva na webu cirkev.cz",
        href: "https://www.cirkev.cz/cs/aktuality/211029odpustky-za-zemrele-rozsireny-na-cely-listopad",
      },
    ],
  },
  {
    id: "petrklic-2021-1",
    title: "Petrklíč 1/2021",
    start: "2021-11-07",
    text: "Právě vyšlo první letošní vydání farního časopisu Petrklíč.",
    attachments: [{ label: "Petrklíč 1/2021", file: "/uploads/petrklic/2021-1/petrklic-2021-1.pdf", size: 10829180 }],
  },
  {
    id: "novena-ke-sv-josefovi-2021",
    title: "Novéna ke sv. Josefovi",
    start: "2021-11-10",
    text: "Rok sv. Josefa končí 8. prosince 2021. Devítidenní novénu k svatému Josefovi si můžete kdykoli poslechnout.",
    links: [
      {
        label: "Novéna na YouTube",
        href: "https://www.youtube.com/results?search_query=nov%C3%A9na+k+svat%C3%A9mu+josefovi",
      },
    ],
  },
  {
    id: "martinske-hody-2021",
    title: "Martinské hody",
    start: "2021-11-13",
    end: "2021-11-14",
    place: "Moravské Knínice",
    text: "Přijměte pozvání na Martinské hody v Moravských Knínicích.",
    poster: {
      src: `${UPLOADS}/martinske-hody-2021-plakat.webp`,
      alt: "Plakát: Martinské hody v Moravských Knínicích 13.–14. 11. 2021",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/martinske-hody-2021-plakat.pdf`, size: 377032 }],
  },
  {
    id: "svata-anezka-porta-coeli-2021",
    title: "Výročí kanonizace svaté Anežky České",
    start: "2021-11-14",
    time: "10:15",
    place: "Předklášteří, bazilika Porta Coeli",
    text: "Oslava 32. výročí kanonizace svaté Anežky České mší svatou v bazilice Nanebevzetí Panny Marie kláštera Porta Coeli.",
    body: "<p>Mši svatou bude sloužit P. PharmDr. Mgr. Josef Šedivý, O.Cr. Zvou farnosti Tišnov a Předklášteří.</p>",
    poster: {
      src: `${UPLOADS}/svata-anezka-porta-coeli-2021-plakat.webp`,
      alt: "Plakát: 32. výročí kanonizace svaté Anežky České v Porta Coeli",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/svata-anezka-porta-coeli-2021-plakat.pdf`, size: 2555209 }],
  },
  {
    id: "charitativni-beh-a-jarmark-2021",
    title: "Charitativní běh a jarmark",
    start: "2021-11-20",
    end: "2021-11-21",
    place: "Lelekovice a Česká",
    text: "Běh a 21. ročník charitativního jarmarku v České na pomoc dětem v Jižním Súdánu.",
    body: "<p>Jarmark se kvůli pandemii koná ve venkovních prostorách sokolovny v České. Prodej zboží pak pokračuje až do konce roku online a na sociálních sítích. Výtěžek podpoří projekt pomoci dětem v Jižním Súdánu cestou Papežských misijních děl.</p>",
    program: [
      {
        time: "20. 11. 10:30",
        title: "Charitativní běh",
        note: "start u vodojemu Na Pasekách v Lelekovicích, prezentace od 10:00",
      },
      { time: "21. 11. 13:30–16:30", title: "Charitativní jarmark", note: "dvůr sokolovny v České" },
    ],
    poster: {
      src: `${UPLOADS}/charitativni-beh-a-jarmark-2021-plakat-jarmark.webp`,
      alt: "Plakát: 21. tradiční farní charitativní jarmark v České",
    },
    attachments: [
      {
        label: "Plakát: Charitativní jarmark",
        file: `${UPLOADS}/charitativni-beh-a-jarmark-2021-plakat-jarmark.pdf`,
        size: 364271,
      },
      {
        label: "Plakát: Charitativní běh",
        file: `${UPLOADS}/charitativni-beh-a-jarmark-2021-plakat-beh.pdf`,
        size: 128233,
      },
    ],
    links: [{ label: "Charitativní jarmark", href: "https://www.dc-vranov.cz/index.php/charitativni-jarmark" }],
  },
  {
    id: "film-o-sv-anezce-2021",
    title: "Film o sv. Anežce České",
    start: "2021-11-21",
    time: "10:30",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Promítání dokumentárního filmu o sv. Anežce České po mši svaté.",
    body: "<p>Promítání pořádá senátorka Jaromíra Vítková společně s farností Kuřim.</p>",
    poster: {
      src: `${UPLOADS}/film-o-sv-anezce-2021-pozvanka.webp`,
      alt: "Pozvánka: promítání dokumentárního filmu o sv. Anežce České",
    },
    attachments: [{ label: "Pozvánka", file: `${UPLOADS}/film-o-sv-anezce-2021-pozvanka.jpg`, size: 1902520 }],
  },
  {
    id: "cervena-streda-2021",
    title: "Červená středa",
    start: "2021-11-24",
    time: "19:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Společenství mladých zve na mši svatou za pronásledované pro víru s hudebním doprovodem. Kostel bude nasvícen červeně.",
    body: "<p>Po mši následuje výstava s možností modlitby až do 21 hodin.</p>",
    poster: { src: `${UPLOADS}/cervena-streda-2021-plakat.webp`, alt: "Plakát: Červená středa 24. listopadu 2021" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/cervena-streda-2021-plakat.pdf`, size: 615368 }],
    links: [{ label: "Červená středa", href: "https://www.cervenastreda.cz/" }],
  },
  {
    id: "vecer-boziho-milosrdenstvi-2021",
    title: "Večer Božího milosrdenství",
    start: "2021-11-27",
    time: "18:00",
    place: "Brno-Žebětín, kostel sv. Bartoloměje",
    text: "Večer Božího milosrdenství pod záštitou komunity Emmanuel.",
    poster: {
      src: `${UPLOADS}/vecer-boziho-milosrdenstvi-2021-pozvanka.webp`,
      alt: "Pozvánka: Večer Božího milosrdenství v Brně-Žebětíně",
    },
    attachments: [{ label: "Pozvánka", file: `${UPLOADS}/vecer-boziho-milosrdenstvi-2021-pozvanka.pdf`, size: 678797 }],
  },
  {
    id: "katecheze-advent-vanoce-2021",
    title: "Katecheze k adventu a Vánocům",
    start: "2021-11-27",
    text: "Kdo je nemocný nebo nemůže přijít do kostela, může si prohlédnout loňské katecheze pro děti k adventu a Vánocům.",
  },
  {
    id: "adventni-koncert-bara-basikova-2021",
    title: "Adventní koncert Báry Basikové",
    start: "2021-12-06",
    time: "17:30",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Tradiční adventní koncert: vystoupí Bára Basiková a skupina Shot-C.",
    body: "<p>Koncert pořádají ZŠ Jungmannova, Římskokatolická farnost Kuřim a Společenské a kulturní centrum Kuřim. Vstupenky jsou v předprodeji na ZŠ Jungmannova a ve Společenském a kulturním centru Kuřim.</p>",
    price: "300 Kč v předprodeji, 350 Kč na místě",
    poster: {
      src: `${UPLOADS}/adventni-koncert-bara-basikova-2021-plakat.webp`,
      alt: "Plakát: Bára Basiková a Shot-C, 6. 12. 2021",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/adventni-koncert-bara-basikova-2021-plakat.pdf`, size: 220385 }],
  },
  {
    id: "koncert-ucednici-2021",
    title: "Koncert skupiny Učedníci (zrušeno)",
    start: "2021-12-11",
    time: "15:00",
    place: "Boskovice, kino Panorama",
    text: "Koncert byl zrušen. Charitativní koncert skupiny Učedníci, zaměřené na křesťanský folk.",
    body: "<p>Výtěžek z koncertu měl podpořit salesiánskou misii v Bulharsku, kterou vykonává P. Petr Cvrkal.</p>",
    label: "Zrušeno",
    poster: {
      src: `${UPLOADS}/koncert-ucednici-2021-plakat.webp`,
      alt: "Plakát: Charitativní koncert skupiny Učedníci 11. 12. 2021",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/koncert-ucednici-2021-plakat.jpg`, size: 554815 }],
  },
  {
    id: "uklid-kostela-2021",
    title: "Vánoční úklid kostela",
    start: "2021-12-18",
    time: "8:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Vánoční zdobení a úklid kuřimského kostela před svátky. Předem děkujeme za vaši pomoc.",
  },
  {
    id: "petrklic-2021-2",
    title: "Petrklíč 2/2021",
    start: "2021-12-19",
    text: "Právě vyšlo nové vydání farního časopisu Petrklíč.",
    attachments: [{ label: "Petrklíč 2/2021", file: "/uploads/petrklic/2021-2/petrklic-2021-2.pdf", size: 7924318 }],
  },
  {
    id: "zpivani-chramoveho-sboru-vanoce-2021",
    title: "Chrámový sbor o Vánocích",
    start: "2021-12-24",
    end: "2021-12-25",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Mše svaté na Štědrý den a na slavnost Narození Páně doprovodí chrámový sbor.",
    program: [
      { time: "24. 12. 22:00", title: "Noční mše svatá na Štědrý den" },
      { time: "25. 12. 9:30", title: "Mše svatá o slavnosti Narození Páně" },
    ],
  },
];
