import type { NewsEvent } from "@/content/types/news";
import { UPLOADS } from "./uploads";

export const events2023: NewsEvent[] = [
  {
    id: "trikralovy-koncert-zus-2023",
    title: "Tříkrálový koncert ZUŠ Kuřim",
    start: "2023-01-11",
    time: "18:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Základní umělecká škola Kuřim zve na tříkrálový koncert ve farním kostele.",
    poster: {
      src: `${UPLOADS}/trikralovy-koncert-zus-2023-plakat.webp`,
      alt: "Plakát: Tříkrálový koncert ZUŠ Kuřim 11. 1. 2023",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/trikralovy-koncert-zus-2023-plakat.pdf`, size: 925966 }],
  },
  {
    id: "tyden-modliteb-za-jednotu-krestanu-2023",
    title: "Týden modliteb za jednotu křesťanů",
    start: "2023-01-18",
    end: "2023-01-25",
    text: "Letošní týden modliteb za jednotu křesťanů má motto z proroka Izaiáše: „Učte se činit dobro, hledejte právo“ (Iz 1,17).",
    poster: {
      src: `${UPLOADS}/tyden-modliteb-za-jednotu-krestanu-2023-plakat.webp`,
      alt: "Plakát: Týden modliteb za jednotu křesťanů 18.–25. ledna 2023",
    },
    attachments: [
      { label: "Plakát", file: `${UPLOADS}/tyden-modliteb-za-jednotu-krestanu-2023-plakat.pdf`, size: 2908825 },
    ],
  },
  {
    id: "24-hodin-pro-pana-2023",
    title: "24 hodin pro Pána v Tišnově",
    start: "2023-03-17",
    end: "2023-03-18",
    place: "Tišnov, kostel sv. Václava",
    text: "Děkanství Tišnov zve do kostela sv. Václava k modlitbě, adoraci a svátosti smíření.",
    body: "<p>Ke svátosti smíření nebo k rozhovoru s knězem je možné přijít v pátek od 17:00 do 17:50 a od 19:00 do 21:00 a v sobotu od 19:00 do 21:00.</p>",
    program: [
      { time: "pá 17:30", title: "Růženec" },
      { time: "pá 18:00", title: "Mše svatá" },
      { time: "pá 19:00 – so 21:00", title: "Adorace" },
    ],
    poster: {
      src: `${UPLOADS}/24-hodin-pro-pana-2023-plakat.webp`,
      alt: "Plakát: 24 hodin pro Pána v kostele sv. Václava v Tišnově",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/24-hodin-pro-pana-2023-plakat.pdf`, size: 1701151 }],
  },
  {
    id: "duchovni-obnova-pro-zeny-2023",
    title: "Postní duchovní obnova pro ženy",
    start: "2023-03-17",
    end: "2023-03-18",
    place: "Brno-Husovice, fara",
    text: "Postní duchovní obnova pro ženy „Žena, nositelka Boží krásy“ s Pavlou Cenkovou na faře v Husovicích.",
    poster: {
      src: `${UPLOADS}/duchovni-obnova-pro-zeny-2023-pozvanka.webp`,
      alt: "Pozvánka: Žena, nositelka Boží krásy – postní duchovní obnova pro ženy",
    },
    attachments: [{ label: "Pozvánka", file: `${UPLOADS}/duchovni-obnova-pro-zeny-2023-pozvanka.jpg`, size: 538309 }],
  },
  {
    id: "velikonoce-2023",
    title: "Velikonoce 2023",
    start: "2023-03-30",
    end: "2023-04-10",
    place: "Kuřim a Moravské Knínice",
    text: "Pořad velikonočních bohoslužeb a zpovídání v Kuřimi a v Moravských Knínicích.",
    body: "<p>Pašije se zpívají na Květnou neděli (2. 4.) v 8:00 a na Velký pátek (7. 4.) při obřadech v 18:00. Chrámový sbor zpívá při vigilii na Bílou sobotu (8. 4.) ve 20:00 a o slavnosti Zmrtvýchvstání Páně (9. 4.) v 9:30.</p>",
    attachments: [
      { label: "Pořad bohoslužeb a zpovídání", file: `${UPLOADS}/velikonoce-2023-porad-bohosluzeb.pdf`, size: 78593 },
    ],
  },
  {
    id: "petrklic-2023-1",
    title: "Petrklíč 1/2023",
    start: "2023-03-31",
    text: "Právě vyšlo nové vydání farního časopisu Petrklíč.",
    attachments: [{ label: "Petrklíč 1/2023", file: "/uploads/petrklic/2023-1/petrklic-2023-1.pdf", size: 5690248 }],
  },
  {
    id: "vecer-boziho-milosrdenstvi-2023",
    title: "Večer Božího milosrdenství",
    start: "2023-04-15",
    time: "16:30",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Večer Božího milosrdenství s komunitou Emmanuel: mše svatá, chvály, přímluvná modlitba, žehnání a adorace.",
    poster: {
      src: `${UPLOADS}/vecer-boziho-milosrdenstvi-2023-plakat.webp`,
      alt: "Plakát: Večer Božího milosrdenství 15. 4. 2023",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/vecer-boziho-milosrdenstvi-2023-plakat.pdf`, size: 130362 }],
  },
  {
    id: "koncert-listovej-2023",
    title: "Koncert skupiny Listověj",
    start: "2023-04-23",
    time: "18:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Skupina Listověj uvede vlastní písně a zhudebněné básně Jana Zahradníčka a Bohuslava Reynka.",
    body: "<p>Písně vyprávějí o duchovně silných místech v krajině, o zaniklých a znovu obnovených kostelích a o obětech komunistického režimu. Hrají Jiří Nohel (kytara, zpěv), Markéta Štouračová (flétny, klávesy, zpěv) a Aleš Tomek (housle, zpěv).</p>",
    price: "dobrovolné vstupné",
    poster: {
      src: `${UPLOADS}/koncert-listovej-2023-pozvanka.webp`,
      alt: "Pozvánka: koncert skupiny Listověj v Kuřimi",
    },
    attachments: [{ label: "Pozvánka", file: `${UPLOADS}/koncert-listovej-2023-pozvanka.pdf`, size: 631156 }],
    links: [{ label: "Listověj", href: "https://www.listovej.cz/" }],
  },
  {
    id: "diecezni-setkani-mladeze-2023",
    title: "Diecézní setkání mládeže",
    start: "2023-05-13",
    place: "Žarošice",
    text: "Diecézní setkání mládeže s brněnským biskupem Pavlem Konzbulem v Žarošicích.",
    poster: {
      src: `${UPLOADS}/diecezni-setkani-mladeze-2023-plakat.webp`,
      alt: "Plakát: Diecézní setkání mládeže 13. 5. Žarošice",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/diecezni-setkani-mladeze-2023-plakat.jpg`, size: 48645 }],
    links: [{ label: "Diecézní setkání mládeže", href: "https://mladez.biskupstvi.cz/dsm" }],
  },
  {
    id: "rodinny-den-2023",
    title: "Rodinný den",
    start: "2023-05-21",
    time: "14:00",
    place: "Kuřim, areál zámku",
    text: "Zveme vás na Rodinný den do areálu kuřimského zámku a na prostranství kolem kostela sv. Maří Magdalény.",
    body: "<p>Po celou dobu akce budou probíhat soutěže a hry, malování na obličej a skákací hrady pro malé i větší. Občerstvení zajištěno, vstupné dobrovolné.</p>",
    program: [
      { time: "14:00", title: "Zahájení" },
      { time: "14:30", title: "Vystoupení ZUŠ Kuřim" },
      { time: "15:15", title: "Skotačení s klaunem" },
      { time: "16:00", title: "Hudební okénko s Petrem a Pavlem" },
      { time: "16:45", title: "Žonglování s klaunem" },
    ],
    poster: {
      src: `${UPLOADS}/rodinny-den-2023-plakat.webp`,
      alt: "Plakát: Rodinný den v areálu kuřimského zámku 21. května 2023",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/rodinny-den-2023-plakat.pdf`, size: 1069183 }],
  },
  {
    id: "noc-kostelu-2023",
    title: "Noc kostelů",
    start: "2023-06-02",
    time: "18:30",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Noc kostelů v kuřimském kostele: zpěvy dětské scholy, duchovní písně neduchovních autorů a večer s komunitou Emmanuel.",
    program: [
      { time: "18:30", title: "Zpěvy kuřimské dětské scholy" },
      {
        time: "19:30",
        title: "Duchovní písně neduchovních autorů",
        note: "kapela Church Knights s pěveckým sborem, host Hana Ulrychová",
      },
      { time: "21:00", title: "Kdo zpívá, dvakrát se modlí", note: "hudba komunity Emmanuel a tichá adorace" },
    ],
    poster: { src: `${UPLOADS}/noc-kostelu-2023-plakat.webp`, alt: "Plakát: Noc kostelů v Kuřimi 2. 6. 2023" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/noc-kostelu-2023-plakat.png`, size: 171495 }],
    links: [{ label: "Noc kostelů", href: "https://www.nockostelu.cz/" }],
  },
  {
    id: "koncert-coelum-et-terra-2023",
    title: "Koncert Coelum et terra laetentur alleluia",
    start: "2023-06-04",
    time: "17:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Brněnský ekumenický sbor a komorní orchestr barokních nástrojů uvedou díla barokních a renesančních skladatelů.",
    price: "dobrovolné vstupné",
    poster: {
      src: `${UPLOADS}/koncert-coelum-et-terra-2023-plakat.webp`,
      alt: "Plakát: koncert duchovní hudby Coelum et terra laetentur alleluia",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/koncert-coelum-et-terra-2023-plakat.pdf`, size: 312907 }],
  },
  {
    id: "farni-den-2023",
    title: "Farní den",
    start: "2023-06-10",
    time: "15:00",
    place: "Kuřim, farní dvorek a orlovna",
    text: "Farní den s mší svatou na farním dvorku a bohatým programem pro děti i dospělé.",
    body: "<p>Celé odpoledne se hraje rodinná hra v celém areálu a turnaj ve stolním fotbale, večer posezení u ohně s živou hudbou a špekáčky. Drobné občerstvení, které přinesete, je vítáno.</p>",
    program: [
      { time: "15:00", title: "Mše svatá na farním dvorku" },
      { time: "15:45", title: "Zahájení turnaje ve stolním fotbale a rodinné hry" },
      { time: "16:00", title: "Přednáška o léčivých bylinách", note: "Marek Motyčka" },
      { time: "17:00", title: "Hudební překvapení", note: "Ukulele Band" },
      { time: "17:30", title: "Pomáháme psím srdcem", note: "asistenční pes" },
    ],
    poster: { src: `${UPLOADS}/farni-den-2023-program.webp`, alt: "Plakát: Farní den Kuřim 10. 6. 2023" },
    attachments: [{ label: "Program", file: `${UPLOADS}/farni-den-2023-program.pdf`, size: 11854 }],
  },
  {
    id: "petrklic-2023-2",
    title: "Petrklíč 2/2023",
    start: "2023-06-25",
    text: "Právě vyšlo nové vydání farního časopisu Petrklíč.",
    attachments: [{ label: "Petrklíč 2/2023", file: "/uploads/petrklic/2023-2/petrklic-2023-2.pdf", size: 20273811 }],
  },
  {
    id: "hody-2023",
    title: "Hody v obcích farnosti",
    start: "2023-07-14",
    end: "2023-07-23",
    place: "Moravské Knínice, Jinačovice a Kuřim",
    text: "Přijměte pozvání na Markétské hody v Moravských Knínicích, Mladé hody v Jinačovicích a Babské hody v Kuřimi.",
    program: [
      { time: "14.–16. 7.", title: "Markétské hody", note: "Moravské Knínice" },
      { time: "21.–23. 7.", title: "Mladé hody a den obce", note: "Jinačovice" },
      { time: "22. 7.", title: "Babské hody k poctě sv. Maří Magdalény", note: "Kuřim, areál ZŠ Komenského" },
    ],
    poster: { src: `${UPLOADS}/hody-2023-plakat-kurim.webp`, alt: "Plakát: 11. Babské hody Kuřim 22. 7. 2023" },
    attachments: [
      {
        label: "Plakát: Markétské hody v Moravských Knínicích",
        file: `${UPLOADS}/hody-2023-plakat-kninice.pdf`,
        size: 349653,
      },
      { label: "Plakát: Mladé hody v Jinačovicích", file: `${UPLOADS}/hody-2023-plakat-jinacovice.pdf`, size: 803519 },
      { label: "Plakát: Babské hody v Kuřimi", file: `${UPLOADS}/hody-2023-plakat-kurim.pdf`, size: 324130 },
    ],
  },
  {
    id: "farni-tabor-2023",
    title: "Farní tábor 2023",
    start: "2023-08-12",
    end: "2023-08-19",
    place: "Čachnov",
    text: "Již 5. ročník farního tábora pro děti od 8 do 14 let.",
    poster: { src: `${UPLOADS}/farni-tabor-2023-plakat.webp`, alt: "Plakát: Farní tábor Čachnov 2023" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/farni-tabor-2023-plakat.png`, size: 2604741 }],
  },
  {
    id: "stanovy-pastoracnich-rad-2023",
    title: "Stanovy pastoračních rad farností",
    start: "2023-08-19",
    text: "Biskupství vydalo stanovy pastoračních rad farností. Podle nich proběhnou i u nás volby nové pastorační rady.",
    body: "<p>Návrhy kandidátů, kteří jsou ochotni pět let pracovat v pastorační radě farnosti, můžete předat panu faráři do 17. září.</p>",
    attachments: [
      { label: "Stanovy pastoračních rad", file: `${UPLOADS}/stanovy-pastoracnich-rad-2023-stanovy.pdf`, size: 85184 },
    ],
  },
  {
    id: "marianske-pouti-2023",
    title: "Mariánské poutě",
    start: "2023-09-02",
    end: "2023-09-30",
    place: "Vranov u Brna a Žarošice",
    text: "Přijměte pozvání na zářijové mariánské poutě na Vranov a do Žarošic.",
    poster: {
      src: `${UPLOADS}/marianske-pouti-2023-plakat-zarosice.webp`,
      alt: "Plakát: Zlatá sobota u Staré Matky Boží v Žarošicích 2023",
    },
    attachments: [
      {
        label: "Plakát: Zlatá sobota v Žarošicích",
        file: `${UPLOADS}/marianske-pouti-2023-plakat-zarosice.pdf`,
        size: 245216,
      },
      { label: "Program vranovských poutí", file: `${UPLOADS}/marianske-pouti-2023-program-vranov.pdf`, size: 263303 },
    ],
  },
  {
    id: "pesi-pout-na-vranov-2023",
    title: "Pěší pouť na Vranov",
    start: "2023-09-03",
    time: "7:00",
    place: "Moravské Knínice, Kuřim a Česká",
    mapQuery: "Vranov u Brna",
    text: "Letošní pouť na Vranov je již v neděli 3. září. Zvláště vítáni jsou krojovaní.",
    body:
      "<p>Vyrazit můžete v 7:00 od kapličky v České, nebo tradiční cestou přes Podlesí a Babí lom v 7:00 z Moravských Knínic od domu čp. 2. V 7:20 se můžete přidat v Kuřimi při požehnání poutníkům.</p>" +
      "<p>Na Vranově slouží mši svatou s krojovanými poutníky v 11:00 kuřimský farář P. Jaroslav Filka.</p>",
    poster: { src: `${UPLOADS}/pesi-pout-na-vranov-2023-plakat.webp`, alt: "Plakát: Pěší pouť na Vranov 3. září 2023" },
    attachments: [
      { label: "Plakát", file: `${UPLOADS}/pesi-pout-na-vranov-2023-plakat.pdf`, size: 1988000 },
      {
        label: "Plakát: Sedmiradostná cesta",
        file: `${UPLOADS}/pesi-pout-na-vranov-2023-plakat-sedmiradostna-cesta.pdf`,
        size: 311846,
      },
    ],
  },
  {
    id: "den-narodnostnich-mensin-2023",
    title: "Den národnostních menšin",
    start: "2023-09-17",
    time: "14:00",
    place: "Kuřim, areál zámku",
    text: "Srdečně zveme na Den národnostních menšin v areálu kuřimského zámku.",
    poster: {
      src: `${UPLOADS}/den-narodnostnich-mensin-2023-plakat.webp`,
      alt: "Plakát: Den národnostních menšin v areálu zámku Kuřim",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/den-narodnostnich-mensin-2023-plakat.jpg`, size: 3327476 }],
  },
  {
    id: "medovy-den-2023",
    title: "Medový den",
    start: "2023-09-24",
    time: "10:00–17:00",
    place: "Kuřim, u kulturního domu",
    text: "Farnost bude mít opět svůj stánek s občerstvením, perníčky, drobnými výrobky a věcmi na podporu cystické fibrózy.",
    poster: { src: `${UPLOADS}/medovy-den-2023-plakat.webp`, alt: "Plakát: Medový den 2023 v Kuřimi" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/medovy-den-2023-plakat.pdf`, size: 638006 }],
  },
  {
    id: "koncert-dej-nam-akord-mosty-2023",
    title: "Koncert skupin Dej nám akord a Mosty",
    start: "2023-10-01",
    time: "18:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Ve farním kostele zahrají skupiny Dej nám akord z Brna a Mosty ze Znojma.",
  },
  {
    id: "hody-v-ceske-2023",
    title: "Hody v České",
    start: "2023-10-06",
    end: "2023-10-08",
    place: "Česká",
    text: "Přijměte pozvání na hody do České se stavěním máje, průvodem obcí a hodovou mší svatou.",
    program: [
      { time: "pá 16:00", title: "Stavění máje starou hodovou chasou" },
      { time: "so 15:00", title: "Průvod obcí, předání hodového práva a svěcení práva a vína u kapličky" },
      { time: "so 20:00", title: "Hodová zábava" },
      { time: "ne 11:00", title: "Mše svatá v kostele sv. Maří Magdalény v Kuřimi", note: "autobus z návsi v 10:40" },
      { time: "ne 18:00", title: "Hodové dozvuky" },
    ],
    poster: { src: `${UPLOADS}/hody-v-ceske-2023-plakat.webp`, alt: "Plakát: Hody v České 6.–8. 10. 2023" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/hody-v-ceske-2023-plakat.pdf`, size: 4539538 }],
  },
  {
    id: "adoracni-den-2023",
    title: "Adorační den farnosti",
    start: "2023-10-12",
    time: "9:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Adorační den naší farnosti. Zapište se pod kůrem do rozpisu adorantů, abychom pokryli celou dobu adorace.",
    program: [
      { time: "9:00", title: "Výstav Nejsvětější svátosti" },
      { time: "18:00", title: "Mše svatá" },
    ],
  },
  {
    id: "petrklic-2023-3",
    title: "Petrklíč 3/2023",
    start: "2023-10-14",
    text: "Právě vyšlo nové vydání farního časopisu Petrklíč.",
    attachments: [{ label: "Petrklíč 3/2023", file: "/uploads/petrklic/2023-3/petrklic-2023-3.pdf", size: 21970236 }],
  },
  {
    id: "misijni-klubko-2023",
    title: "Misijní klubko nabízí koláčky",
    start: "2023-10-15",
    place: "Kuřim, před kostelem sv. Maří Magdalény",
    text: "Po mších svatých budou děti z Misijního klubka před kostelem nabízet koláčky a perníčky na podporu Papežských misijních děl dětí.",
  },
  {
    id: "zpravodaj-proglas-2023",
    title: "Zpravodaj Radia Proglas",
    start: "2023-10-15",
    text: "Přečtěte si elektronické vydání podzimního zpravodaje Radia Proglas č. 69.",
    attachments: [
      {
        label: "Zpravodaj Radia Proglas č. 69",
        file: `${UPLOADS}/zpravodaj-proglas-2023-zpravodaj.pdf`,
        size: 1580386,
      },
    ],
  },
  {
    id: "laska-a-pravda-2023",
    title: "Duchovní obnova pro manžele Láska a pravda",
    start: "2023-10-21",
    end: "2023-12-02",
    place: "Tišnov, fara",
    mapQuery: "Kostelní 16, Tišnov",
    text: "Farnost Tišnov a Předklášteří ve spolupráci s komunitou Emmanuel zve manžele všeho věku na tři sobotní setkání.",
    body: "<p>Obnova se koná v soboty 21. 10., 18. 11. a 2. 12. na faře v Tišnově (Kostelní 16). Hlídání dětí bude zajištěno.</p>",
    poster: {
      src: `${UPLOADS}/laska-a-pravda-2023-pozvanka.webp`,
      alt: "Pozvánka: duchovní obnova pro manžele Láska a pravda",
    },
    attachments: [{ label: "Pozvánka", file: `${UPLOADS}/laska-a-pravda-2023-pozvanka.pdf`, size: 286133 }],
    links: [
      { label: "lap@emmanuel.cz", href: "mailto:lap@emmanuel.cz" },
      { label: "Komunita Emmanuel – manželé", href: "https://www.emmanuel.cz/manzele/" },
    ],
    registrationDeadline: "2023-10-15",
    sessions: 3,
  },
  {
    id: "nadechni-se-2023",
    title: "Nadechni se",
    start: "2023-11-04",
    place: "Brno, Lidická 24",
    text: "Duchovní obnova komunity Emmanuel pro rodiče malých dětí: přednáška, chvály, sdílení, čas pro pár a přímluvná modlitba.",
    body: "<p>Hlídání dětí je možné zajistit.</p>",
    poster: {
      src: `${UPLOADS}/nadechni-se-2023-letak.webp`,
      alt: "Leták: Nadechni se – duchovní obnova pro rodiče malých dětí",
    },
    attachments: [{ label: "Leták", file: `${UPLOADS}/nadechni-se-2023-letak.pdf`, size: 871752 }],
    links: [
      { label: "rodiny@emmanuel.cz", href: "mailto:rodiny@emmanuel.cz" },
      { label: "Komunita Emmanuel", href: "https://www.emmanuel.cz/" },
    ],
  },
  {
    id: "martinske-hody-2023",
    title: "Martinské hody",
    start: "2023-11-11",
    end: "2023-11-12",
    place: "Moravské Knínice",
    text: "Přijměte pozvání na Martinské hody a den obce v Moravských Knínicích.",
    program: [
      { time: "so 14:00", title: "Předání hodového práva a zvaní na hody" },
      { time: "so 20:00", title: "Hodová zábava v sokolovně" },
      { time: "ne 11:00", title: "Hodová mše svatá", note: "kostel sv. Markéty" },
      { time: "ne 14:00", title: "Slavnostní jízda sv. Martina a průvod krojované chasy" },
    ],
    poster: {
      src: `${UPLOADS}/martinske-hody-2023-plakat.webp`,
      alt: "Plakát: Martinské hody Moravské Knínice 11.–12. listopadu 2023",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/martinske-hody-2023-plakat.pdf`, size: 1030395 }],
  },
  {
    id: "tyden-modliteb-za-mladez-2023",
    title: "Týden modliteb za mládež",
    start: "2023-11-19",
    end: "2023-11-25",
    text: "Církev se v těchto dnech zvláště modlí za mladé lidi, kteří tvoří její živou součást.",
    poster: {
      src: `${UPLOADS}/tyden-modliteb-za-mladez-2023-plakat.webp`,
      alt: "Plakát: Týden modliteb za mládež 19.–25. 11. 2023",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/tyden-modliteb-za-mladez-2023-plakat.pdf`, size: 4586723 }],
  },
  {
    id: "charitativni-jarmark-a-beh-2023",
    title: "Charitativní jarmark a běh",
    start: "2023-11-25",
    end: "2023-11-26",
    place: "Česká a Lelekovice",
    text: "23. farní charitativní jarmark v České a 7. charitativní běh v Lelekovicích. Výtěžek půjde na pomoc seniorům na Ukrajině.",
    program: [
      {
        time: "so 10:30",
        title: "Charitativní běh",
        note: "start u vodojemu na Pasekách v Lelekovicích, prezence od 10:00",
      },
      { time: "so 15:00–18:00", title: "Příjem výrobků do jarmarku", note: "sokolovna v České" },
      {
        time: "so 16:00",
        title: "Beseda o pomoci Ukrajině",
        note: "s Evženem Adámkem, ředitelem Oblastní charity Znojmo",
      },
      { time: "ne 13:30–17:30", title: "Jarmark", note: "sokolovna v České" },
    ],
    poster: {
      src: `${UPLOADS}/charitativni-jarmark-a-beh-2023-letak.webp`,
      alt: "Leták: 23. charitativní jarmark v České a 7. charitativní běh",
    },
    attachments: [{ label: "Leták", file: `${UPLOADS}/charitativni-jarmark-a-beh-2023-letak.pdf`, size: 706024 }],
  },
  {
    id: "cervena-streda-2023",
    title: "Červená středa",
    start: "2023-11-29",
    time: "17:00–20:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Mezinárodní připomínka lidí pronásledovaných pro víru. Sháníme dobrovolníky pro organizaci akce.",
    body: "<p>Kostel bude po celou dobu akce nasvícen červeně. V 18 hodin bude mše svatá za pronásledované, pak tichá adorace a modlitba při svíčkách.</p>",
    poster: { src: `${UPLOADS}/cervena-streda-2023-plakat.webp`, alt: "Plakát: Červená středa 29. listopadu 2023" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/cervena-streda-2023-plakat.jpg`, size: 3146320 }],
    links: [{ label: "Červená středa", href: "https://www.cervenastreda.cz/" }],
  },
  {
    id: "modlitebni-vecer-emmanuel-2023",
    title: "Modlitební večer s komunitou Emmanuel",
    start: "2023-12-01",
    time: "19:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Modlitební večer s adorací a hudebním doprovodem komunity Emmanuel.",
    poster: {
      src: `${UPLOADS}/modlitebni-vecer-emmanuel-2023-plakat.webp`,
      alt: "Plakát: Modlitební večer s komunitou Emmanuel 1. 12. 2023",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/modlitebni-vecer-emmanuel-2023-plakat.jpg`, size: 139490 }],
  },
  {
    id: "oceneni-kukuc-2023",
    title: "Ocenění KuKuč pro farníky",
    start: "2023-12-13",
    time: "18:00",
    place: "Kuřim, kulturní dům",
    text: "Při vyhlášení Kuřimských kulturních činů za rok 2023 budou oceněny i dvě aktivity lidí z farnosti.",
    body: "<ul><li>Pavel Rajmic a kapela Church Knights za vystoupení na Noci kostelů 2023,</li><li>výstava betlémů, kterou připravili Jana Kytnerová, Lucie Sádlíková a Milan Císař.</li></ul>",
  },
  {
    id: "petrklic-2023-4",
    title: "Petrklíč 4/2023",
    start: "2023-12-14",
    text: "Právě vyšlo nové vydání farního časopisu Petrklíč.",
    attachments: [{ label: "Petrklíč 4/2023", file: "/uploads/petrklic/2023-4/petrklic-2023-4.pdf", size: 21626677 }],
  },
  {
    id: "vanoce-2023",
    title: "Bohoslužby o Vánocích 2023",
    start: "2023-12-17",
    end: "2024-01-07",
    place: "Kuřim a Moravské Knínice",
    text: "Rozpis vánočních bohoslužeb a zpovídání v kuřimské farnosti.",
    body: "<p>Chrámový sbor zpívá při noční mši na Štědrý den ve 22:00 a na Boží hod v 9:30. Dětská schola zpívá na Štědrý den v 15:00 při programu pro děti.</p>",
    attachments: [{ label: "Pořad bohoslužeb", file: `${UPLOADS}/vanoce-2023-porad-bohosluzeb.pdf`, size: 58947 }],
  },
  {
    id: "vystava-betlemu-2023",
    title: "Výstava betlémů",
    start: "2023-12-17",
    end: "2024-01-07",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "V době vánoční zveme na výstavu betlémů v kuřimském kostele.",
    program: [
      { time: "ne 17. 12.", title: "10:30–11:30" },
      { time: "ne 24. 12.", title: "13:00–15:00" },
      { time: "út 26. 12.", title: "10:30–11:30" },
      { time: "po 1. 1.", title: "14:30–16:30" },
      { time: "ne 7. 1.", title: "10:30–11:30" },
    ],
    poster: { src: `${UPLOADS}/vystava-betlemu-2023-plakat.webp`, alt: "Plakát: Výstava betlémů v kuřimském kostele" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/vystava-betlemu-2023-plakat.pdf`, size: 1059871 }],
  },
  {
    id: "betlemske-svetlo-2023",
    title: "Betlémské světlo",
    start: "2023-12-23",
    place: "Kuřim",
    text: "Skauti budou v sobotu dopoledne roznášet Betlémské světlo až k vám domů.",
    body: "<p>Pokud máte zájem, aby přišli i k vám nebo k vašim blízkým, nechte lístek se jménem a adresou v krabičce pod kůrem, nebo napište e-mail.</p>",
    poster: { src: `${UPLOADS}/betlemske-svetlo-2023-letak.webp`, alt: "Leták: Betlémské světlo v Kuřimi" },
    attachments: [{ label: "Leták", file: `${UPLOADS}/betlemske-svetlo-2023-letak.jpg`, size: 400749 }],
    links: [{ label: "betlemskesvetlo@skautkurim.cz", href: "mailto:betlemskesvetlo@skautkurim.cz" }],
  },
  {
    id: "vanocni-pribeh-2023",
    title: "Vánoční příběh",
    start: "2023-12-24",
    time: "15:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Štědrovečerní bohoslužba slova a Vánoční příběh s doprovodem kuřimské dětské scholy.",
    poster: { src: `${UPLOADS}/vanocni-pribeh-2023-plakat.webp`, alt: "Plakát: Vánoční příběh, Štědrý den v 15 hodin" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/vanocni-pribeh-2023-plakat.pdf`, size: 950270 }],
  },
  {
    id: "vanocni-zpivani-zs-divizna-2023",
    title: "Vánoční zpívání ZŠ DiviZna",
    start: "2023-12-26",
    time: "15:30",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Základní škola DiviZna zve na vánoční zpívání.",
    poster: {
      src: `${UPLOADS}/vanocni-zpivani-zs-divizna-2023-plakat.webp`,
      alt: "Plakát: Vánoční zpívání ZŠ DiviZna 26. 12. 2023",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/vanocni-zpivani-zs-divizna-2023-plakat.pdf`, size: 5082648 }],
  },
];
