import type { NewsEvent } from "@/content/types/news";
import { UPLOADS } from "./uploads";

export const events2024: NewsEvent[] = [
  {
    id: "aznaveky-2024-01-08",
    title: "Ažnavěky: nový videolist brněnské diecéze",
    start: "2024-01-08",
    text: "Biskup Pavel Konzbul s generálním vikářem a vikářem pro pastoraci mluví ve videolistu Ažnavěky o všem důležitém, co se v diecézi událo.",
    body: "<p>Až na věky? Ano! <strong>Ažnavěky</strong> – tak se jmenuje nově vzniklý videolist brněnské diecéze, ve kterém biskup Pavel Konzbul společně s generálním vikářem Pavlem Kafkou a vikářem pro pastoraci a vzdělávání Pavlem Šenkyříkem mluví o všem důležitém, co se v posledních měsících událo na biskupství a v diecézi. Všichni tři jako bonus přidávají vlastní postřehy a místy i tajemství a zvyky, o kterých se odjinud nedozvíte.</p>",
    links: [{ label: "Videolist na YouTube", href: "https://www.youtube.com/watch?v=W4rDTN74Zuw" }],
  },
  {
    id: "zpravodaj-puls-2024",
    title: "Zpravodaj fondu Puls",
    start: "2024-01-08",
    text: "Přečtěte si lednové číslo zpravodaje fondu Puls (ImPULSy brněnské diecéze).",
    attachments: [
      { label: "Zpravodaj Puls, leden 2024", file: `${UPLOADS}/zpravodaj-puls-2024-zpravodaj.pdf`, size: 1294216 },
    ],
  },
  {
    id: "trikralovy-koncert-zus-2024",
    title: "Tříkrálový koncert ZUŠ",
    start: "2024-01-10",
    time: "18:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Základní umělecká škola a Klub přátel ZUŠ Kuřim zvou na Tříkrálový koncert.",
    poster: {
      src: `${UPLOADS}/trikralovy-koncert-zus-2024-plakat.webp`,
      alt: "Plakát: Tříkrálový koncert ZUŠ Kuřim 10. 1. 2024",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/trikralovy-koncert-zus-2024-plakat.jpg`, size: 708190 }],
  },
  {
    id: "kurz-alfa-tisnov-2024",
    title: "Kurz Alfa v Tišnově",
    start: "2024-01-16",
    time: "19:00",
    place: "Tišnov, fara",
    mapQuery: "Kostelní 16, Tišnov",
    text: "Kurz Alfa „Jiný pohled“ pro lidi, kteří se chtějí bavit o hlubších otázkách života a o křesťanské víře.",
    poster: {
      src: `${UPLOADS}/kurz-alfa-tisnov-2024-plakat.webp`,
      alt: "Plakát: Kurz Alfa – Jiný pohled, Tišnov 16. 1. 2024",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/kurz-alfa-tisnov-2024-plakat.pdf`, size: 4219384 }],
    links: [{ label: "b.vitam@post.cz", href: "mailto:b.vitam@post.cz" }],
  },
  {
    id: "mission-possible-2024",
    title: "Mission Possible",
    start: "2024-01-20",
    end: "2024-03-26",
    place: "Kuřim, fara",
    text: "Kurz dialogu a misie komunity Emmanuel pro angažované křesťany na kuřimské faře.",
    body: "<p>Kurz má dvě soboty (20. 1. a 16. 3. od 9:00 do 18:30) a čtyři úterní večery (30. 1., 13. 2., 27. 2. a 26. 3. od 19:00 do 21:30). Setkání obsahují impulz k tématu, sdílení ve skupinkách, společnou modlitbu a vlastní projekt.</p>",
    poster: {
      src: `${UPLOADS}/mission-possible-2024-letak.webp`,
      alt: "Leták: Mission Possible – kurz dialogu a misie",
    },
    attachments: [{ label: "Leták", file: `${UPLOADS}/mission-possible-2024-letak.pdf`, size: 2100559 }],
    links: [{ label: "Mission Possible", href: "https://www.emmanuel.cz/mp/" }],
    sessions: 6,
  },
  {
    id: "narodni-tyden-manzelstvi-2024",
    title: "Národní týden manželství",
    start: "2024-02-12",
    end: "2024-02-18",
    text: "Týden věnovaný manželství s online webinářem Manželství – cesta vzájemného respektu a dalšími akcemi.",
    body: "<p>Ve čtvrtek <strong>15. 2.</strong> od <strong>19:30</strong> je možné navštívit jednorázový online webinář <strong>Manželství – cesta vzájemného respektu</strong>. Program akcí v tišnovském děkanství najdete v přílohách.</p>",
    poster: {
      src: `${UPLOADS}/narodni-tyden-manzelstvi-2024-plakat-webinar.webp`,
      alt: "Plakát: Národní týden manželství, webinář Manželství – cesta vzájemného respektu",
    },
    attachments: [
      { label: "Plakát: webinář", file: `${UPLOADS}/narodni-tyden-manzelstvi-2024-plakat-webinar.pdf`, size: 400296 },
      {
        label: "Program v děkanství Tišnov",
        file: `${UPLOADS}/narodni-tyden-manzelstvi-2024-program-tisnov.jpg`,
        size: 302353,
      },
    ],
    links: [{ label: "CENAP", href: "https://www.cenap.cz/" }],
  },
  {
    id: "krizova-cesta-v-prirode-2024",
    title: "Křížová cesta v přírodě",
    start: "2024-02-14",
    end: "2024-03-28",
    place: "Moravské Knínice, Mezihoří",
    text: "Obnovená křížová cesta pro osobní modlitbu vede od výletiště v Mezihoří na kopec Strážná.",
    body: "<p>Letos vychází z knihy kardinála Miloslava Vlka „Meditace nad křížovou cestou“ a ilustrace k jednotlivým zastavením vytvořila paní Jindra Hubková.</p>",
    attachments: [
      { label: "Pozvánka", file: `${UPLOADS}/krizova-cesta-v-prirode-2024-pozvanka.pdf`, size: 39789 },
      { label: "Mapa trasy", file: `${UPLOADS}/krizova-cesta-v-prirode-2024-mapa.pdf`, size: 321003 },
    ],
  },
  {
    id: "postni-obnova-pro-manzele-2024",
    title: "Postní duchovní obnova pro manžele",
    start: "2024-02-16",
    end: "2024-02-17",
    place: "Vranov u Brna, duchovní centrum",
    text: "Postní duchovní obnova pro manžele v duchovním centru na Vranově.",
    links: [
      {
        label: "Duchovní obnovy pro manžele",
        href: "https://www.crsp.cz/nabizime/duchovni-programy/duchovni-obnovy-pro-manzele/",
      },
    ],
  },
  {
    id: "beneficni-varhanni-koncert-2024",
    title: "Benefiční varhanní koncert",
    start: "2024-02-25",
    time: "16:00",
    place: "Moravské Knínice, kostel sv. Markéty",
    text: "Zahraje Přemysl Kšica, varhaník chrámu sv. Mikuláše na Malé Straně v Praze.",
    price: "dobrovolné vstupné",
    poster: {
      src: `${UPLOADS}/beneficni-varhanni-koncert-2024-plakat.webp`,
      alt: "Plakát: Benefiční varhanní koncert, Přemysl Kšica",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/beneficni-varhanni-koncert-2024-plakat.png`, size: 3648112 }],
  },
  {
    id: "24-hodin-pro-pana-2024",
    title: "24 hodin pro Pána v Tišnově",
    start: "2024-03-08",
    end: "2024-03-09",
    place: "Tišnov, kostel sv. Václava",
    text: "Den modliteb, adorace a návštěv kostela s příležitostí ke svaté zpovědi.",
    body: "<p>Příležitost ke svaté zpovědi je v pátek od 17 do 21 hodin a v sobotu od 19 do 20 hodin.</p>",
    poster: {
      src: `${UPLOADS}/24-hodin-pro-pana-2024-plakat.webp`,
      alt: "Plakát: 24 hodin pro Pána v Tišnově 8.–9. 3. 2024",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/24-hodin-pro-pana-2024-plakat.pdf`, size: 143421 }],
  },
  {
    id: "postni-duchovni-obnova-2024",
    title: "Postní duchovní obnova",
    start: "2024-03-10",
    time: "14:30",
    place: "Kuřim, fara",
    text: "Postní duchovní obnova na téma Ježíšova křížová cesta s P. Jaroslavem Filkou.",
    poster: {
      src: `${UPLOADS}/postni-duchovni-obnova-2024-plakat.webp`,
      alt: "Plakát: Postní duchovní obnova na téma Ježíšova křížová cesta",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/postni-duchovni-obnova-2024-plakat.png`, size: 881523 }],
  },
  {
    id: "nejlepe-opravena-pamatka-2024",
    title: "Hlasujte pro kostel sv. Markéty",
    start: "2024-03-11",
    end: "2024-03-31",
    text: "Kostel sv. Markéty v Moravských Knínicích soutěží o nejlépe opravenou kulturní památku Jihomoravského kraje v roce 2023.",
    body: "<p>Hlasovat lze do 31. března odesláním SMS s textem <strong>PAMATKA 14</strong> na číslo <strong>736 301 599</strong>. Z jednoho telefonu je možné hlasovat jen jednou, SMS stojí podle tarifu hlasujícího.</p>",
    poster: {
      src: `${UPLOADS}/nejlepe-opravena-pamatka-2024-letak.webp`,
      alt: "Leták: Kostel sv. Markéty v soutěži o nejlépe opravenou památku",
    },
    attachments: [{ label: "Leták", file: `${UPLOADS}/nejlepe-opravena-pamatka-2024-letak.pdf`, size: 306167 }],
    links: [{ label: "Soutěž na webu kraje", href: "https://www.kr-jihomoravsky.cz/pamatky" }],
  },
  {
    id: "velikonoce-2024",
    title: "Velikonoce 2024",
    start: "2024-03-21",
    end: "2024-04-01",
    place: "Kuřim a Moravské Knínice",
    text: "Pořad velikonočních bohoslužeb a zpovídání a pozvání na obřady se zpěvy chrámového sboru.",
    program: [
      { time: "Zelený čtvrtek 18:00", title: "Mše svatá", note: "M. Praetorius: Anima mea, Taizé: Zůstaňte" },
      {
        time: "Velký pátek 18:00",
        title: "Obřady Velkého pátku",
        note: "zpívané pašije podle sv. Marka, A. Mička: Improperia, J. Berthier: Per crucem, F. H. Kedrut: Vexilla regis",
      },
      {
        time: "Bílá sobota 19:00",
        title: "Velikonoční vigilie",
        note: "J. Olejník: Exsultet, A. S. Maškov: Alleluja, A. Lotti: Regina coeli",
      },
      {
        time: "Velikonoční neděle 9:30",
        title: "Mše svatá",
        note: "V. K. H. Rovenský: Zazpívejme Kristu Pánu, B. Korejs: Velikonoční, M. Praetorius: Dnes je den Páně vítězství",
      },
    ],
    poster: {
      src: `${UPLOADS}/velikonoce-2024-pozvanka.webp`,
      alt: "Pozvánka: Svátky velikonoční se zpěvy chrámového sboru",
    },
    attachments: [
      { label: "Pozvánka", file: `${UPLOADS}/velikonoce-2024-pozvanka.pdf`, size: 781226 },
      { label: "Pořad bohoslužeb a zpovídání", file: `${UPLOADS}/velikonoce-2024-porad-bohosluzeb.pdf`, size: 107128 },
    ],
  },
  {
    id: "krizova-cesta-rodin-2024",
    title: "Křížová cesta rodin",
    start: "2024-03-23",
    time: "10:00",
    place: "Kuřim, kaple sv. Jana Nepomuckého",
    text: "Křížová cesta rodin vychází od vodní kaple sv. Jana Nepomuckého a končí na faře u ohně.",
    body: "<p>Doneste si něco na opečení.</p>",
  },
  {
    id: "misijni-kavarna-2024",
    title: "Misijní kavárna",
    start: "2024-03-24",
    place: "Kuřim, fara",
    text: "Na Květnou neděli ochutnáte kávu Agapé z produkce Papežských misijních děl a děti si vytvoří velikonoční přání.",
    body: "<p>Káva pochází z česko-ugandské spolupráce. Výtěžek půjde na aktuální projekty Papežských misijních děl.</p>",
    poster: { src: `${UPLOADS}/misijni-kavarna-2024-plakat.webp`, alt: "Plakát: Misijní kavárna na Květnou neděli" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/misijni-kavarna-2024-plakat.pdf`, size: 2275304 }],
  },
  {
    id: "sbirka-na-charitu-2024",
    title: "Sbírka na Charitu",
    start: "2024-04-07",
    text: "O neděli Božího milosrdenství můžete svým darem podpořit dílo Charity a pomoci lidem v nouzi.",
    poster: { src: `${UPLOADS}/sbirka-na-charitu-2024-letak.webp`, alt: "Leták: Sbírka na Charitu 7. 4. 2024" },
    attachments: [{ label: "Leták", file: `${UPLOADS}/sbirka-na-charitu-2024-letak.pdf`, size: 276361 }],
    links: [{ label: "Diecézní charita Brno", href: "https://www.dchb.charita.cz/" }],
  },
  {
    id: "diecezni-ministrantska-pout-2024",
    title: "Diecézní ministrantská pouť",
    start: "2024-04-27",
    time: "13:00",
    place: "Rajhrad, benediktinský klášter",
    text: "Diecézní ministrantská pouť do Rajhradu. Sraz je ve 13:00 před kostelem sv. Petra a Pavla.",
    registrationDeadline: "2024-03-27",
    poster: {
      src: `${UPLOADS}/diecezni-ministrantska-pout-2024-plakat.webp`,
      alt: "Plakát: Diecézní ministrantská pouť, Rajhrad 27. dubna 2024",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/diecezni-ministrantska-pout-2024-plakat.pdf`, size: 429702 }],
    links: [{ label: "Ministranti brněnské diecéze", href: "https://www.biskupstvi.cz/ministranti" }],
  },
  {
    id: "pout-do-predklasteri-2024",
    title: "Pouť do Předklášteří",
    start: "2024-05-11",
    time: "9:00",
    place: "Předklášteří, klášter Porta Coeli",
    text: "Komunita Emmanuel a kuřimská farnost zvou na pěší pouť k Bráně nebes, do kláštera Porta Coeli v Předklášteří.",
    program: [
      { time: "9:00", title: "Modlitba chval v kuřimském kostele" },
      { time: "dopoledne", title: "Putování do Předklášteří", note: "z Hradčan asi 10 km" },
      { time: "asi 14:30", title: "Růženec a mše svatá v Porta Coeli" },
      { time: "potom", title: "Posezení v klášterním pivovaru Vorkloster", note: "po předchozí rezervaci" },
    ],
    poster: {
      src: `${UPLOADS}/pout-do-predklasteri-2024-plakat.webp`,
      alt: "Plakát: Pouť k Bráně nebes, sobota 11. května",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/pout-do-predklasteri-2024-plakat.pdf`, size: 28174 }],
    links: [{ label: "Pouť na webu komunity Emmanuel", href: "https://www.emmanuel.cz/pout-do-predklasteri" }],
  },
  {
    id: "diecezni-setkani-mladeze-2024",
    title: "Diecézní setkání mládeže",
    start: "2024-05-18",
    place: "Třebíč",
    text: "Diecézní setkání mládeže se letos koná v Třebíči.",
    poster: {
      src: `${UPLOADS}/diecezni-setkani-mladeze-2024-plakat.webp`,
      alt: "Plakát: Diecézní setkání mládeže, Třebíč 18. 5. 2024",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/diecezni-setkani-mladeze-2024-plakat.pdf`, size: 5255800 }],
  },
  {
    id: "den-rodin-2024",
    title: "Den rodin",
    start: "2024-05-19",
    time: "14:00",
    place: "Kuřim, areál zámku",
    text: "Odpoledne pro rodiny s vystoupeními, soutěžemi, malováním na obličej a skákacími hrady. Vstupné dobrovolné.",
    program: [
      { time: "14:00", title: "Zahájení" },
      { time: "14:10", title: "Taneční vystoupení Lumíku" },
      { time: "14:45", title: "Vystoupení kouzelníka" },
      { time: "15:15", title: "Dětská rocková skupina MAD" },
      { time: "16:00", title: "Skotačení s klaunem" },
      { time: "16:45", title: "Kuřimská schola" },
    ],
    poster: {
      src: `${UPLOADS}/den-rodin-2024-plakat.webp`,
      alt: "Plakát: Den rodin v areálu kuřimského zámku 19. 5. 2024",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/den-rodin-2024-plakat.pdf`, size: 2035495 }],
  },
  {
    id: "dekanatni-setkani-ministrantu-2024",
    title: "Děkanátní setkání ministrantů",
    start: "2024-05-25",
    time: "14:00",
    place: "Veverská Bítýška, kostel sv. Jakuba",
    text: "Setkání ministrantů děkanství se mší svatou, fotbalem, lukostřelbou a táborákem.",
    program: [
      { time: "14:00", title: "Mše svatá", note: "lze ministrovat" },
      { time: "15:00–17:00", title: "Fotbal a lukostřelba" },
      { time: "17:00–18:30", title: "Táborák s opékáním buřtů a další hry" },
    ],
    poster: {
      src: `${UPLOADS}/dekanatni-setkani-ministrantu-2024-plakat.webp`,
      alt: "Plakát: Děkanátní setkání ministrantů, Veverská Bítýška 25. 5. 2024",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/dekanatni-setkani-ministrantu-2024-plakat.pdf`, size: 560674 }],
  },
  {
    id: "aznaveky-2024-05-30",
    title: "Ažnavěky: druhý díl videozpravodaje",
    start: "2024-05-30",
    text: "Druhý díl videozpravodaje brněnského biskupství Ažnavěky je ke zhlédnutí na YouTube.",
    links: [{ label: "Ažnavěky na YouTube", href: "https://www.youtube.com/watch?v=PZHhswrbXME" }],
  },
  {
    id: "noc-kostelu-2024",
    title: "Noc kostelů",
    start: "2024-06-07",
    time: "17:00–22:30",
    place: "Kuřim a Moravské Knínice",
    text: "Noc kostelů v Kuřimi a v Moravských Knínicích s bohatým programem.",
    body: "<p>V Moravských Knínicích je kostel otevřen od 18 do 22 hodin: prohlídky věže, zvonice, ochozu a půdy, fresky a varhany, výstava liturgických předmětů a rouch, ochutnávka mešních vín a hostií, varhanní improvizace v 18:30 a ve 20:00, knínická schola v 19:00 a program pro děti v okolí kostela.</p>",
    program: [
      { time: "17:00–20:15", title: "Individuální prohlídka kostela", note: "Kuřim" },
      { time: "17:00–22:00", title: "Výstava „Cesta časem“" },
      { time: "18:15–19:15", title: "Slavnostní bohoslužba", note: "se zpěvy chrámového sboru a hostů" },
      { time: "19:30–20:00", title: "Zpěvy kuřimské dětské scholy" },
      { time: "20:10–20:25", title: "Divadelní představení Deset egyptských ran" },
      { time: "20:30–21:00", title: "Videoprojekce k 350 letům od zjevení v Paray-le-Monial" },
      { time: "21:00–22:00", title: "Kdo zpívá, dvakrát se modlí" },
      { time: "22:00–22:30", title: "Zakončení Noci kostelů" },
    ],
    poster: {
      src: `${UPLOADS}/noc-kostelu-2024-program-kurim.webp`,
      alt: "Plakát: Noc kostelů 7. 6. 2024 v kostele sv. Maří Magdalény v Kuřimi",
    },
    attachments: [
      { label: "Program: Kuřim", file: `${UPLOADS}/noc-kostelu-2024-program-kurim.pdf`, size: 845075 },
      { label: "Program: Moravské Knínice", file: `${UPLOADS}/noc-kostelu-2024-program-kninice.pdf`, size: 638575 },
    ],
    links: [{ label: "Noc kostelů v Kuřimi", href: "https://www.nockostelu.cz/kostel/470/" }],
  },
  {
    id: "farni-den-2024",
    title: "Farní piknikový den",
    start: "2024-06-09",
    time: "10:30–15:00",
    place: "Kuřim, farní zahrada",
    text: "Farní den letos netradičně formou pikniku na farní zahradě, hned po druhé mši svaté.",
    body: "<p>Na programu je představení služeb Oblastní charity Tišnov, živá hudba a táborák. Přineste si své oblíbené pochoutky, špekáčky a deku.</p>",
    poster: { src: `${UPLOADS}/farni-den-2024-pozvanka.webp`, alt: "Pozvánka: Farní piknikový den 9. 6. 2024" },
    attachments: [{ label: "Pozvánka", file: `${UPLOADS}/farni-den-2024-pozvanka.pdf`, size: 1211360 }],
  },
  {
    id: "koncert-co-cini-buh-2024",
    title: "Koncert barokní a renesanční hudby",
    start: "2024-06-09",
    time: "17:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Brněnský ekumenický sbor a komorní orchestr barokních nástrojů uvedou koncert duchovní hudby Co činí Bůh, vše dobré jest.",
    poster: {
      src: `${UPLOADS}/koncert-co-cini-buh-2024-plakat.webp`,
      alt: "Plakát: Koncert duchovní hudby Co činí Bůh, vše dobré jest",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/koncert-co-cini-buh-2024-plakat.png`, size: 454901 }],
    links: [{ label: "Brněnský ekumenický sbor", href: "https://www.besbrno.cz/cs" }],
  },
  {
    id: "putovani-mezi-staletimi-2024",
    title: "Putování mezi staletími",
    start: "2024-06-09",
    time: "17:00",
    place: "Moravské Knínice, kostel sv. Markéty",
    text: "Koncert Brněnského varhanního festivalu: Hana Bartošová (varhany) a Barbora Štěflová (hoboj).",
    price: "dobrovolné vstupné",
    poster: {
      src: `${UPLOADS}/putovani-mezi-staletimi-2024-plakat.webp`,
      alt: "Plakát: Putování mezi staletími, Brněnský varhanní festival",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/putovani-mezi-staletimi-2024-plakat.pdf`, size: 2868184 }],
  },
  {
    id: "dekanatni-setkani-katechetu-2024",
    title: "Děkanátní setkání katechetů",
    start: "2024-06-11",
    time: "18:30",
    place: "Tišnov, fara",
    text: "Přednáška Mgr. Jitky Šebkové na téma „Jak nepřijít o motivaci ve službě“ a vzájemné sdílení.",
    body: "<p>Jste srdečně zváni už na mši svatou v 17:30 v kostele sv. Václava.</p>",
    poster: {
      src: `${UPLOADS}/dekanatni-setkani-katechetu-2024-pozvanka.webp`,
      alt: "Pozvánka: Děkanátní setkání katechetů 11. 6. 2024",
    },
    attachments: [
      { label: "Pozvánka", file: `${UPLOADS}/dekanatni-setkani-katechetu-2024-pozvanka.pdf`, size: 3557583 },
    ],
  },
  {
    id: "petrklic-2024-2",
    title: "Petrklíč 2/2024",
    start: "2024-06-22",
    text: "Právě vyšlo nové vydání farního časopisu Petrklíč.",
    attachments: [{ label: "Petrklíč 2/2024", file: "/uploads/petrklic/2024-2/petrklic-2024-2.pdf", size: 2616368 }],
  },
  {
    id: "tvurci-pokoje-2024",
    title: "Tvůrci pokoje",
    start: "2024-06-30",
    text: "Pastorační středisko brněnské diecéze zve leadery farních společenství na vzdělávací program Stávat se tvůrci pokoje.",
    poster: {
      src: `${UPLOADS}/tvurci-pokoje-2024-letak.webp`,
      alt: "Leták: Stávat se tvůrci pokoje, vzdělávací program pro leadery farních společenství",
    },
    attachments: [{ label: "Leták", file: `${UPLOADS}/tvurci-pokoje-2024-letak.pdf`, size: 6268959 }],
    links: [{ label: "Tvůrci pokoje", href: "https://www.tvurcipokoje.cz/" }],
  },
  {
    id: "konference-charis-2024",
    title: "Katolická charismatická konference",
    start: "2024-07-10",
    end: "2024-07-14",
    place: "Brno, Výstaviště",
    text: "Katolická charismatická konference Charis na brněnském výstavišti. Přijet se dá i bez přihlášení.",
    registrationDeadline: "2024-06-25",
    attachments: [{ label: "Informace", file: `${UPLOADS}/konference-charis-2024-informace.pdf`, size: 120476 }],
    links: [{ label: "Konference Charis", href: "https://konferencecharis.cz/" }],
  },
  {
    id: "duchovni-obnova-mary-healy-2024",
    title: "Duchovní obnova s Dr. Mary Healy",
    start: "2024-08-09",
    end: "2024-08-11",
    text: "Duchovní obnova na téma Duchovní dary a uzdravení pod záštitou brněnského biskupa.",
    links: [{ label: "Duchovní obnova", href: "https://obnova.credonf.cz/" }],
  },
  {
    id: "farni-tabor-2024",
    title: "Farní tábor 2024",
    start: "2024-08-10",
    end: "2024-08-17",
    place: "Čachnov",
    text: "Šestý ročník farního tábora pro děti od 8 do 14 let.",
    body: "<p>Od 1. června se na faře koná předtáborová víkendovka.</p>",
    poster: { src: `${UPLOADS}/farni-tabor-2024-plakat.webp`, alt: "Plakát: Farní tábor Čachnov 2024" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/farni-tabor-2024-plakat.pdf`, size: 1274692 }],
  },
  {
    id: "primestsky-tabor-2024",
    title: "Letní příměstský tábor pro nejmenší",
    start: "2024-08-12",
    end: "2024-08-23",
    place: "Kuřim, fara",
    mapQuery: "Křížkovského 55, Kuřim",
    text: "Dva turnusy příměstského tábora pro děti od 3 do 5 let na téma Poznáváme IZS.",
    body:
      "<p>Tábor probíhá od <strong>12. do 16. 8.</strong> a od <strong>19. do 23. 8.</strong> pod záštitou farnosti a za podpory města Kuřimi.</p>" +
      "<p>Hledáme dobrovolníky – „čtecí babičky a dědečky“ – pro odpolední pauzu od 13:00 do 14:30. Přihlášky a informace u Mgr. Ing. Jany Němečkové.</p>",
    poster: {
      src: `${UPLOADS}/primestsky-tabor-2024-plakat.webp`,
      alt: "Plakát: Příměstský tábor pro mrňata 2024, Kuřim",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/primestsky-tabor-2024-plakat.pdf`, size: 4253832 }],
    links: [{ label: "detitaborkurim@seznam.cz", href: "mailto:detitaborkurim@seznam.cz" }],
  },
  {
    id: "diecezni-pout-rodin-2024",
    title: "Diecézní pouť rodin",
    start: "2024-08-31",
    time: "10:30",
    place: "Předklášteří, klášter Porta Coeli",
    text: "Dvacátá diecézní pouť rodin s pontifikální mší svatou, kterou slouží biskup Pavel Konzbul.",
    program: [
      { time: "10:30", title: "Modlitba růžence, svátost smíření" },
      { time: "11:00", title: "Pontifikální mše svatá", note: "biskup Pavel Konzbul" },
      { time: "12:00", title: "Zábavná stanoviště s úkoly pro děti a mládež" },
      { time: "13:00", title: "Divadlo Mikro-teatro: Vítr z plachet!" },
      { time: "14:00", title: "Adorace s komunitou Emmanuel, svátost smíření" },
      { time: "15:30", title: "Slavnostní zakončení s požehnáním do nového školního roku" },
    ],
    poster: {
      src: `${UPLOADS}/diecezni-pout-rodin-2024-plakat.webp`,
      alt: "Plakát: 20. diecézní pouť rodin, Předklášteří 31. 8. 2024",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/diecezni-pout-rodin-2024-plakat.pdf`, size: 3380491 }],
  },
  {
    id: "marianske-pouti-2024",
    title: "Mariánské poutě",
    start: "2024-09-01",
    end: "2024-09-22",
    place: "Vranov u Brna a Žarošice",
    text: "Přijměte pozvání na pouť Sedmiradostnou cestou, Zlatou sobotu v Žarošicích a pěší pouť na Vranov.",
    program: [
      { time: "1. 9.", title: "6. pouť Sedmiradostnou cestou Česká – Lelekovice – Vranov", note: "mše svatá v 11:00" },
      { time: "14. 9.", title: "Zlatá sobota v Žarošicích", note: "krojovaný světelný průvod se soškami Panny Marie" },
      {
        time: "22. 9.",
        title: "12. tradiční pěší pouť Moravské Knínice – Kuřim – Vranov",
        note: "s krojovaným procesím, mše svatá v 11:00",
      },
    ],
    poster: {
      src: `${UPLOADS}/marianske-pouti-2024-plakat-pesi-pout.webp`,
      alt: "Plakát: Pěší pouť na Vranov 22. září 2024",
    },
    attachments: [
      {
        label: "Plakát: Pěší pouť na Vranov",
        file: `${UPLOADS}/marianske-pouti-2024-plakat-pesi-pout.pdf`,
        size: 865734,
      },
      {
        label: "Plakát: Sedmiradostná cesta",
        file: `${UPLOADS}/marianske-pouti-2024-plakat-sedmiradostna-cesta.pdf`,
        size: 311560,
      },
      {
        label: "Plakát: Zlatá sobota v Žarošicích",
        file: `${UPLOADS}/marianske-pouti-2024-plakat-zlata-sobota.pdf`,
        size: 583352,
      },
    ],
  },
  {
    id: "aznaveky-2024-09-14",
    title: "Ažnavěky: třetí díl videozpravodaje",
    start: "2024-09-14",
    text: "Videozpravodaj brněnského biskupství Ažnavěky pokračuje třetím dílem.",
    links: [{ label: "Ažnavěky na YouTube", href: "https://www.youtube.com/watch?v=5fpZWepkA1I" }],
  },
  {
    id: "sbirka-na-cirkevni-skolstvi-2024",
    title: "Sbírka na církevní školství a na bohoslovce",
    start: "2024-09-15",
    text: "Sbírkou podpoříte aktivity církve a modlitbou doprovodíte budoucí kněze. Přispět můžete i přes portál Donátor.",
    poster: {
      src: `${UPLOADS}/sbirka-na-cirkevni-skolstvi-2024-letak.webp`,
      alt: "Leták: Sbírka na církevní školství a na bohoslovce 15. září 2024",
    },
    attachments: [{ label: "Leták", file: `${UPLOADS}/sbirka-na-cirkevni-skolstvi-2024-letak.jpg`, size: 484882 }],
  },
  {
    id: "beta-kurz-2024",
    title: "Beta kurz",
    start: "2024-10-01",
    time: "19:00",
    place: "Tišnov, fara",
    mapQuery: "Kostelní 16, Tišnov",
    text: "Beta kurz pro absolventy kurzu Alfa: každé úterý od 19:00 na tišnovské faře.",
    poster: { src: `${UPLOADS}/beta-kurz-2024-plakat.webp`, alt: "Plakát: Beta kurz 2024 na tišnovské faře" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/beta-kurz-2024-plakat.pdf`, size: 109152 }],
    longTerm: { weeklyAt: "19:00" },
  },
  {
    id: "hody-ceska-2024",
    title: "Hody v České",
    start: "2024-10-04",
    end: "2024-10-06",
    place: "Česká",
    text: "Tradiční hody v České se stavěním máje, průvodem obcí, hodovou zábavou a mší svatou v Kuřimi.",
    program: [
      { time: "pá 16:00", title: "Stavění máje stárky a hodovou chasou" },
      {
        time: "so 15:00",
        title: "Průvod obcí od sokolovny",
        note: "předání hodového práva, svěcení práva a vína u kapličky",
      },
      { time: "so 20:00", title: "Hodová zábava", note: "hraje DH Blučiňáci" },
      {
        time: "ne 11:00",
        title: "Mše svatá v kostele sv. Maří Magdalény v Kuřimi",
        note: "autobus odjíždí v 10:30 z návsi",
      },
      { time: "ne 18:00", title: "Hodové dozvuky s CM Primáš" },
    ],
    poster: { src: `${UPLOADS}/hody-ceska-2024-plakat.webp`, alt: "Plakát: Hody v České 4.–6. 10. 2024" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/hody-ceska-2024-plakat.pdf`, size: 8452270 }],
  },
  {
    id: "nadechni-se-2024",
    title: "Nadechni se",
    start: "2024-10-05",
    place: "Brno, Lidická 24",
    text: "Duchovní obnova pro rodiče malých dětí: přednáška, chvály, sdílení, čas pro pár a přímluvná modlitba.",
    body: "<p>Je možné zajistit hlídání dětí.</p>",
    poster: {
      src: `${UPLOADS}/nadechni-se-2024-plakat.webp`,
      alt: "Plakát: Nadechni se, duchovní obnova pro rodiče malých dětí",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/nadechni-se-2024-plakat.pdf`, size: 481331 }],
    links: [
      { label: "Komunita Emmanuel", href: "https://www.emmanuel.cz/" },
      { label: "rodiny@emmanuel.cz", href: "mailto:rodiny@emmanuel.cz" },
    ],
  },
  {
    id: "at-svoboda-zni-2024",
    title: "Ať svoboda zní",
    start: "2024-10-06",
    time: "18:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Koncert duchovní hudby k výročí projevu Martina Luthera Kinga „Mám sen“. Vystoupí Dej Nám Akord – DNA a Soumrak ze Zbraslavi.",
    price: "dobrovolné vstupné",
    poster: {
      src: `${UPLOADS}/at-svoboda-zni-2024-plakat.webp`,
      alt: "Plakát: Koncert duchovní hudby Ať svoboda zní 6. 10. 2024",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/at-svoboda-zni-2024-plakat.pdf`, size: 2399456 }],
  },
  {
    id: "den-narodnostnich-mensin-2024",
    title: "Den národnostních menšin",
    start: "2024-10-06",
    time: "14:00",
    place: "Kuřim, areál zámku",
    text: "Den národnostních menšin v areálu kuřimského zámku.",
    body: "<p>Akce byla kvůli nepříznivému počasí přesunuta z 15. září na 6. října.</p>",
    poster: {
      src: `${UPLOADS}/den-narodnostnich-mensin-2024-plakat.webp`,
      alt: "Plakát: Den národnostních menšin v areálu zámku Kuřim",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/den-narodnostnich-mensin-2024-plakat.jpg`, size: 1700179 }],
  },
  {
    id: "adoracni-den-2024",
    title: "Adorační den farnosti",
    start: "2024-10-12",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Adorační den naší farnosti. Na adorační stráž se zapisujte po půlhodinách do tabulky vzadu v kostele.",
  },
  {
    id: "pastoracni-veletrh-2024",
    title: "Pastorační veletrh",
    start: "2024-10-19",
    time: "9:00",
    place: "Brno, Biskupské gymnázium",
    text: "Pastorační veletrh brněnské diecéze s přednáškami a workshopy.",
    registrationDeadline: "2024-10-13",
    poster: {
      src: `${UPLOADS}/pastoracni-veletrh-2024-plakat.webp`,
      alt: "Plakát: Pastorační veletrh 19. 10. 2024, Biskupské gymnázium Brno",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/pastoracni-veletrh-2024-plakat.jpg`, size: 4439366 }],
  },
  {
    id: "misijni-nedele-2024",
    title: "Misijní neděle",
    start: "2024-10-20",
    text: "Světový den misií: sbírka této neděle je určena na podporu Papežských misijních děl.",
    poster: { src: `${UPLOADS}/misijni-nedele-2024-plakat.webp`, alt: "Plakát: Misijní neděle 20. října 2024" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/misijni-nedele-2024-plakat.jpg`, size: 4492277 }],
  },
  {
    id: "petrklic-2024-3",
    title: "Petrklíč 3/2024",
    start: "2024-10-20",
    text: "Právě vyšlo nové vydání farního zpravodaje Petrklíč.",
    attachments: [{ label: "Petrklíč 3/2024", file: "/uploads/petrklic/2024-3/petrklic-2024-3.pdf", size: 4650094 }],
  },
  {
    id: "godzone-2024",
    title: "Godzone: Nejsi na to sám",
    start: "2024-10-24",
    time: "18:00",
    place: "Brno, Výstaviště, pavilon B",
    text: "Evangelizační koncert pro mladé skupiny Godzone, doprovázený slovem a svědectvími. Vstup zdarma.",
    poster: { src: `${UPLOADS}/godzone-2024-plakat.webp`, alt: "Plakát: Godzone tour Nejsi na to sám" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/godzone-2024-plakat.jpg`, size: 5168366 }],
  },
  {
    id: "pout-ke-sv-anezce-ceske-2024",
    title: "Pouť ke sv. Anežce České",
    start: "2024-11-17",
    time: "10:15",
    place: "Předklášteří, bazilika Porta Coeli",
    text: "Mše svatá k 35. výročí sametové revoluce v bazilice Nanebevzetí Panny Marie kláštera Porta Coeli.",
    body: "<p>Mši svatou slouží P. Mgr. Michael Maria Roman Frič, OCart. Zpívá brněnský katedrální sbor Magnificat.</p>",
    poster: {
      src: `${UPLOADS}/pout-ke-sv-anezce-ceske-2024-plakat.webp`,
      alt: "Plakát: Pouť ke svaté Anežce České 17. 11. 2024",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/pout-ke-sv-anezce-ceske-2024-plakat.jpg`, size: 474993 }],
  },
  {
    id: "cervena-streda-2024",
    title: "Červená středa",
    start: "2024-11-27",
    time: "18:00",
    place: "Moravské Knínice, kostel sv. Markéty",
    text: "Připojíme se k iniciativě Červená středa na podporu tolerance a solidarity s pronásledovanými pro víru.",
    program: [
      { time: "od soumraku", title: "Kostel nasvícený červeným světlem" },
      { time: "18:00", title: "Mše svatá" },
      { time: "18:45", title: "Videoprojekce a zapálení červených svíček" },
    ],
  },
  {
    id: "nove-stranky-biskupstvi-2024",
    title: "Nové stránky brněnského biskupství",
    start: "2024-11-27",
    text: "Brněnské biskupství spustilo nové webové stránky.",
    links: [{ label: "Biskupství brněnské", href: "https://www.biskupstvi.cz/" }],
  },
  {
    id: "farni-silvestr-2024",
    title: "Farní silvestr",
    start: "2024-11-30",
    time: "17:00",
    place: "Kuřim",
    text: "Oslava začátku nového církevního roku, kterou letos připravuje společenství mladých.",
    program: [
      { time: "17:00", title: "Mše svatá" },
      { time: "18:00", title: "Zahájení" },
      { time: "18:30", title: "Hudební kvíz" },
      { time: "19:30", title: "Život s vírou", note: "Anna Macková" },
      { time: "20:30", title: "Zakončení s prskavkami" },
    ],
    body: "<p>Pro děti bude připravena dílnička a proběhne soutěž o nejlepší jednohubky.</p>",
    poster: { src: `${UPLOADS}/farni-silvestr-2024-plakat.webp`, alt: "Plakát: Farní silvestr 2024" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/farni-silvestr-2024-plakat.pdf`, size: 3112616 }],
  },
  {
    id: "vystava-betlemu-2024",
    title: "Výstava betlémů",
    start: "2024-12-01",
    end: "2024-12-31",
    place: "Kuřim",
    text: "Vánoční výstava betlémů se soutěží o nejhezčí betlém prvních tříd.",
    body: "<p>V soutěži bylo šest betlémů z prvních tříd kuřimských základních škol a jeden z Moravských Knínic. Návštěvníci odevzdali 484 hlasovacích lístků. Zvítězila 1.A ZŠ Tyršova (212 hlasů), druhá byla 1.C ZŠ Jungmannova (80 hlasů) a třetí 1.B ZŠ Tyršova (77 hlasů).</p>",
  },
  {
    id: "koncert-chantal-poullain-2024",
    title: "Koncert Chantal Poullain",
    start: "2024-12-09",
    time: "18:00",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Chantal Poullain, žáci ZŠ Jungmannova a Trio Štěpána Markoviče. Výtěžek je věnován nadaci Archa Chantal.",
    body: "<p>Vstupenky lze zakoupit v kanceláři školy a v den koncertu na místě. Výtěžek podpoří oddělení dětské psychiatrie.</p>",
    price: "350 Kč",
    poster: {
      src: `${UPLOADS}/koncert-chantal-poullain-2024-plakat.webp`,
      alt: "Plakát: Chantal Poullain a žáci ZŠ Jungmannova 9. 12. 2024",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/koncert-chantal-poullain-2024-plakat.pdf`, size: 437320 }],
  },
  {
    id: "adventni-koncert-pro-hospic-2024",
    title: "Adventní koncert pro Hospic sv. Alžběty",
    start: "2024-12-14",
    time: "18:00",
    place: "Brno, kaple sv. Alžběty",
    mapQuery: "Kamenná 36, Brno",
    text: "Zpívá Husovický spolek okrašlovací pěvecký. Koncert je spojený s prezentací hospice a sbírkou v jeho prospěch.",
    price: "zdarma",
    poster: {
      src: `${UPLOADS}/adventni-koncert-pro-hospic-2024-plakat.webp`,
      alt: "Plakát: Adventní koncert pro Hospic sv. Alžběty 14. prosince 2024",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/adventni-koncert-pro-hospic-2024-plakat.pdf`, size: 819260 }],
  },
  {
    id: "petrklic-2024-4",
    title: "Petrklíč 4/2024",
    start: "2024-12-21",
    text: "Právě vyšlo nové vydání farního časopisu Petrklíč.",
    attachments: [{ label: "Petrklíč 4/2024", file: "/uploads/petrklic/2024-4/petrklic-2024-4.pdf", size: 14355424 }],
  },
  {
    id: "porad-bohosluzeb-vanoce-2024",
    title: "Pořad bohoslužeb o Vánocích",
    start: "2024-12-22",
    end: "2025-01-12",
    place: "Kuřim a Moravské Knínice",
    text: "Vánoční pořad bohoslužeb v kuřimské farnosti, od 4. neděle adventní do svátku Křtu Páně.",
    attachments: [
      { label: "Pořad bohoslužeb", file: `${UPLOADS}/porad-bohosluzeb-vanoce-2024-porad-bohosluzeb.pdf`, size: 87803 },
    ],
  },
  {
    id: "betlemske-svetlo-2024",
    title: "Betlémské světlo",
    start: "2024-12-23",
    place: "Kuřim",
    text: "Kuřimští skauti v pondělí dopoledne roznesou Betlémské světlo po Kuřimi.",
    body: "<p>Pokud byste světlo chtěli donést k sobě nebo ke svým blízkým, pošlete jméno a adresu e-mailem do nedělního večera. Krabička na lístečky letos v kostele nebude.</p>",
    poster: { src: `${UPLOADS}/betlemske-svetlo-2024-plakat.webp`, alt: "Plakát: Betlémské světlo 2024" },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/betlemske-svetlo-2024-plakat.jpg`, size: 49157 }],
    links: [{ label: "betlemskesvetlo@skautkurim.cz", href: "mailto:betlemskesvetlo@skautkurim.cz" }],
  },
  {
    id: "vanocni-zpevy-sboru-2024",
    title: "Zpěvy chrámového sboru o Vánocích",
    start: "2024-12-24",
    end: "2024-12-25",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Kuřimský chrámový sbor zpívá Steckerovy koledy při mši na Štědrý den a na Boží hod vánoční.",
    program: [
      { time: "24. 12. 22:00", title: "Mše svatá se Steckerovými koledami" },
      { time: "25. 12. 9:30", title: "Mše svatá se Steckerovými koledami" },
    ],
    body: "<p>Diriguje Adam Janík.</p>",
    poster: {
      src: `${UPLOADS}/vanocni-zpevy-sboru-2024-pozvanka.webp`,
      alt: "Pozvánka: Vánoční koncerty kuřimského chrámového sboru, Steckerovy koledy",
    },
    attachments: [{ label: "Pozvánka", file: `${UPLOADS}/vanocni-zpevy-sboru-2024-pozvanka.pdf`, size: 2147722 }],
  },
  {
    id: "vanocni-zpivani-zs-divizna-2024",
    title: "Vánoční zpívání ZŠ DiviZna",
    start: "2024-12-26",
    time: "15:30",
    place: "Kuřim, kostel sv. Maří Magdalény",
    text: "Přijďte si zazpívat, nebo jen poslechnout známé i méně známé koledy, vánoční písně a kánony.",
    poster: {
      src: `${UPLOADS}/vanocni-zpivani-zs-divizna-2024-plakat.webp`,
      alt: "Plakát: Vánoční zpívání ZŠ DiviZna 26. prosince 2024",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/vanocni-zpivani-zs-divizna-2024-plakat.pdf`, size: 4611053 }],
  },
  {
    id: "vecer-s-koledami-2024",
    title: "Večer s koledami",
    start: "2024-12-29",
    time: "17:30",
    place: "Moravské Knínice, kostel sv. Markéty",
    text: "Večer s koledami a Českou mší vánoční Jakuba Jana Ryby v podání mužského sboru, scholy a orchestru.",
    body: "<p>Rybovu mši uslyšíte také při slavnostní bohoslužbě na Boží hod vánoční 25. prosince v 11:00.</p>",
    poster: {
      src: `${UPLOADS}/vecer-s-koledami-2024-plakat.webp`,
      alt: "Plakát: Česká mše vánoční J. J. Ryby v Moravských Knínicích",
    },
    attachments: [{ label: "Plakát", file: `${UPLOADS}/vecer-s-koledami-2024-plakat.pdf`, size: 165696 }],
  },
];
